import Nightstream.Rv64IM.Stage1.BytecodeFetchProjection

namespace Nightstream.Rv64IM

namespace BytecodeFetchProjectionInterface

abbrev bytecodeFetchFamily := Nightstream.Rv64IM.bytecodeFetchFamily
abbrev BytecodeFetchRecordBound := @Nightstream.Rv64IM.BytecodeFetchRecordBound
abbrev bytecodeFetchProjection := @Nightstream.Rv64IM.bytecodeFetchProjection

abbrev bytecodeFetchRecordBound_of_fetchDecodeBound :=
  @Nightstream.Rv64IM.bytecodeFetchRecordBound_of_fetchDecodeBound
abbrev bytecodeFetchProjection_is_projectionFamily :=
  @Nightstream.Rv64IM.bytecodeFetchProjection_is_projectionFamily
abbrev bytecodeFetchProjection_not_mainLane :=
  @Nightstream.Rv64IM.bytecodeFetchProjection_not_mainLane
abbrev bytecodeFetchProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Rv64IM.bytecodeFetchProjection_decide_eq_foldSeparate_of_supported
abbrev bytecodeFetchProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Rv64IM.bytecodeFetchProjection_decide_eq_exportFinal_of_unsupported

end BytecodeFetchProjectionInterface

end Nightstream.Rv64IM
