import Nightstream.Rv64IM.Stage1.ExecutionRowBinding

namespace Nightstream.Rv64IM

namespace ExecutionRowBindingInterface

abbrev executionRowFamily := Nightstream.Rv64IM.executionRowFamily
abbrev aluSubtableFamily := Nightstream.Rv64IM.aluSubtableFamily
abbrev branchConditionFamily := Nightstream.Rv64IM.branchConditionFamily
abbrev maxAluQuerySlots := Nightstream.Rv64IM.maxAluQuerySlots
abbrev maxBranchQuerySlots := Nightstream.Rv64IM.maxBranchQuerySlots
abbrev byteParallelSlotIndex := Nightstream.Rv64IM.byteParallelSlotIndex
abbrev mulGridSlotIndex := Nightstream.Rv64IM.mulGridSlotIndex
abbrev byteParallelSlotIndex_lt_maxAluQuerySlots :=
  @Nightstream.Rv64IM.byteParallelSlotIndex_lt_maxAluQuerySlots
abbrev mulGridSlotIndex_lt_maxAluQuerySlots :=
  @Nightstream.Rv64IM.mulGridSlotIndex_lt_maxAluQuerySlots
abbrev ExecutionResults := Nightstream.Rv64IM.ExecutionResults
abbrev Stage1LaneView := Nightstream.Rv64IM.Stage1LaneView
abbrev ExecutionSlotUsage := Nightstream.Rv64IM.ExecutionSlotUsage
abbrev DenseAluSlotUsageBound := Nightstream.Rv64IM.DenseAluSlotUsageBound
abbrev DenseBranchSlotUsageBound := Nightstream.Rv64IM.DenseBranchSlotUsageBound
abbrev DenseSlotManifestBound := Nightstream.Rv64IM.DenseSlotManifestBound
abbrev branchTakenMux := Nightstream.Rv64IM.branchTakenMux
abbrev TakenTargetAlignmentBound := @Nightstream.Rv64IM.TakenTargetAlignmentBound
abbrev MulUNoOverflowBound := @Nightstream.Rv64IM.MulUNoOverflowBound
abbrev Stage1SupportBound := @Nightstream.Rv64IM.Stage1SupportBound
abbrev Stage1LinkageBound := @Nightstream.Rv64IM.Stage1LinkageBound
abbrev ExecutionRowProofPackage := Nightstream.Rv64IM.ExecutionRowProofPackage
abbrev takenTargetAlignmentBound_of_stage1Support :=
  @Nightstream.Rv64IM.takenTargetAlignmentBound_of_stage1Support
abbrev mulUNoOverflowBound_of_stage1Support :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_stage1Support
abbrev stage1LinkageBound_of_executionRow :=
  @Nightstream.Rv64IM.stage1LinkageBound_of_executionRow
abbrev laneAluOut_eq_resultsAluResult_of_stage1LinkageBound :=
  @Nightstream.Rv64IM.laneAluOut_eq_resultsAluResult_of_stage1LinkageBound
abbrev laneAluOut_eq_resultsAluResult_of_executionRow :=
  @Nightstream.Rv64IM.laneAluOut_eq_resultsAluResult_of_executionRow
abbrev takenTargetAlignmentBound_of_executionRow :=
  @Nightstream.Rv64IM.takenTargetAlignmentBound_of_executionRow
abbrev mulUNoOverflowBound_of_executionRow :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_executionRow
abbrev executionRowProjection := @Nightstream.Rv64IM.executionRowProjection
abbrev aluSubtableProjection := @Nightstream.Rv64IM.aluSubtableProjection
abbrev branchConditionProjection := @Nightstream.Rv64IM.branchConditionProjection

abbrev executionRowProjection_is_projectionFamily :=
  @Nightstream.Rv64IM.executionRowProjection_is_projectionFamily
abbrev executionRowProjection_decide_eq_mergeMain_iff :=
  @Nightstream.Rv64IM.executionRowProjection_decide_eq_mergeMain_iff
abbrev executionRowProjection_decide_eq_foldSeparate_of_supported_not_main :=
  @Nightstream.Rv64IM.executionRowProjection_decide_eq_foldSeparate_of_supported_not_main
abbrev executionRowProjection_decide_eq_exportFinal_of_unsupported_not_main :=
  @Nightstream.Rv64IM.executionRowProjection_decide_eq_exportFinal_of_unsupported_not_main
abbrev aluSubtableProjection_is_projectionFamily :=
  @Nightstream.Rv64IM.aluSubtableProjection_is_projectionFamily
abbrev aluSubtableProjection_not_mainLane :=
  @Nightstream.Rv64IM.aluSubtableProjection_not_mainLane
abbrev aluSubtableProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Rv64IM.aluSubtableProjection_decide_eq_foldSeparate_of_supported
abbrev aluSubtableProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Rv64IM.aluSubtableProjection_decide_eq_exportFinal_of_unsupported
abbrev branchConditionProjection_is_projectionFamily :=
  @Nightstream.Rv64IM.branchConditionProjection_is_projectionFamily
abbrev branchConditionProjection_not_mainLane :=
  @Nightstream.Rv64IM.branchConditionProjection_not_mainLane
abbrev branchConditionProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Rv64IM.branchConditionProjection_decide_eq_foldSeparate_of_supported
abbrev branchConditionProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Rv64IM.branchConditionProjection_decide_eq_exportFinal_of_unsupported

end ExecutionRowBindingInterface

end Nightstream.Rv64IM
