import Nightstream.Rv64IM.Stage1.ImportedSemantics

namespace Nightstream.Rv64IM

namespace ImportedSemanticsInterface

abbrev stage1EffectRowCount := Nightstream.Rv64IM.stage1EffectRowCount
abbrev stage1CommitRowCount := Nightstream.Rv64IM.stage1CommitRowCount
abbrev stage1RealRowCount := Nightstream.Rv64IM.stage1RealRowCount
abbrev stage1PreservesX0Count := Nightstream.Rv64IM.stage1PreservesX0Count
abbrev executionEffectRowCount := Nightstream.Rv64IM.executionEffectRowCount
abbrev executionCommitRowCount := Nightstream.Rv64IM.executionCommitRowCount
abbrev executionRealRowCount := Nightstream.Rv64IM.executionRealRowCount
abbrev executionPreservesX0Count := Nightstream.Rv64IM.executionPreservesX0Count
abbrev ImportedStage1ProjectionSemantics := @Nightstream.Rv64IM.ImportedStage1ProjectionSemantics
abbrev importedStage1ProjectionSemanticsCheck := @Nightstream.Rv64IM.importedStage1ProjectionSemanticsCheck
abbrev stage1Row_at_index_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1Row_at_index_of_importedStage1Closure
abbrev stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure
abbrev stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure
abbrev stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure
abbrev stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure
abbrev importedStage1ProjectionSemantics_of_importedStage1Closure :=
  @Nightstream.Rv64IM.importedStage1ProjectionSemantics_of_importedStage1Closure

end ImportedSemanticsInterface

end Nightstream.Rv64IM
