import Nightstream.Rv64IM.Stage1.ImportedClosure

namespace Nightstream.Rv64IM

namespace ImportedClosureInterface

abbrev stage1RowBindingOfExecutionRow := Nightstream.Rv64IM.stage1RowBindingOfExecutionRow
abbrev stage1SummaryOfExecutionRows := Nightstream.Rv64IM.stage1SummaryOfExecutionRows
abbrev ImportedStage1Closure := @Nightstream.Rv64IM.ImportedStage1Closure
abbrev importedStage1ClosureCheck := @Nightstream.Rv64IM.importedStage1ClosureCheck
abbrev stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure
abbrev stage1Rows_eq_map_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1Rows_eq_map_of_importedStage1Closure
abbrev stage1Rows_length_eq_executionRows_length_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1Rows_length_eq_executionRows_length_of_importedStage1Closure
abbrev stage1RowBinding_mem_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1RowBinding_mem_of_importedStage1Closure

end ImportedClosureInterface

end Nightstream.Rv64IM
