import Nightstream.Rv64IM.Stage1.ImportedLocalSemantics

namespace Nightstream.Rv64IM

namespace ImportedLocalSemanticsInterface

abbrev stage1FirstInSequenceCount := Nightstream.Rv64IM.stage1FirstInSequenceCount
abbrev executionFirstInSequenceCount := Nightstream.Rv64IM.executionFirstInSequenceCount
abbrev ImportedStage1RowLocalSemantics := @Nightstream.Rv64IM.ImportedStage1RowLocalSemantics
abbrev ImportedStage1LocalSemantics := @Nightstream.Rv64IM.ImportedStage1LocalSemantics
abbrev importedStage1LocalSemanticsCheck := @Nightstream.Rv64IM.importedStage1LocalSemanticsCheck
abbrev stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure :=
  @Nightstream.Rv64IM.stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure
abbrev importedStage1RowLocalSemantics_of_rowBinding :=
  @Nightstream.Rv64IM.importedStage1RowLocalSemantics_of_rowBinding
abbrev importedStage1LocalSemantics_of_importedStage1Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage1LocalSemantics_of_importedStage1Closure_and_sequence

end ImportedLocalSemanticsInterface

end Nightstream.Rv64IM
