import Nightstream.Rv64IM.AcceptedArtifactKernelDesignBridgeClosure

namespace Nightstream.Rv64IM

namespace AcceptedArtifactKernelDesignBridgeClosureInterface

abbrev KernelDesignBridgeClosureField :=
  Nightstream.Rv64IM.KernelDesignBridgeClosureField
abbrev kernelDesignBridgeClosureFieldName :=
  Nightstream.Rv64IM.kernelDesignBridgeClosureFieldName
abbrev requiredKernelDesignBridgeClosureFields :=
  Nightstream.Rv64IM.requiredKernelDesignBridgeClosureFields
abbrev kernelDesignBridgeClosureFieldPresent :=
  Nightstream.Rv64IM.kernelDesignBridgeClosureFieldPresent
abbrev kernelDesignBridgeClosureChecks :=
  Nightstream.Rv64IM.kernelDesignBridgeClosureChecks
abbrev kernelDesignBridgeClosureAccepted :=
  Nightstream.Rv64IM.kernelDesignBridgeClosureAccepted
abbrev missingKernelDesignBridgeClosureFields :=
  Nightstream.Rv64IM.missingKernelDesignBridgeClosureFields
abbrev kernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.kernelDesignBridgeRustExportBlockers
abbrev uniqueKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.uniqueKernelDesignBridgeRustExportBlockers
abbrev Rv64imKernelDesignBridgeClosureReport :=
  Nightstream.Rv64IM.Rv64imKernelDesignBridgeClosureReport
abbrev rv64imAcceptedArtifactKernelDesignBridgeClosureChecks :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactKernelDesignBridgeClosureChecks
abbrev validGeneratedRv64imAcceptedArtifactKernelDesignBridgeClosureCases :=
  Nightstream.Rv64IM.validGeneratedRv64imAcceptedArtifactKernelDesignBridgeClosureCases
abbrev rv64imAcceptedArtifactKernelDesignBridgeClosureReports :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactKernelDesignBridgeClosureReports

end AcceptedArtifactKernelDesignBridgeClosureInterface

end Nightstream.Rv64IM
