import Nightstream.Rv64IM.AcceptedArtifactRootExecutionClosure

namespace Nightstream.Rv64IM

namespace AcceptedArtifactRootExecutionClosureInterface

abbrev RootExecutionClosureField := Nightstream.Rv64IM.RootExecutionClosureField
abbrev rootExecutionClosureFieldName := Nightstream.Rv64IM.rootExecutionClosureFieldName
abbrev requiredRootExecutionClosureFields :=
  Nightstream.Rv64IM.requiredRootExecutionClosureFields
abbrev rootExecutionClosureFieldPresent :=
  Nightstream.Rv64IM.rootExecutionClosureFieldPresent
abbrev rootExecutionClosureChecks := Nightstream.Rv64IM.rootExecutionClosureChecks
abbrev rootExecutionClosureAccepted := Nightstream.Rv64IM.rootExecutionClosureAccepted
abbrev missingRootExecutionClosureFields :=
  Nightstream.Rv64IM.missingRootExecutionClosureFields
abbrev Rv64imRootExecutionClosureReport :=
  Nightstream.Rv64IM.Rv64imRootExecutionClosureReport
abbrev rv64imAcceptedArtifactRootExecutionClosureChecks :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactRootExecutionClosureChecks
abbrev validGeneratedRv64imAcceptedArtifactRootExecutionClosureCases :=
  Nightstream.Rv64IM.validGeneratedRv64imAcceptedArtifactRootExecutionClosureCases
abbrev rv64imAcceptedArtifactRootExecutionClosureReports :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactRootExecutionClosureReports

end AcceptedArtifactRootExecutionClosureInterface

end Nightstream.Rv64IM
