import Nightstream.Rv64IM.AcceptedArtifactRootExecutionSemanticsClosure

namespace Nightstream.Rv64IM

namespace AcceptedArtifactRootExecutionSemanticsClosureInterface

abbrev RootExecutionSemanticsClosureField :=
  Nightstream.Rv64IM.RootExecutionSemanticsClosureField
abbrev rootExecutionSemanticsClosureFieldName :=
  Nightstream.Rv64IM.rootExecutionSemanticsClosureFieldName
abbrev requiredRootExecutionSemanticsClosureFields :=
  Nightstream.Rv64IM.requiredRootExecutionSemanticsClosureFields
abbrev rootExecutionSemanticsClosureFieldPresent :=
  Nightstream.Rv64IM.rootExecutionSemanticsClosureFieldPresent
abbrev rootExecutionSemanticsClosureChecks :=
  Nightstream.Rv64IM.rootExecutionSemanticsClosureChecks
abbrev rootExecutionSemanticsClosureAccepted :=
  Nightstream.Rv64IM.rootExecutionSemanticsClosureAccepted
abbrev missingRootExecutionSemanticsClosureFields :=
  Nightstream.Rv64IM.missingRootExecutionSemanticsClosureFields
abbrev rootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.rootExecutionSemanticsRustExportBlockers
abbrev uniqueRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRootExecutionSemanticsRustExportBlockers
abbrev requiredRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.requiredRootExecutionSemanticsRustExportBlockers
abbrev uniqueRequiredRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredRootExecutionSemanticsRustExportBlockers
abbrev Rv64imRootExecutionSemanticsClosureReport :=
  Nightstream.Rv64IM.Rv64imRootExecutionSemanticsClosureReport
abbrev rv64imAcceptedArtifactRootExecutionSemanticsClosureChecks :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactRootExecutionSemanticsClosureChecks
abbrev validGeneratedRv64imAcceptedArtifactRootExecutionSemanticsClosureCases :=
  Nightstream.Rv64IM.validGeneratedRv64imAcceptedArtifactRootExecutionSemanticsClosureCases
abbrev rv64imAcceptedArtifactRootExecutionSemanticsClosureReports :=
  Nightstream.Rv64IM.rv64imAcceptedArtifactRootExecutionSemanticsClosureReports

end AcceptedArtifactRootExecutionSemanticsClosureInterface

end Nightstream.Rv64IM
