import Nightstream.Rv64IM.Stage3.ExportSemantics

namespace Nightstream.Rv64IM

namespace Stage3ExportSemanticsInterface

abbrev Stage3ContinuitySemantics := @Nightstream.Rv64IM.Stage3ContinuitySemantics
abbrev Stage3ExportSemantics := @Nightstream.Rv64IM.Stage3ExportSemantics
abbrev pcAdjacentBridge_of_stage3ContinuitySemantics :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_stage3ContinuitySemantics
abbrev activePrefixContinuity_of_stage3ContinuitySemantics :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_stage3ContinuitySemantics
abbrev fullHaltedExecutionClaim_of_stage3ExportSemantics :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_stage3ExportSemantics
abbrev stage3ContinuitySemantics_of_stage3Refinement :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_stage3Refinement
abbrev stage3ExportSemantics_of_stage3Refinement :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_stage3Refinement

end Stage3ExportSemanticsInterface

end Nightstream.Rv64IM
