import Nightstream.Rv64IM.Stage3.ImportedExportSemantics

namespace Nightstream.Rv64IM

namespace ImportedExportSemanticsInterface

abbrev ImportedStage3ExportSemantics := @Nightstream.Rv64IM.ImportedStage3ExportSemantics
abbrev importedStage3ExportSemanticsCheck := @Nightstream.Rv64IM.importedStage3ExportSemanticsCheck
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics
abbrev stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics :=
  @Nightstream.Rv64IM.stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics
abbrev importedStage3ExportSemantics_of_importedStage3Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage3ExportSemantics_of_importedStage3Closure_and_sequence

end ImportedExportSemanticsInterface

end Nightstream.Rv64IM
