import Nightstream.Rv64IM.Stage3.ImportedClosure

namespace Nightstream.Rv64IM

namespace ImportedClosureInterface

abbrev realExecutionRows := Nightstream.Rv64IM.realExecutionRows
abbrev stage3SummaryOfExecutionRows := Nightstream.Rv64IM.stage3SummaryOfExecutionRows
abbrev ImportedStage3Closure := @Nightstream.Rv64IM.ImportedStage3Closure
abbrev importedStage3ClosureCheck := @Nightstream.Rv64IM.importedStage3ClosureCheck
abbrev stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure
abbrev stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure
abbrev stage3Halted_eq_executionHalted_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3Halted_eq_executionHalted_of_importedStage3Closure

end ImportedClosureInterface

end Nightstream.Rv64IM
