import Nightstream.Rv64IM.Stage3.ImportedLocalSemantics

namespace Nightstream.Rv64IM

namespace ImportedLocalSemanticsInterface

abbrev stage3ContinuityCount := Nightstream.Rv64IM.stage3ContinuityCount
abbrev stage3FinalStepCount := Nightstream.Rv64IM.stage3FinalStepCount
abbrev stage3AllContinuityHold := Nightstream.Rv64IM.stage3AllContinuityHold
abbrev executionContinuityCount := Nightstream.Rv64IM.executionContinuityCount
abbrev executionFinalStepCount := Nightstream.Rv64IM.executionFinalStepCount
abbrev executionAllContinuityHold := Nightstream.Rv64IM.executionAllContinuityHold
abbrev executionHalted := Nightstream.Rv64IM.executionHalted
abbrev ImportedStage3LocalSemantics := @Nightstream.Rv64IM.ImportedStage3LocalSemantics
abbrev importedStage3LocalSemanticsCheck := @Nightstream.Rv64IM.importedStage3LocalSemanticsCheck
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure
abbrev importedStage3LocalSemantics_of_importedStage3Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage3LocalSemantics_of_importedStage3Closure_and_sequence

end ImportedLocalSemanticsInterface

end Nightstream.Rv64IM
