import Nightstream.Rv64IM.Stage3.ImportedContinuitySemantics

namespace Nightstream.Rv64IM

namespace ImportedContinuitySemanticsInterface

abbrev continuityEventLocalSemantics := @Nightstream.Rv64IM.continuityEventLocalSemantics
abbrev continuityEventLocalSemanticsCheck := @Nightstream.Rv64IM.continuityEventLocalSemanticsCheck
abbrev ImportedStage3ContinuitySemantics := @Nightstream.Rv64IM.ImportedStage3ContinuitySemantics
abbrev importedStage3ContinuitySemanticsCheck := @Nightstream.Rv64IM.importedStage3ContinuitySemanticsCheck
abbrev continuityEventLocalSemantics_of_mem_of_importedStage3Closure :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics_of_mem_of_importedStage3Closure
abbrev importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence

end ImportedContinuitySemanticsInterface

end Nightstream.Rv64IM
