import Nightstream.Rv64IM.Stage3.Stage3Refinement

namespace Nightstream.Rv64IM

namespace Stage3RefinementInterface

abbrev Stage3RefinementPackage := Nightstream.Rv64IM.Stage3RefinementPackage
abbrev fullHaltedExecutionClaim_of_stage3Refinement :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_stage3Refinement
abbrev pcAdjacentBridgeProofPackage_of_stage3Refinement :=
  @Nightstream.Rv64IM.pcAdjacentBridgeProofPackage_of_stage3Refinement

end Stage3RefinementInterface

end Nightstream.Rv64IM
