import Nightstream.Rv64IM.Execution.CommittedSequenceSoundness

namespace Nightstream.Rv64IM

abbrev AdviceSequenceCorrect := @CommittedSequenceCorrect
abbrev AdviceSequenceDeterministic := @CommittedSequenceDeterministic
abbrev AdviceSequenceProofPackage := @CommittedSequenceProofPackage
abbrev adviceSequenceDeterministic_of_correct := @committedSequenceDeterministic_of_correct
abbrev adviceSequenceProofPackage_of_correct := @committedSequenceProofPackage_of_correct

end Nightstream.Rv64IM
