import Nightstream.Rv64IM.Execution.ControlFlowSemantics

namespace Nightstream.Rv64IM

namespace ControlFlowSemanticsInterface

abbrev ControlFlowExecutionFacts := @Nightstream.Rv64IM.ControlFlowExecutionFacts
abbrev controlFlowExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.controlFlowExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_controlFlowExecutionFacts
abbrev adjacentStates_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_controlFlowExecutionFacts
abbrev preparedStep_matches_row_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_controlFlowExecutionFacts
abbrev successor_matches_rows_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_controlFlowExecutionFacts
abbrev row_has_opcodeClass_at_index_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_controlFlowExecutionFacts
abbrev takenTargetAlignment_of_controlFlowExecutionFacts :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_controlFlowExecutionFacts
noncomputable abbrev controlFlowExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.controlFlowExecutionFacts_of_stepComposition

end ControlFlowSemanticsInterface

end Nightstream.Rv64IM
