import Nightstream.Rv64IM.Execution.ControlFlowLoweringSemantics

namespace Nightstream.Rv64IM

namespace ControlFlowLoweringSemanticsInterface

abbrev fetchDecodeBound_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_controlFlowLoweringSemantics
abbrev decodedRow_valid_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_controlFlowLoweringSemantics
abbrev decodeHandoffBound_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_controlFlowLoweringSemantics
abbrev x0WritePreserved_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_controlFlowLoweringSemantics
abbrev nonFinalRdTarget_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_controlFlowLoweringSemantics
abbrev frame_row_eq_at_index_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_controlFlowLoweringSemantics
abbrev adjacentStates_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_controlFlowLoweringSemantics
abbrev preparedStep_matches_row_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_controlFlowLoweringSemantics
abbrev successor_matches_rows_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_controlFlowLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_controlFlowLoweringSemantics
abbrev takenTargetAlignment_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_controlFlowLoweringSemantics
abbrev sequenceCorrect_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_controlFlowLoweringSemantics
abbrev sequenceDeterministic_of_controlFlowLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_controlFlowLoweringSemantics

end ControlFlowLoweringSemanticsInterface

end Nightstream.Rv64IM
