import Nightstream.Rv64IM.Execution.ControlFlowOpcodeSemantics

namespace Nightstream.Rv64IM

namespace ControlFlowOpcodeSemanticsInterface

abbrev ControlFlowOpcode := @Nightstream.Rv64IM.ControlFlowOpcode
abbrev ControlFlowOpcodeBound := @Nightstream.Rv64IM.ControlFlowOpcodeBound
abbrev isJal_of_controlFlowOpcodeBound := @Nightstream.Rv64IM.isJal_of_controlFlowOpcodeBound
abbrev isJalr_of_controlFlowOpcodeBound := @Nightstream.Rv64IM.isJalr_of_controlFlowOpcodeBound
abbrev isBranch_of_controlFlowOpcodeBound := @Nightstream.Rv64IM.isBranch_of_controlFlowOpcodeBound
abbrev branchOp_of_controlFlowOpcodeBound := @Nightstream.Rv64IM.branchOp_of_controlFlowOpcodeBound
abbrev jal_flags_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.jal_flags_of_controlFlowOpcodeSemantics
abbrev jalr_flags_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.jalr_flags_of_controlFlowOpcodeSemantics
abbrev branch_flags_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.branch_flags_of_controlFlowOpcodeSemantics
abbrev lane_isJal_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.lane_isJal_of_controlFlowOpcodeSemantics
abbrev lane_isJalr_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.lane_isJalr_of_controlFlowOpcodeSemantics
abbrev lane_isBranch_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.lane_isBranch_of_controlFlowOpcodeSemantics
abbrev branchOp_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.branchOp_of_controlFlowOpcodeSemantics
abbrev takenTargetAlignment_of_jalOpcodeSemantics :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jalOpcodeSemantics
abbrev takenTargetAlignment_of_jalrOpcodeSemantics :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jalrOpcodeSemantics
abbrev takenBranchMux_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.takenBranchMux_of_controlFlowOpcodeSemantics
abbrev takenTargetAlignment_of_takenBranchOpcodeSemantics :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_takenBranchOpcodeSemantics
abbrev sequenceCorrect_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_controlFlowOpcodeSemantics
abbrev sequenceDeterministic_of_controlFlowOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_controlFlowOpcodeSemantics

end ControlFlowOpcodeSemanticsInterface

end Nightstream.Rv64IM
