import Nightstream.Rv64IM.Execution.ExactOpcodeFamilySemantics

namespace Nightstream.Rv64IM

namespace ExactOpcodeFamilySemanticsInterface

abbrev ExactOpcodeFamilySemantics := @Nightstream.Rv64IM.ExactOpcodeFamilySemantics
noncomputable abbrev exactOpcodeFamilySemantics_of_stepComposition :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_stepComposition
abbrev nativeAluSequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.nativeAluSequenceCorrect_of_exactOpcodeFamilySemantics
abbrev nativeAluSequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.nativeAluSequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev wordShiftSequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.wordShiftSequenceCorrect_of_exactOpcodeFamilySemantics
abbrev wordShiftSequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.wordShiftSequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev controlFlowSequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.controlFlowSequenceCorrect_of_exactOpcodeFamilySemantics
abbrev controlFlowSequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.controlFlowSequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev narrowMemorySequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.narrowMemorySequenceCorrect_of_exactOpcodeFamilySemantics
abbrev narrowMemorySequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.narrowMemorySequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev multiplySequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.multiplySequenceCorrect_of_exactOpcodeFamilySemantics
abbrev multiplySequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.multiplySequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev unsignedDivRemSequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.unsignedDivRemSequenceCorrect_of_exactOpcodeFamilySemantics
abbrev unsignedDivRemSequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.unsignedDivRemSequenceDeterministic_of_exactOpcodeFamilySemantics
abbrev signedDivRemSequenceCorrect_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.signedDivRemSequenceCorrect_of_exactOpcodeFamilySemantics
abbrev signedDivRemSequenceDeterministic_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.signedDivRemSequenceDeterministic_of_exactOpcodeFamilySemantics

end ExactOpcodeFamilySemanticsInterface

end Nightstream.Rv64IM
