import Nightstream.Rv64IM.Execution.ExactAlignedMemoryOpcodeSemantics

namespace Nightstream.Rv64IM

namespace ExactAlignedMemoryOpcodeSemanticsInterface

abbrev ExactAlignedMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.ExactAlignedMemoryOpcodeSemantics
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_stepComposition :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_stepComposition

end ExactAlignedMemoryOpcodeSemanticsInterface

end Nightstream.Rv64IM
