import Nightstream.Rv64IM.Execution.ExactNarrowMemoryHelperResultSemantics

namespace Nightstream.Rv64IM

namespace ExactNarrowMemoryHelperResultSemanticsInterface

abbrev ExactNarrowMemoryHelperResultSemantics :=
  @Nightstream.Rv64IM.ExactNarrowMemoryHelperResultSemantics
abbrev exactNarrowMemoryHelperResultSemantics_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_exactOpcodeFamilySemantics
abbrev exactNarrowMemoryHelperResultSemantics_of_stepComposition :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_stepComposition
abbrev loadExtractHelperResult_of_exactNarrowMemoryHelperResultSemantics :=
  @Nightstream.Rv64IM.loadExtractHelperResult_of_exactNarrowMemoryHelperResultSemantics
abbrev storeBlendHelperResult_of_exactNarrowMemoryHelperResultSemantics :=
  @Nightstream.Rv64IM.storeBlendHelperResult_of_exactNarrowMemoryHelperResultSemantics

end ExactNarrowMemoryHelperResultSemanticsInterface

end Nightstream.Rv64IM
