import Nightstream.Rv64IM.Execution.ExactWordArithmeticSemantics

namespace Nightstream.Rv64IM

namespace ExactWordArithmeticSemanticsInterface

abbrev ExactWordArithmeticSemantics :=
  @Nightstream.Rv64IM.ExactWordArithmeticSemantics
abbrev exactWordArithmeticSemantics_of_exactOpcodeFamilySemantics :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_exactOpcodeFamilySemantics
abbrev exactWordArithmeticSemantics_of_stepComposition :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_stepComposition

end ExactWordArithmeticSemanticsInterface

end Nightstream.Rv64IM
