import Nightstream.Rv64IM.Execution.ExactOpcodeClassSemantics

namespace Nightstream.Rv64IM

namespace ExactOpcodeClassSemanticsInterface

abbrev OpcodeClassExecutionFacts := @Nightstream.Rv64IM.OpcodeClassExecutionFacts
abbrev opcodeClassExecutionFacts_of_opcodeClassProof :=
  @Nightstream.Rv64IM.opcodeClassExecutionFacts_of_opcodeClassProof
abbrev frame_row_eq_at_index_of_opcodeClassExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_opcodeClassExecutionFacts
abbrev adjacentStates_of_opcodeClassExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_opcodeClassExecutionFacts
abbrev preparedStep_matches_row_of_opcodeClassExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_opcodeClassExecutionFacts
abbrev successor_matches_rows_of_opcodeClassExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_opcodeClassExecutionFacts
abbrev row_has_opcodeClass_at_index_of_opcodeClassExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_opcodeClassExecutionFacts
abbrev CanonicalOpcodeClassSemantics :=
  @Nightstream.Rv64IM.CanonicalOpcodeClassSemantics
abbrev canonicalOpcodeClassSemantics_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_canonicalOpcodeProofs
abbrev nativeAluFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.nativeAluFacts_of_canonicalOpcodeProofs
abbrev wordShiftFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.wordShiftFacts_of_canonicalOpcodeProofs
abbrev controlFlowFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.controlFlowFacts_of_canonicalOpcodeProofs
abbrev narrowMemoryFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_canonicalOpcodeProofs
abbrev multiplyFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.multiplyFacts_of_canonicalOpcodeProofs
abbrev unsignedDivRemFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_canonicalOpcodeProofs
abbrev signedDivRemFacts_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_canonicalOpcodeProofs
noncomputable abbrev canonicalOpcodeClassSemantics_of_stepComposition :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_stepComposition
noncomputable abbrev nativeAluFacts_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluFacts_of_stepComposition
noncomputable abbrev wordShiftFacts_of_stepComposition :=
  @Nightstream.Rv64IM.wordShiftFacts_of_stepComposition
noncomputable abbrev controlFlowFacts_of_stepComposition :=
  @Nightstream.Rv64IM.controlFlowFacts_of_stepComposition
noncomputable abbrev narrowMemoryFacts_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_stepComposition
noncomputable abbrev multiplyFacts_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyFacts_of_stepComposition
noncomputable abbrev unsignedDivRemFacts_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_stepComposition
noncomputable abbrev signedDivRemFacts_of_stepComposition :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_stepComposition

end ExactOpcodeClassSemanticsInterface

end Nightstream.Rv64IM
