import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemantics

namespace Nightstream.Rv64IM

namespace HardOpLoweringRefinementSemanticsInterface

abbrev normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end HardOpLoweringRefinementSemanticsInterface

end Nightstream.Rv64IM
