import Nightstream.Rv64IM.Execution.ImportedSequenceSemantics

namespace Nightstream.Rv64IM

namespace ImportedSequenceSemanticsInterface

abbrev ImportedExpandedRowSequenceSemantics :=
  @Nightstream.Rv64IM.ImportedExpandedRowSequenceSemantics
abbrev importedExpandedRowSequenceSemanticsCheck :=
  @Nightstream.Rv64IM.importedExpandedRowSequenceSemanticsCheck

end ImportedSequenceSemanticsInterface

end Nightstream.Rv64IM
