import Nightstream.Rv64IM.Execution.LoweringRefinement

namespace Nightstream.Rv64IM

namespace LoweringRefinementInterface

abbrev ImportedLoweringRow := @Nightstream.Rv64IM.ImportedLoweringRow
abbrev inlineScratchRegisterBase := @Nightstream.Rv64IM.inlineScratchRegisterBase
abbrev inlineScratchRegisterLimit := @Nightstream.Rv64IM.inlineScratchRegisterLimit
abbrev isInlineScratchRegister := @Nightstream.Rv64IM.isInlineScratchRegister
abbrev rowSequenceMetadataBound := @Nightstream.Rv64IM.rowSequenceMetadataBound
abbrev isInlineScratchCleanupRow := @Nightstream.Rv64IM.isInlineScratchCleanupRow
abbrev uniqueRealRowAt := @Nightstream.Rv64IM.uniqueRealRowAt
abbrev SingleRowReferenceSpec := @Nightstream.Rv64IM.SingleRowReferenceSpec
abbrev singleRowReferenceLowering := @Nightstream.Rv64IM.singleRowReferenceLowering
abbrev nativeAluWriteRdSingleRowSpec := @Nightstream.Rv64IM.nativeAluWriteRdSingleRowSpec
abbrev nativeAluNoWriteSingleRowSpec := @Nightstream.Rv64IM.nativeAluNoWriteSingleRowSpec
abbrev alignedMemoryLoadSingleRowSpec := @Nightstream.Rv64IM.alignedMemoryLoadSingleRowSpec
abbrev alignedMemoryStoreSingleRowSpec := @Nightstream.Rv64IM.alignedMemoryStoreSingleRowSpec
abbrev narrowMemoryLoadSingleRowSpec := @Nightstream.Rv64IM.narrowMemoryLoadSingleRowSpec
abbrev narrowMemoryStoreSingleRowSpec := @Nightstream.Rv64IM.narrowMemoryStoreSingleRowSpec
abbrev controlFlowWriteRdSingleRowSpec := @Nightstream.Rv64IM.controlFlowWriteRdSingleRowSpec
abbrev controlFlowNoWriteSingleRowSpec := @Nightstream.Rv64IM.controlFlowNoWriteSingleRowSpec
abbrev multiplyWriteRdSingleRowSpec := @Nightstream.Rv64IM.multiplyWriteRdSingleRowSpec

abbrev MulReferenceStep := @Nightstream.Rv64IM.MulReferenceStep
abbrev MulhuReferenceStep := @Nightstream.Rv64IM.MulhuReferenceStep
abbrev MulwReferenceStep := @Nightstream.Rv64IM.MulwReferenceStep
abbrev MulhReferenceStep := @Nightstream.Rv64IM.MulhReferenceStep
abbrev MulhsuReferenceStep := @Nightstream.Rv64IM.MulhsuReferenceStep
abbrev UnsignedDivRemReferenceStep := @Nightstream.Rv64IM.UnsignedDivRemReferenceStep
abbrev SignedDivRemReferenceStep := @Nightstream.Rv64IM.SignedDivRemReferenceStep

abbrev mulReferenceLowering := @Nightstream.Rv64IM.mulReferenceLowering
abbrev mulhuReferenceLowering := @Nightstream.Rv64IM.mulhuReferenceLowering
abbrev mulwReferenceLowering := @Nightstream.Rv64IM.mulwReferenceLowering
abbrev mulhReferenceLowering := @Nightstream.Rv64IM.mulhReferenceLowering
abbrev mulhsuReferenceLowering := @Nightstream.Rv64IM.mulhsuReferenceLowering
abbrev divuReferenceLowering := @Nightstream.Rv64IM.divuReferenceLowering
abbrev remuReferenceLowering := @Nightstream.Rv64IM.remuReferenceLowering
abbrev divuwReferenceLowering := @Nightstream.Rv64IM.divuwReferenceLowering
abbrev remuwReferenceLowering := @Nightstream.Rv64IM.remuwReferenceLowering
abbrev divReferenceLowering := @Nightstream.Rv64IM.divReferenceLowering
abbrev remReferenceLowering := @Nightstream.Rv64IM.remReferenceLowering
abbrev divwReferenceLowering := @Nightstream.Rv64IM.divwReferenceLowering
abbrev remwReferenceLowering := @Nightstream.Rv64IM.remwReferenceLowering

abbrev mulEffectRowIndex := @Nightstream.Rv64IM.mulEffectRowIndex
abbrev mulhuEffectRowIndex := @Nightstream.Rv64IM.mulhuEffectRowIndex
abbrev mulwEffectRowIndex := @Nightstream.Rv64IM.mulwEffectRowIndex
abbrev mulhEffectRowIndex := @Nightstream.Rv64IM.mulhEffectRowIndex
abbrev mulhsuEffectRowIndex := @Nightstream.Rv64IM.mulhsuEffectRowIndex
abbrev divuEffectRowIndex := @Nightstream.Rv64IM.divuEffectRowIndex
abbrev remuEffectRowIndex := @Nightstream.Rv64IM.remuEffectRowIndex
abbrev divuwEffectRowIndex := @Nightstream.Rv64IM.divuwEffectRowIndex
abbrev remuwEffectRowIndex := @Nightstream.Rv64IM.remuwEffectRowIndex
abbrev divEffectRowIndex := @Nightstream.Rv64IM.divEffectRowIndex
abbrev remEffectRowIndex := @Nightstream.Rv64IM.remEffectRowIndex
abbrev divwEffectRowIndex := @Nightstream.Rv64IM.divwEffectRowIndex
abbrev remwEffectRowIndex := @Nightstream.Rv64IM.remwEffectRowIndex

abbrev mulhClosureSuffixRows := @Nightstream.Rv64IM.mulhClosureSuffixRows
abbrev mulhsuClosureSuffixRows := @Nightstream.Rv64IM.mulhsuClosureSuffixRows
abbrev divuClosureSuffixRows := @Nightstream.Rv64IM.divuClosureSuffixRows
abbrev remuClosureSuffixRows := @Nightstream.Rv64IM.remuClosureSuffixRows
abbrev divuwClosureSuffixRows := @Nightstream.Rv64IM.divuwClosureSuffixRows
abbrev remuwClosureSuffixRows := @Nightstream.Rv64IM.remuwClosureSuffixRows
abbrev divClosureSuffixRows := @Nightstream.Rv64IM.divClosureSuffixRows
abbrev remClosureSuffixRows := @Nightstream.Rv64IM.remClosureSuffixRows
abbrev divwClosureSuffixRows := @Nightstream.Rv64IM.divwClosureSuffixRows
abbrev remwClosureSuffixRows := @Nightstream.Rv64IM.remwClosureSuffixRows
abbrev mulhClosureSuffixScratchOnly := @Nightstream.Rv64IM.mulhClosureSuffixScratchOnly
abbrev mulhsuClosureSuffixScratchOnly := @Nightstream.Rv64IM.mulhsuClosureSuffixScratchOnly
abbrev divuClosureSuffixScratchOnly := @Nightstream.Rv64IM.divuClosureSuffixScratchOnly
abbrev remuClosureSuffixScratchOnly := @Nightstream.Rv64IM.remuClosureSuffixScratchOnly
abbrev divuwClosureSuffixScratchOnly := @Nightstream.Rv64IM.divuwClosureSuffixScratchOnly
abbrev remuwClosureSuffixScratchOnly := @Nightstream.Rv64IM.remuwClosureSuffixScratchOnly
abbrev divClosureSuffixScratchOnly := @Nightstream.Rv64IM.divClosureSuffixScratchOnly
abbrev remClosureSuffixScratchOnly := @Nightstream.Rv64IM.remClosureSuffixScratchOnly
abbrev divwClosureSuffixScratchOnly := @Nightstream.Rv64IM.divwClosureSuffixScratchOnly
abbrev remwClosureSuffixScratchOnly := @Nightstream.Rv64IM.remwClosureSuffixScratchOnly

abbrev mulConcreteCoreShape := @Nightstream.Rv64IM.mulConcreteCoreShape
abbrev mulhuConcreteCoreShape := @Nightstream.Rv64IM.mulhuConcreteCoreShape
abbrev mulwConcreteCoreShape := @Nightstream.Rv64IM.mulwConcreteCoreShape
abbrev mulhConcreteCoreShape := @Nightstream.Rv64IM.mulhConcreteCoreShape
abbrev mulhsuConcreteCoreShape := @Nightstream.Rv64IM.mulhsuConcreteCoreShape
abbrev divuConcreteCoreShape := @Nightstream.Rv64IM.divuConcreteCoreShape
abbrev remuConcreteCoreShape := @Nightstream.Rv64IM.remuConcreteCoreShape
abbrev divuwConcreteCoreShape := @Nightstream.Rv64IM.divuwConcreteCoreShape
abbrev remuwConcreteCoreShape := @Nightstream.Rv64IM.remuwConcreteCoreShape
abbrev divConcreteCoreShape := @Nightstream.Rv64IM.divConcreteCoreShape
abbrev remConcreteCoreShape := @Nightstream.Rv64IM.remConcreteCoreShape
abbrev divwConcreteCoreShape := @Nightstream.Rv64IM.divwConcreteCoreShape
abbrev remwConcreteCoreShape := @Nightstream.Rv64IM.remwConcreteCoreShape
abbrev singleRowConcreteShape := @Nightstream.Rv64IM.singleRowConcreteShape

abbrev normalizeSingleRowConcreteCore? := @Nightstream.Rv64IM.normalizeSingleRowConcreteCore?
abbrev normalizeMulConcreteCore? := @Nightstream.Rv64IM.normalizeMulConcreteCore?
abbrev normalizeMulhuConcreteCore? := @Nightstream.Rv64IM.normalizeMulhuConcreteCore?
abbrev normalizeMulwConcreteCore? := @Nightstream.Rv64IM.normalizeMulwConcreteCore?
abbrev normalizeMulhConcreteCore? := @Nightstream.Rv64IM.normalizeMulhConcreteCore?
abbrev normalizeMulhsuConcreteCore? := @Nightstream.Rv64IM.normalizeMulhsuConcreteCore?
abbrev normalizeDivuConcreteCore? := @Nightstream.Rv64IM.normalizeDivuConcreteCore?
abbrev normalizeRemuConcreteCore? := @Nightstream.Rv64IM.normalizeRemuConcreteCore?
abbrev normalizeDivuwConcreteCore? := @Nightstream.Rv64IM.normalizeDivuwConcreteCore?
abbrev normalizeRemuwConcreteCore? := @Nightstream.Rv64IM.normalizeRemuwConcreteCore?
abbrev normalizeDivConcreteCore? := @Nightstream.Rv64IM.normalizeDivConcreteCore?
abbrev normalizeRemConcreteCore? := @Nightstream.Rv64IM.normalizeRemConcreteCore?
abbrev normalizeDivwConcreteCore? := @Nightstream.Rv64IM.normalizeDivwConcreteCore?
abbrev normalizeRemwConcreteCore? := @Nightstream.Rv64IM.normalizeRemwConcreteCore?

abbrev SingleRowConcreteLoweringRefinesReference := @Nightstream.Rv64IM.SingleRowConcreteLoweringRefinesReference
abbrev MulConcreteLoweringRefinesReference := @Nightstream.Rv64IM.MulConcreteLoweringRefinesReference
abbrev MulhuConcreteLoweringRefinesReference := @Nightstream.Rv64IM.MulhuConcreteLoweringRefinesReference
abbrev MulwConcreteLoweringRefinesReference := @Nightstream.Rv64IM.MulwConcreteLoweringRefinesReference
abbrev MulhConcreteLoweringRefinesReference := @Nightstream.Rv64IM.MulhConcreteLoweringRefinesReference
abbrev MulhsuConcreteLoweringRefinesReference := @Nightstream.Rv64IM.MulhsuConcreteLoweringRefinesReference
abbrev DivuConcreteLoweringRefinesReference := @Nightstream.Rv64IM.DivuConcreteLoweringRefinesReference
abbrev RemuConcreteLoweringRefinesReference := @Nightstream.Rv64IM.RemuConcreteLoweringRefinesReference
abbrev DivuwConcreteLoweringRefinesReference := @Nightstream.Rv64IM.DivuwConcreteLoweringRefinesReference
abbrev RemuwConcreteLoweringRefinesReference := @Nightstream.Rv64IM.RemuwConcreteLoweringRefinesReference
abbrev DivConcreteLoweringRefinesReference := @Nightstream.Rv64IM.DivConcreteLoweringRefinesReference
abbrev RemConcreteLoweringRefinesReference := @Nightstream.Rv64IM.RemConcreteLoweringRefinesReference
abbrev DivwConcreteLoweringRefinesReference := @Nightstream.Rv64IM.DivwConcreteLoweringRefinesReference
abbrev RemwConcreteLoweringRefinesReference := @Nightstream.Rv64IM.RemwConcreteLoweringRefinesReference

abbrev normalizedReference_of_singleRowConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_singleRowConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_singleRowConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_singleRowConcreteLoweringRefinesReference
abbrev uniqueEffectRow_of_singleRowConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueEffectRow_of_singleRowConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_singleRowConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_singleRowConcreteLoweringRefinesReference
abbrev uniqueRealRow_of_singleRowConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueRealRow_of_singleRowConcreteLoweringRefinesReference

abbrev normalizedReference_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhConcreteLoweringRefinesReference
abbrev normalizedReference_of_mulConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_mulConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_mulConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_mulConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulConcreteLoweringRefinesReference
abbrev normalizedReference_of_mulhuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhuConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_mulhuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhuConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_mulhuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhuConcreteLoweringRefinesReference
abbrev normalizedReference_of_mulwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_mulwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_mulwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulwConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_mulwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_mulhConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_mulhConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_mulhConcreteLoweringRefinesReference
abbrev normalizedReference_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhsuConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhsuConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_mulhsuConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhsuConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhsuConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_mulhsuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_mulhsuConcreteLoweringRefinesReference
abbrev normalizedReference_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_divuConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_divuConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_divuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_divuConcreteLoweringRefinesReference
abbrev normalizedReference_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_remuConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_remuConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_remuConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_remuConcreteLoweringRefinesReference
abbrev normalizedReference_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_divuwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuwConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_divuwConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuwConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuwConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_divuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_divuwConcreteLoweringRefinesReference
abbrev normalizedReference_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_remuwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuwConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_remuwConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuwConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuwConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_remuwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_remuwConcreteLoweringRefinesReference
abbrev normalizedReference_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_divConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_divConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_divConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_divConcreteLoweringRefinesReference
abbrev normalizedReference_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_remConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_remConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_remConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_remConcreteLoweringRefinesReference
abbrev normalizedReference_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_divwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_divwConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_divwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_divwConcreteLoweringRefinesReference
abbrev normalizedReference_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.normalizedReference_of_remwConcreteLoweringRefinesReference
abbrev sequenceMetadataBound_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwConcreteLoweringRefinesReference
abbrev effectRowIndex_lt_length_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRowIndex_lt_length_of_remwConcreteLoweringRefinesReference
abbrev closureSuffixScratchOnly_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwConcreteLoweringRefinesReference
abbrev uniqueCommitRow_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwConcreteLoweringRefinesReference
abbrev effectRow_precedesCommitRow_of_remwConcreteLoweringRefinesReference :=
  @Nightstream.Rv64IM.effectRow_precedesCommitRow_of_remwConcreteLoweringRefinesReference

end LoweringRefinementInterface

end Nightstream.Rv64IM
