import Nightstream.Rv64IM.Execution.MultiplyOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace MultiplyOpcodeResultSemanticsInterface

abbrev mul_encodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mul_encodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mul_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mul_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulh_encodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulh_encodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulh_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulh_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulhu_encodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulhu_encodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulhu_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulhu_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulhsu_encodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulhsu_encodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulhsu_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulhsu_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulw_encodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulw_encodedAluResult_of_multiplyOpcodeResultSemantics
abbrev mulw_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics :=
  @Nightstream.Rv64IM.mulw_authenticatedEncodedAluResult_of_multiplyOpcodeResultSemantics

end MultiplyOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
