import Nightstream.Rv64IM.Execution.MultiplyLoweringSemantics

namespace Nightstream.Rv64IM

namespace MultiplyLoweringSemanticsInterface

abbrev fetchDecodeBound_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_multiplyLoweringSemantics
abbrev decodedRow_valid_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_multiplyLoweringSemantics
abbrev decodeHandoffBound_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_multiplyLoweringSemantics
abbrev x0WritePreserved_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_multiplyLoweringSemantics
abbrev nonFinalRdTarget_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_multiplyLoweringSemantics
abbrev frame_row_eq_at_index_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_multiplyLoweringSemantics
abbrev adjacentStates_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_multiplyLoweringSemantics
abbrev preparedStep_matches_row_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_multiplyLoweringSemantics
abbrev successor_matches_rows_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_multiplyLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_multiplyLoweringSemantics
abbrev sequenceCorrect_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_multiplyLoweringSemantics
abbrev sequenceDeterministic_of_multiplyLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_multiplyLoweringSemantics
abbrev normalizedReference_of_mulRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_mulRefinedMultiplyLowering
abbrev sequenceMetadataBound_of_mulRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulRefinedMultiplyLowering
abbrev uniqueCommitRow_of_mulRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulRefinedMultiplyLowering
abbrev normalizedReference_of_mulhuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhuRefinedMultiplyLowering
abbrev sequenceMetadataBound_of_mulhuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhuRefinedMultiplyLowering
abbrev uniqueCommitRow_of_mulhuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhuRefinedMultiplyLowering
abbrev normalizedReference_of_mulwRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_mulwRefinedMultiplyLowering
abbrev sequenceMetadataBound_of_mulwRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulwRefinedMultiplyLowering
abbrev uniqueCommitRow_of_mulwRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulwRefinedMultiplyLowering
abbrev normalizedReference_of_mulhRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyLowering
abbrev sequenceMetadataBound_of_mulhRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhRefinedMultiplyLowering
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyLowering
abbrev uniqueCommitRow_of_mulhRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhRefinedMultiplyLowering
abbrev effectRowPrecedesCommitRow_of_mulhRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhRefinedMultiplyLowering
abbrev normalizedReference_of_mulhsuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhsuRefinedMultiplyLowering
abbrev sequenceMetadataBound_of_mulhsuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhsuRefinedMultiplyLowering
abbrev closureSuffixScratchOnly_of_mulhsuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhsuRefinedMultiplyLowering
abbrev uniqueCommitRow_of_mulhsuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhsuRefinedMultiplyLowering
abbrev effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyLowering

end MultiplyLoweringSemanticsInterface

end Nightstream.Rv64IM
