import Nightstream.Rv64IM.Execution.MultiplySemantics

namespace Nightstream.Rv64IM

namespace MultiplySemanticsInterface

abbrev MultiplyExecutionFacts := @Nightstream.Rv64IM.MultiplyExecutionFacts
abbrev multiplyExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.multiplyExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_multiplyExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_multiplyExecutionFacts
abbrev adjacentStates_of_multiplyExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_multiplyExecutionFacts
abbrev preparedStep_matches_row_of_multiplyExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_multiplyExecutionFacts
abbrev successor_matches_rows_of_multiplyExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_multiplyExecutionFacts
abbrev row_has_opcodeClass_at_index_of_multiplyExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_multiplyExecutionFacts
noncomputable abbrev multiplyExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyExecutionFacts_of_stepComposition

end MultiplySemanticsInterface

end Nightstream.Rv64IM
