import Nightstream.Rv64IM.Execution.MultiplyEncodedArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyEncodedArithmeticInterface

abbrev mul_encodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mul_encodedArithmetic_of_multiplyEncodedArithmetic
abbrev mul_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mul_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulh_encodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulh_encodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulh_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulh_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulhu_encodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulhu_encodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulhu_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulhu_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulhsu_encodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulhsu_encodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulhsu_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulhsu_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulw_encodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulw_encodedArithmetic_of_multiplyEncodedArithmetic
abbrev mulw_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic :=
  @Nightstream.Rv64IM.mulw_authenticatedEncodedArithmetic_of_multiplyEncodedArithmetic

end MultiplyEncodedArithmeticInterface

end Nightstream.Rv64IM
