import Nightstream.Rv64IM.Execution.MultiplyWordArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyWordArithmeticInterface

abbrev mul_wordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mul_wordArithmetic_of_multiplyWordArithmetic
abbrev mul_authenticatedWordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mul_authenticatedWordArithmetic_of_multiplyWordArithmetic
abbrev mulh_wordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulh_wordArithmetic_of_multiplyWordArithmetic
abbrev mulh_authenticatedWordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulh_authenticatedWordArithmetic_of_multiplyWordArithmetic
abbrev mulhu_wordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulhu_wordArithmetic_of_multiplyWordArithmetic
abbrev mulhu_authenticatedWordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulhu_authenticatedWordArithmetic_of_multiplyWordArithmetic
abbrev mulhsu_wordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulhsu_wordArithmetic_of_multiplyWordArithmetic
abbrev mulhsu_authenticatedWordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulhsu_authenticatedWordArithmetic_of_multiplyWordArithmetic
abbrev mulw_wordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulw_wordArithmetic_of_multiplyWordArithmetic
abbrev mulw_authenticatedWordArithmetic_of_multiplyWordArithmetic :=
  @Nightstream.Rv64IM.mulw_authenticatedWordArithmetic_of_multiplyWordArithmetic

end MultiplyWordArithmeticInterface

end Nightstream.Rv64IM
