import Nightstream.Rv64IM.Execution.NarrowMemoryOpcodeSemantics

namespace NarrowMemoryOpcodeSemanticsInterface

abbrev NarrowMemoryWidths := @Nightstream.Rv64IM.NarrowMemoryWidths
abbrev NarrowMemoryOpcode := Nightstream.Rv64IM.NarrowMemoryOpcode
abbrev NarrowMemoryOpcodeBound := @Nightstream.Rv64IM.NarrowMemoryOpcodeBound
abbrev flags_of_narrowMemoryOpcodeBound := @Nightstream.Rv64IM.flags_of_narrowMemoryOpcodeBound
abbrev rowClassFlags_of_narrowMemoryOpcodeBound :=
  @Nightstream.Rv64IM.rowClassFlags_of_narrowMemoryOpcodeBound
abbrev flags_of_narrowMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.flags_of_narrowMemoryOpcodeSemantics
abbrev classFlags_of_narrowMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.classFlags_of_narrowMemoryOpcodeSemantics
abbrev x0WritePreserved_of_narrowMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_narrowMemoryOpcodeSemantics
abbrev sequenceCorrect_of_narrowMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_narrowMemoryOpcodeSemantics
abbrev sequenceDeterministic_of_narrowMemoryOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_narrowMemoryOpcodeSemantics

end NarrowMemoryOpcodeSemanticsInterface
