import Nightstream.Rv64IM.Execution.NarrowMemorySemantics

namespace Nightstream.Rv64IM

namespace NarrowMemorySemanticsInterface

abbrev NarrowMemoryExecutionFacts := @Nightstream.Rv64IM.NarrowMemoryExecutionFacts
abbrev narrowMemoryExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.narrowMemoryExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_narrowMemoryExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_narrowMemoryExecutionFacts
abbrev adjacentStates_of_narrowMemoryExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_narrowMemoryExecutionFacts
abbrev preparedStep_matches_row_of_narrowMemoryExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_narrowMemoryExecutionFacts
abbrev successor_matches_rows_of_narrowMemoryExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_narrowMemoryExecutionFacts
abbrev row_has_opcodeClass_at_index_of_narrowMemoryExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_narrowMemoryExecutionFacts
noncomputable abbrev narrowMemoryExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemoryExecutionFacts_of_stepComposition

end NarrowMemorySemanticsInterface

end Nightstream.Rv64IM
