import Nightstream.Rv64IM.Execution.NarrowMemoryLoweringSemantics

namespace Nightstream.Rv64IM

namespace NarrowMemoryLoweringSemanticsInterface

abbrev fetchDecodeBound_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_narrowMemoryLoweringSemantics
abbrev decodedRow_valid_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_narrowMemoryLoweringSemantics
abbrev decodeHandoffBound_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_narrowMemoryLoweringSemantics
abbrev x0WritePreserved_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_narrowMemoryLoweringSemantics
abbrev nonFinalRdTarget_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_narrowMemoryLoweringSemantics
abbrev frame_row_eq_at_index_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_narrowMemoryLoweringSemantics
abbrev adjacentStates_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_narrowMemoryLoweringSemantics
abbrev preparedStep_matches_row_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_narrowMemoryLoweringSemantics
abbrev successor_matches_rows_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_narrowMemoryLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_narrowMemoryLoweringSemantics
abbrev sequenceCorrect_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_narrowMemoryLoweringSemantics
abbrev sequenceDeterministic_of_narrowMemoryLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_narrowMemoryLoweringSemantics

end NarrowMemoryLoweringSemanticsInterface

end Nightstream.Rv64IM
