import Nightstream.Rv64IM.Execution.NativeAluWordArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluWordArithmeticInterface

abbrev add_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.add_wordArithmetic_of_nativeAluWordArithmetic
abbrev add_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.add_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev addi_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.addi_wordArithmetic_of_nativeAluWordArithmetic
abbrev addi_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.addi_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev sub_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sub_wordArithmetic_of_nativeAluWordArithmetic
abbrev sub_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sub_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev and_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.and_wordArithmetic_of_nativeAluWordArithmetic
abbrev and_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.and_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev andi_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.andi_wordArithmetic_of_nativeAluWordArithmetic
abbrev andi_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.andi_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev or_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.or_wordArithmetic_of_nativeAluWordArithmetic
abbrev or_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.or_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev ori_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.ori_wordArithmetic_of_nativeAluWordArithmetic
abbrev ori_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.ori_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev xor_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.xor_wordArithmetic_of_nativeAluWordArithmetic
abbrev xor_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.xor_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev xori_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.xori_wordArithmetic_of_nativeAluWordArithmetic
abbrev xori_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.xori_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev slt_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.slt_wordArithmetic_of_nativeAluWordArithmetic
abbrev slt_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.slt_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev slti_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.slti_wordArithmetic_of_nativeAluWordArithmetic
abbrev slti_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.slti_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev sltu_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sltu_wordArithmetic_of_nativeAluWordArithmetic
abbrev sltu_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sltu_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev sltiu_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sltiu_wordArithmetic_of_nativeAluWordArithmetic
abbrev sltiu_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.sltiu_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev lui_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.lui_wordArithmetic_of_nativeAluWordArithmetic
abbrev lui_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.lui_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev auipc_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.auipc_wordArithmetic_of_nativeAluWordArithmetic
abbrev auipc_authenticatedWordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.auipc_authenticatedWordArithmetic_of_nativeAluWordArithmetic
abbrev fence_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.fence_wordArithmetic_of_nativeAluWordArithmetic
abbrev ecall_wordArithmetic_of_nativeAluWordArithmetic :=
  @Nightstream.Rv64IM.ecall_wordArithmetic_of_nativeAluWordArithmetic

end NativeAluWordArithmeticInterface

end Nightstream.Rv64IM
