import Nightstream.Rv64IM.Execution.NativeAluOpcodeSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeSemanticsInterface

abbrev opcodeBound_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.opcodeBound_of_nativeAluOpcodeSemantics
abbrev flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.flags_of_nativeAluOpcodeSemantics
abbrev add_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.add_flags_of_nativeAluOpcodeSemantics
abbrev addi_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.addi_flags_of_nativeAluOpcodeSemantics
abbrev sub_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sub_flags_of_nativeAluOpcodeSemantics
abbrev and_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.and_flags_of_nativeAluOpcodeSemantics
abbrev andi_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.andi_flags_of_nativeAluOpcodeSemantics
abbrev or_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.or_flags_of_nativeAluOpcodeSemantics
abbrev ori_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.ori_flags_of_nativeAluOpcodeSemantics
abbrev xor_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.xor_flags_of_nativeAluOpcodeSemantics
abbrev xori_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.xori_flags_of_nativeAluOpcodeSemantics
abbrev slt_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.slt_flags_of_nativeAluOpcodeSemantics
abbrev slti_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.slti_flags_of_nativeAluOpcodeSemantics
abbrev sltu_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sltu_flags_of_nativeAluOpcodeSemantics
abbrev sltiu_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sltiu_flags_of_nativeAluOpcodeSemantics
abbrev lui_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.lui_flags_of_nativeAluOpcodeSemantics
abbrev auipc_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.auipc_flags_of_nativeAluOpcodeSemantics
abbrev fence_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.fence_flags_of_nativeAluOpcodeSemantics
abbrev ecall_flags_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.ecall_flags_of_nativeAluOpcodeSemantics
abbrev x0WritePreserved_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_nativeAluOpcodeSemantics
abbrev registerOperands_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.registerOperands_of_nativeAluOpcodeSemantics
abbrev nonX0WriteFacts_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_nativeAluOpcodeSemantics
abbrev activeWrite_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.activeWrite_of_nativeAluOpcodeSemantics
abbrev passiveWrite_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.passiveWrite_of_nativeAluOpcodeSemantics
abbrev authenticatedWriteback_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeNativeAluOpcodeSemantics
abbrev routedWriteback_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.routedWriteback_of_activeNativeAluOpcodeSemantics
abbrev authenticatedRoutedWriteback_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeNativeAluOpcodeSemantics
abbrev encodedAluOut_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeNativeAluOpcodeSemantics
abbrev encodedAluResult_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeNativeAluOpcodeSemantics
abbrev authenticatedEncodedAluOut_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeNativeAluOpcodeSemantics
abbrev authenticatedEncodedAluResult_of_activeNativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeNativeAluOpcodeSemantics
abbrev add_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.add_writeback_of_nativeAluOpcodeSemantics
abbrev addi_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.addi_writeback_of_nativeAluOpcodeSemantics
abbrev sub_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sub_writeback_of_nativeAluOpcodeSemantics
abbrev and_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.and_writeback_of_nativeAluOpcodeSemantics
abbrev andi_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.andi_writeback_of_nativeAluOpcodeSemantics
abbrev or_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.or_writeback_of_nativeAluOpcodeSemantics
abbrev ori_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.ori_writeback_of_nativeAluOpcodeSemantics
abbrev xor_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.xor_writeback_of_nativeAluOpcodeSemantics
abbrev xori_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.xori_writeback_of_nativeAluOpcodeSemantics
abbrev slt_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.slt_writeback_of_nativeAluOpcodeSemantics
abbrev slti_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.slti_writeback_of_nativeAluOpcodeSemantics
abbrev sltu_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sltu_writeback_of_nativeAluOpcodeSemantics
abbrev sltiu_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sltiu_writeback_of_nativeAluOpcodeSemantics
abbrev lui_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.lui_writeback_of_nativeAluOpcodeSemantics
abbrev auipc_writeback_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.auipc_writeback_of_nativeAluOpcodeSemantics
abbrev fence_passiveWrite_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.fence_passiveWrite_of_nativeAluOpcodeSemantics
abbrev ecall_passiveWrite_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.ecall_passiveWrite_of_nativeAluOpcodeSemantics
abbrev ecall_terminates_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.ecall_terminates_of_nativeAluOpcodeSemantics
abbrev sequenceCorrect_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_nativeAluOpcodeSemantics
abbrev sequenceDeterministic_of_nativeAluOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_nativeAluOpcodeSemantics

end NativeAluOpcodeSemanticsInterface

end Nightstream.Rv64IM
