import Nightstream.Rv64IM.Execution.NativeAluEncodedArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluEncodedArithmeticInterface

abbrev add_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.add_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev add_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.add_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev addi_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.addi_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev addi_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.addi_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sub_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sub_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sub_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sub_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev and_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.and_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev and_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.and_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev andi_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.andi_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev andi_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.andi_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev or_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.or_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev or_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.or_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev ori_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.ori_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev ori_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.ori_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev xor_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.xor_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev xor_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.xor_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev xori_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.xori_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev xori_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.xori_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev slt_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.slt_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev slt_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.slt_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev slti_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.slti_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev slti_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.slti_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sltu_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sltu_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sltu_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sltu_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sltiu_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sltiu_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev sltiu_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.sltiu_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev lui_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.lui_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev lui_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.lui_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev auipc_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.auipc_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev auipc_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.auipc_authenticatedEncodedArithmetic_of_nativeAluEncodedArithmetic
abbrev fence_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.fence_encodedArithmetic_of_nativeAluEncodedArithmetic
abbrev ecall_encodedArithmetic_of_nativeAluEncodedArithmetic :=
  @Nightstream.Rv64IM.ecall_encodedArithmetic_of_nativeAluEncodedArithmetic

end NativeAluEncodedArithmeticInterface

end Nightstream.Rv64IM
