import Nightstream.Rv64IM.Execution.NativeAluSemantics

namespace Nightstream.Rv64IM

namespace NativeAluSemanticsInterface

abbrev NativeAluExecutionFacts := @Nightstream.Rv64IM.NativeAluExecutionFacts
abbrev nativeAluExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.nativeAluExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_nativeAluExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_nativeAluExecutionFacts
abbrev adjacentStates_of_nativeAluExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_nativeAluExecutionFacts
abbrev preparedStep_matches_row_of_nativeAluExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_nativeAluExecutionFacts
abbrev successor_matches_rows_of_nativeAluExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_nativeAluExecutionFacts
abbrev row_has_opcodeClass_at_index_of_nativeAluExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_nativeAluExecutionFacts
noncomputable abbrev nativeAluExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluExecutionFacts_of_stepComposition

end NativeAluSemanticsInterface

end Nightstream.Rv64IM
