import Nightstream.Rv64IM.Execution.NativeAluLoweringSemantics

namespace Nightstream.Rv64IM

namespace NativeAluLoweringSemanticsInterface

abbrev fetchDecodeBound_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_nativeAluLoweringSemantics
abbrev decodedRow_valid_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_nativeAluLoweringSemantics
abbrev decodeHandoffBound_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_nativeAluLoweringSemantics
abbrev x0WritePreserved_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_nativeAluLoweringSemantics
abbrev nonFinalRdTarget_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_nativeAluLoweringSemantics
abbrev frame_row_eq_at_index_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_nativeAluLoweringSemantics
abbrev adjacentStates_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_nativeAluLoweringSemantics
abbrev preparedStep_matches_row_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_nativeAluLoweringSemantics
abbrev successor_matches_rows_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_nativeAluLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_nativeAluLoweringSemantics
abbrev sequenceCorrect_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_nativeAluLoweringSemantics
abbrev sequenceDeterministic_of_nativeAluLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_nativeAluLoweringSemantics

end NativeAluLoweringSemanticsInterface

end Nightstream.Rv64IM
