import Nightstream.Rv64IM.Execution.NativeAluOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeResultSemanticsInterface

abbrev add_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.add_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev add_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.add_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev addi_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.addi_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev addi_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.addi_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sub_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sub_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sub_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sub_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev and_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.and_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev and_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.and_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev andi_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.andi_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev andi_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.andi_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev or_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.or_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev or_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.or_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev ori_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.ori_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev ori_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.ori_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev xor_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.xor_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev xor_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.xor_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev xori_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.xori_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev xori_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.xori_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev slt_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.slt_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev slt_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.slt_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev slti_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.slti_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev slti_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.slti_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sltu_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sltu_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sltu_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sltu_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sltiu_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sltiu_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev sltiu_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.sltiu_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev lui_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.lui_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev lui_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.lui_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev auipc_encodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.auipc_encodedAluResult_of_nativeAluOpcodeResultSemantics
abbrev auipc_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics :=
  @Nightstream.Rv64IM.auipc_authenticatedEncodedAluResult_of_nativeAluOpcodeResultSemantics

end NativeAluOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
