import Nightstream.Rv64IM.Execution.OpcodeClassExtractors

namespace Nightstream.Rv64IM

namespace OpcodeClassExtractorsInterface

abbrev CanonicalOpcodeProofs := @Nightstream.Rv64IM.CanonicalOpcodeProofs
noncomputable abbrev canonicalOpcodeProofs_of_stepComposition :=
  @Nightstream.Rv64IM.canonicalOpcodeProofs_of_stepComposition
abbrev nativeAlu_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.nativeAlu_mem_of_canonicalOpcodeProofs
abbrev wordShift_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.wordShift_mem_of_canonicalOpcodeProofs
abbrev controlFlow_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.controlFlow_mem_of_canonicalOpcodeProofs
abbrev narrowMemory_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.narrowMemory_mem_of_canonicalOpcodeProofs
abbrev multiply_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.multiply_mem_of_canonicalOpcodeProofs
abbrev unsignedDivRem_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.unsignedDivRem_mem_of_canonicalOpcodeProofs
abbrev signedDivRem_mem_of_canonicalOpcodeProofs :=
  @Nightstream.Rv64IM.signedDivRem_mem_of_canonicalOpcodeProofs

end OpcodeClassExtractorsInterface

end Nightstream.Rv64IM
