import Nightstream.Rv64IM.Execution.SignedDivRemOpcodeSemantics

namespace Nightstream.Rv64IM

namespace SignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_signedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.opcodeBound_of_signedDivRemOpcodeSemantics
abbrev div_flags_of_signedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.div_flags_of_signedDivRemOpcodeSemantics
abbrev rem_flags_of_signedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.rem_flags_of_signedDivRemOpcodeSemantics
abbrev divw_flags_of_signedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.divw_flags_of_signedDivRemOpcodeSemantics
abbrev remw_flags_of_signedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.remw_flags_of_signedDivRemOpcodeSemantics
abbrev spec_of_signedDivOpcodeSemantics :=
  @Nightstream.Rv64IM.spec_of_signedDivOpcodeSemantics
abbrev spec_of_signedRemOpcodeSemantics :=
  @Nightstream.Rv64IM.spec_of_signedRemOpcodeSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics
abbrev normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics
abbrev normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics
abbrev normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics

end SignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
