import Nightstream.Rv64IM.Execution.SignedDivRemLoweringSemantics

namespace Nightstream.Rv64IM

namespace SignedDivRemLoweringSemanticsInterface

abbrev fetchDecodeBound_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_signedDivRemLoweringSemantics
abbrev decodedRow_valid_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_signedDivRemLoweringSemantics
abbrev decodeHandoffBound_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_signedDivRemLoweringSemantics
abbrev x0WritePreserved_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_signedDivRemLoweringSemantics
abbrev nonFinalRdTarget_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_signedDivRemLoweringSemantics
abbrev frame_row_eq_at_index_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_signedDivRemLoweringSemantics
abbrev adjacentStates_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_signedDivRemLoweringSemantics
abbrev preparedStep_matches_row_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_signedDivRemLoweringSemantics
abbrev successor_matches_rows_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_signedDivRemLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_signedDivRemLoweringSemantics
abbrev changeDivisorCorrect_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.changeDivisorCorrect_of_signedDivRemLoweringSemantics
abbrev remainderFromDividendSign_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.remainderFromDividendSign_of_signedDivRemLoweringSemantics
abbrev signedDivRemSpec_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.signedDivRemSpec_of_signedDivRemLoweringSemantics
abbrev sequenceCorrect_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_signedDivRemLoweringSemantics
abbrev sequenceDeterministic_of_signedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_signedDivRemLoweringSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemLowering
abbrev sequenceMetadataBound_of_divRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divRefinedSignedDivRemLowering
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemLowering
abbrev uniqueCommitRow_of_divRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divRefinedSignedDivRemLowering
abbrev effectRowPrecedesCommitRow_of_divRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divRefinedSignedDivRemLowering
abbrev normalizedReference_of_remRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_remRefinedSignedDivRemLowering
abbrev sequenceMetadataBound_of_remRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remRefinedSignedDivRemLowering
abbrev closureSuffixScratchOnly_of_remRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remRefinedSignedDivRemLowering
abbrev uniqueCommitRow_of_remRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remRefinedSignedDivRemLowering
abbrev effectRowPrecedesCommitRow_of_remRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remRefinedSignedDivRemLowering
abbrev normalizedReference_of_divwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_divwRefinedSignedDivRemLowering
abbrev sequenceMetadataBound_of_divwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwRefinedSignedDivRemLowering
abbrev closureSuffixScratchOnly_of_divwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwRefinedSignedDivRemLowering
abbrev uniqueCommitRow_of_divwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwRefinedSignedDivRemLowering
abbrev effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemLowering
abbrev normalizedReference_of_remwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.normalizedReference_of_remwRefinedSignedDivRemLowering
abbrev sequenceMetadataBound_of_remwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwRefinedSignedDivRemLowering
abbrev closureSuffixScratchOnly_of_remwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwRefinedSignedDivRemLowering
abbrev uniqueCommitRow_of_remwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwRefinedSignedDivRemLowering
abbrev effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemLowering :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemLowering

end SignedDivRemLoweringSemanticsInterface

end Nightstream.Rv64IM
