import Nightstream.Rv64IM.Execution.SignedDivRemSemantics

namespace Nightstream.Rv64IM

namespace SignedDivRemSemanticsInterface

abbrev SignedDivRemExecutionFacts := @Nightstream.Rv64IM.SignedDivRemExecutionFacts
abbrev signedDivRemExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.signedDivRemExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_signedDivRemExecutionFacts
abbrev adjacentStates_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_signedDivRemExecutionFacts
abbrev preparedStep_matches_row_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_signedDivRemExecutionFacts
abbrev successor_matches_rows_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_signedDivRemExecutionFacts
abbrev row_has_opcodeClass_at_index_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_signedDivRemExecutionFacts
abbrev changeDivisorCorrect_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.changeDivisorCorrect_of_signedDivRemExecutionFacts
abbrev remainderFromDividendSign_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.remainderFromDividendSign_of_signedDivRemExecutionFacts
abbrev signedDivRemSpec_of_signedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.signedDivRemSpec_of_signedDivRemExecutionFacts
noncomputable abbrev signedDivRemExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.signedDivRemExecutionFacts_of_stepComposition

end SignedDivRemSemanticsInterface

end Nightstream.Rv64IM
