import Nightstream.Rv64IM.Execution.StepComposition

namespace Nightstream.Rv64IM

namespace StepCompositionInterface

abbrev opcodeClassOrder := Nightstream.Rv64IM.opcodeClassOrder
abbrev NativeAluOpcode := @Nightstream.Rv64IM.NativeAluOpcode
abbrev NativeAluOpcode.writesArchitecturalRd := @Nightstream.Rv64IM.NativeAluOpcode.writesArchitecturalRd
abbrev NativeAluAluOps := @Nightstream.Rv64IM.NativeAluAluOps
abbrev NativeAluEncodedOps := @Nightstream.Rv64IM.NativeAluEncodedOps
abbrev NativeAluWordOps := @Nightstream.Rv64IM.NativeAluWordOps
abbrev NativeAluEncodedResult := @Nightstream.Rv64IM.NativeAluEncodedResult
abbrev NativeAluWordResult := @Nightstream.Rv64IM.NativeAluWordResult
abbrev NativeAluOpcodeBound := @Nightstream.Rv64IM.NativeAluOpcodeBound
abbrev NativeAluOpcodeWriteContract := @Nightstream.Rv64IM.NativeAluOpcodeWriteContract
abbrev NativeAluEncodedResultBound := @Nightstream.Rv64IM.NativeAluEncodedResultBound
abbrev NativeAluWordCompatibilityBound := @Nightstream.Rv64IM.NativeAluWordCompatibilityBound
abbrev classFlags_of_nativeAluOpcodeBound := @Nightstream.Rv64IM.classFlags_of_nativeAluOpcodeBound
abbrev usesRs2_of_nativeAluOpcodeBound := @Nightstream.Rv64IM.usesRs2_of_nativeAluOpcodeBound
abbrev writesMemToRd_of_nativeAluOpcodeBound := @Nightstream.Rv64IM.writesMemToRd_of_nativeAluOpcodeBound
abbrev aluOp_of_nativeAluOpcodeBound := @Nightstream.Rv64IM.aluOp_of_nativeAluOpcodeBound
abbrev x0WriteFacts_of_nativeAluOpcodeWriteContract := @Nightstream.Rv64IM.x0WriteFacts_of_nativeAluOpcodeWriteContract
abbrev nonX0WriteFacts_of_nativeAluOpcodeWriteContract := @Nightstream.Rv64IM.nonX0WriteFacts_of_nativeAluOpcodeWriteContract
abbrev activeWrite_of_nativeAluOpcodeWriteContract := @Nightstream.Rv64IM.activeWrite_of_nativeAluOpcodeWriteContract
abbrev passiveWrite_of_nativeAluOpcodeWriteContract := @Nightstream.Rv64IM.passiveWrite_of_nativeAluOpcodeWriteContract
abbrev AlignedMemoryOpcode := @Nightstream.Rv64IM.AlignedMemoryOpcode
abbrev AlignedMemoryOpcode.writesArchitecturalRd :=
  @Nightstream.Rv64IM.AlignedMemoryOpcode.writesArchitecturalRd
abbrev AlignedMemoryOpcodeBound := @Nightstream.Rv64IM.AlignedMemoryOpcodeBound
abbrev AlignedMemoryOpcodeWriteContract := @Nightstream.Rv64IM.AlignedMemoryOpcodeWriteContract
abbrev rowClassFlags_of_alignedMemoryOpcodeBound :=
  @Nightstream.Rv64IM.rowClassFlags_of_alignedMemoryOpcodeBound
abbrev flags_of_alignedMemoryOpcodeBound := @Nightstream.Rv64IM.flags_of_alignedMemoryOpcodeBound
abbrev x0WriteFacts_of_alignedMemoryOpcodeWriteContract :=
  @Nightstream.Rv64IM.x0WriteFacts_of_alignedMemoryOpcodeWriteContract
abbrev nonX0WriteFacts_of_alignedMemoryOpcodeWriteContract :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_alignedMemoryOpcodeWriteContract
abbrev activeMemWrite_of_alignedMemoryOpcodeWriteContract :=
  @Nightstream.Rv64IM.activeMemWrite_of_alignedMemoryOpcodeWriteContract
abbrev passiveWrite_of_alignedMemoryOpcodeWriteContract :=
  @Nightstream.Rv64IM.passiveWrite_of_alignedMemoryOpcodeWriteContract
abbrev WordShiftOpcode := @Nightstream.Rv64IM.WordShiftOpcode
abbrev WordShiftAluOps := @Nightstream.Rv64IM.WordShiftAluOps
abbrev WordShiftOpcodeBound := @Nightstream.Rv64IM.WordShiftOpcodeBound
abbrev isWOp_of_wordShiftOpcodeBound := @Nightstream.Rv64IM.isWOp_of_wordShiftOpcodeBound
abbrev usesRs2_of_wordShiftOpcodeBound := @Nightstream.Rv64IM.usesRs2_of_wordShiftOpcodeBound
abbrev aluOp_of_wordShiftOpcodeBound := @Nightstream.Rv64IM.aluOp_of_wordShiftOpcodeBound
abbrev MultiplyOpcode := @Nightstream.Rv64IM.MultiplyOpcode
abbrev MultiplyOpcode.writesArchitecturalRd := @Nightstream.Rv64IM.MultiplyOpcode.writesArchitecturalRd
abbrev MultiplyAluOps := @Nightstream.Rv64IM.MultiplyAluOps
abbrev MultiplyEncodedOps := @Nightstream.Rv64IM.MultiplyEncodedOps
abbrev MultiplyWordOps := @Nightstream.Rv64IM.MultiplyWordOps
abbrev MultiplyEncodedResult := @Nightstream.Rv64IM.MultiplyEncodedResult
abbrev MultiplyWordResult := @Nightstream.Rv64IM.MultiplyWordResult
abbrev MultiplyOpcodeBound := @Nightstream.Rv64IM.MultiplyOpcodeBound
abbrev MultiplyOpcodeWriteContract := @Nightstream.Rv64IM.MultiplyOpcodeWriteContract
abbrev MultiplyEncodedResultBound := @Nightstream.Rv64IM.MultiplyEncodedResultBound
abbrev MultiplyWordCompatibilityBound := @Nightstream.Rv64IM.MultiplyWordCompatibilityBound
abbrev classFlags_of_multiplyOpcodeBound := @Nightstream.Rv64IM.classFlags_of_multiplyOpcodeBound
abbrev usesRs2_of_multiplyOpcodeBound := @Nightstream.Rv64IM.usesRs2_of_multiplyOpcodeBound
abbrev writeFlags_of_multiplyOpcodeBound := @Nightstream.Rv64IM.writeFlags_of_multiplyOpcodeBound
abbrev isWOp_of_multiplyOpcodeBound := @Nightstream.Rv64IM.isWOp_of_multiplyOpcodeBound
abbrev aluOp_of_multiplyOpcodeBound := @Nightstream.Rv64IM.aluOp_of_multiplyOpcodeBound
abbrev x0WriteFacts_of_multiplyOpcodeWriteContract := @Nightstream.Rv64IM.x0WriteFacts_of_multiplyOpcodeWriteContract
abbrev activeWrite_of_multiplyOpcodeWriteContract := @Nightstream.Rv64IM.activeWrite_of_multiplyOpcodeWriteContract
abbrev OpcodeClassProof := @Nightstream.Rv64IM.OpcodeClassProof
abbrev OpcodeProofsOrdered := @Nightstream.Rv64IM.OpcodeProofsOrdered
abbrev StepCompositionProofPackage := @Nightstream.Rv64IM.StepCompositionProofPackage
abbrev RegisterWriteActivationBound := @Nightstream.Rv64IM.RegisterWriteActivationBound
abbrev WritebackRoutingBound := @Nightstream.Rv64IM.WritebackRoutingBound
abbrev RamRoleFlagsBound := @Nightstream.Rv64IM.RamRoleFlagsBound
abbrev AluWritebackRepresentationBound := @Nightstream.Rv64IM.AluWritebackRepresentationBound
abbrev NarrowMemoryExtractResultBound := @Nightstream.Rv64IM.NarrowMemoryExtractResultBound
abbrev NarrowMemoryBlendResultBound := @Nightstream.Rv64IM.NarrowMemoryBlendResultBound
abbrev committedSequenceDeterministic_of_stepComposition :=
  @Nightstream.Rv64IM.committedSequenceDeterministic_of_stepComposition
abbrev adviceSequenceDeterministic_of_stepComposition :=
  @Nightstream.Rv64IM.adviceSequenceDeterministic_of_stepComposition
abbrev nativeAluSequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluSequenceProof_of_stepComposition
abbrev nativeAluOpcodeBound_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluOpcodeBound_of_stepComposition
abbrev nativeAluWriteContract_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluWriteContract_of_stepComposition
abbrev nativeAluEncodedResultBound_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluEncodedResultBound_of_stepComposition
abbrev wordShiftSequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.wordShiftSequenceProof_of_stepComposition
abbrev controlFlowSequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.controlFlowSequenceProof_of_stepComposition
abbrev narrowMemorySequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemorySequenceProof_of_stepComposition
abbrev narrowMemoryExtractResultBound_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemoryExtractResultBound_of_stepComposition
abbrev narrowMemoryBlendResultBound_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemoryBlendResultBound_of_stepComposition
abbrev alignedMemoryOpcodeBound_of_stepComposition :=
  @Nightstream.Rv64IM.alignedMemoryOpcodeBound_of_stepComposition
abbrev alignedMemoryWriteContract_of_stepComposition :=
  @Nightstream.Rv64IM.alignedMemoryWriteContract_of_stepComposition
abbrev multiplySequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.multiplySequenceProof_of_stepComposition
abbrev multiplyOpcodeBound_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyOpcodeBound_of_stepComposition
abbrev multiplyWriteContract_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyWriteContract_of_stepComposition
abbrev multiplyEncodedResultBound_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyEncodedResultBound_of_stepComposition
abbrev unsignedDivRemSequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemSequenceProof_of_stepComposition
abbrev signedDivRemSequenceProof_of_stepComposition :=
  @Nightstream.Rv64IM.signedDivRemSequenceProof_of_stepComposition
abbrev executionCorrect_of_opcodeClassProof :=
  @Nightstream.Rv64IM.executionCorrect_of_opcodeClassProof
abbrev row_opcodeClass_of_opcodeClassProof :=
  @Nightstream.Rv64IM.row_opcodeClass_of_opcodeClassProof
abbrev stage1LinkageBound_of_stepComposition :=
  @Nightstream.Rv64IM.stage1LinkageBound_of_stepComposition
abbrev decodedRow_eq_executionRow_of_stepComposition :=
  @Nightstream.Rv64IM.decodedRow_eq_executionRow_of_stepComposition
abbrev twistConcreteBinding_of_stepComposition :=
  @Nightstream.Rv64IM.twistConcreteBinding_of_stepComposition
abbrev registerWriteActivation_of_stepComposition :=
  @Nightstream.Rv64IM.registerWriteActivation_of_stepComposition
abbrev writebackRoutingBound_of_stepComposition :=
  @Nightstream.Rv64IM.writebackRoutingBound_of_stepComposition
abbrev aluWritebackRepresentationBound_of_stepComposition :=
  @Nightstream.Rv64IM.aluWritebackRepresentationBound_of_stepComposition
abbrev wordEncodingRoundTripWord_of_stepComposition :=
  @Nightstream.Rv64IM.wordEncodingRoundTripWord_of_stepComposition
abbrev wordEncodingRoundTripPair_of_stepComposition :=
  @Nightstream.Rv64IM.wordEncodingRoundTripPair_of_stepComposition
abbrev wordToLimbPair_injective_of_stepComposition :=
  @Nightstream.Rv64IM.wordToLimbPair_injective_of_stepComposition
abbrev nativeAluWordCompatibility_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluWordCompatibility_of_stepComposition
abbrev multiplyWordCompatibility_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyWordCompatibility_of_stepComposition
abbrev encodedAluOut_of_stepComposition :=
  @Nightstream.Rv64IM.encodedAluOut_of_stepComposition
abbrev encodedAluResult_of_stepComposition :=
  @Nightstream.Rv64IM.encodedAluResult_of_stepComposition
abbrev registerWritesRd_of_stepComposition :=
  @Nightstream.Rv64IM.registerWritesRd_of_stepComposition
abbrev registerRdNext_of_activeAluWrite :=
  @Nightstream.Rv64IM.registerRdNext_of_activeAluWrite
abbrev registerRdNext_of_activeMemWrite :=
  @Nightstream.Rv64IM.registerRdNext_of_activeMemWrite
abbrev registerRdNext_zero_of_preservesRd :=
  @Nightstream.Rv64IM.registerRdNext_zero_of_preservesRd
abbrev stage2LinkageBound_of_stepComposition :=
  @Nightstream.Rv64IM.stage2LinkageBound_of_stepComposition
abbrev registerLinkageBound_of_stepComposition :=
  @Nightstream.Rv64IM.registerLinkageBound_of_stepComposition
abbrev ramLinkageBound_of_stepComposition :=
  @Nightstream.Rv64IM.ramLinkageBound_of_stepComposition
abbrev ramRoleFlags_of_stepComposition :=
  @Nightstream.Rv64IM.ramRoleFlags_of_stepComposition
abbrev ramLaneIsLoad_eq_decodedRow_of_stepComposition :=
  @Nightstream.Rv64IM.ramLaneIsLoad_eq_decodedRow_of_stepComposition
abbrev ramLaneIsStore_eq_decodedRow_of_stepComposition :=
  @Nightstream.Rv64IM.ramLaneIsStore_eq_decodedRow_of_stepComposition
abbrev registerWriteValue_of_stepComposition :=
  @Nightstream.Rv64IM.registerWriteValue_of_stepComposition
abbrev authenticatedAluWriteValue_of_stepComposition :=
  @Nightstream.Rv64IM.authenticatedAluWriteValue_of_stepComposition
abbrev authenticatedMemWriteValue_of_stepComposition :=
  @Nightstream.Rv64IM.authenticatedMemWriteValue_of_stepComposition
abbrev registerReadValues_of_stepComposition :=
  @Nightstream.Rv64IM.registerReadValues_of_stepComposition
abbrev ramLoadMemVal_of_stepComposition :=
  @Nightstream.Rv64IM.ramLoadMemVal_of_stepComposition
abbrev ramStorePayload_of_stepComposition :=
  @Nightstream.Rv64IM.ramStorePayload_of_stepComposition
abbrev ramInactiveMemValZero_of_stepComposition :=
  @Nightstream.Rv64IM.ramInactiveMemValZero_of_stepComposition
abbrev takenTargetAlignmentBound_of_stepComposition :=
  @Nightstream.Rv64IM.takenTargetAlignmentBound_of_stepComposition
abbrev mulUNoOverflowBound_of_stepComposition :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_stepComposition
abbrev opcodeProofs_cover_exact_order :=
  @Nightstream.Rv64IM.opcodeProofs_cover_exact_order
abbrev opcodeProofs_canonicalShape_of_stepComposition :=
  @Nightstream.Rv64IM.opcodeProofs_canonicalShape_of_stepComposition
abbrev nativeAluOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.nativeAluOpcodeClassProof_of_stepComposition
abbrev wordShiftOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.wordShiftOpcodeClassProof_of_stepComposition
abbrev controlFlowOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.controlFlowOpcodeClassProof_of_stepComposition
abbrev narrowMemoryOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.narrowMemoryOpcodeClassProof_of_stepComposition
abbrev multiplyOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.multiplyOpcodeClassProof_of_stepComposition
abbrev unsignedDivRemOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemOpcodeClassProof_of_stepComposition
abbrev signedDivRemOpcodeClassProof_of_stepComposition :=
  @Nightstream.Rv64IM.signedDivRemOpcodeClassProof_of_stepComposition
abbrev temporaryRegisterHygiene_of_stepComposition :=
  @Nightstream.Rv64IM.temporaryRegisterHygiene_of_stepComposition
abbrev mulUNoOverflow_of_stepComposition :=
  @Nightstream.Rv64IM.mulUNoOverflow_of_stepComposition
abbrev unsignedDivRemSpec_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemSpec_of_stepComposition
abbrev unsignedDivRemDeterministic_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemDeterministic_of_stepComposition
abbrev changeDivisorCorrect_of_stepComposition :=
  @Nightstream.Rv64IM.changeDivisorCorrect_of_stepComposition
abbrev remainderFromDividendSign_of_stepComposition :=
  @Nightstream.Rv64IM.remainderFromDividendSign_of_stepComposition
abbrev signedDivRemSpec_of_stepComposition :=
  @Nightstream.Rv64IM.signedDivRemSpec_of_stepComposition

end StepCompositionInterface

end Nightstream.Rv64IM
