import Nightstream.Rv64IM.Execution.UnsignedDivRemSemantics

namespace Nightstream.Rv64IM

namespace UnsignedDivRemSemanticsInterface

abbrev UnsignedDivRemExecutionFacts := @Nightstream.Rv64IM.UnsignedDivRemExecutionFacts
abbrev unsignedDivRemExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.unsignedDivRemExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_unsignedDivRemExecutionFacts
abbrev adjacentStates_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_unsignedDivRemExecutionFacts
abbrev preparedStep_matches_row_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_unsignedDivRemExecutionFacts
abbrev successor_matches_rows_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_unsignedDivRemExecutionFacts
abbrev row_has_opcodeClass_at_index_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_unsignedDivRemExecutionFacts
abbrev mulUNoOverflowBound_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_unsignedDivRemExecutionFacts
abbrev mulUNoOverflow_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.mulUNoOverflow_of_unsignedDivRemExecutionFacts
abbrev unsignedDivRemSpec_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.unsignedDivRemSpec_of_unsignedDivRemExecutionFacts
abbrev unsignedDivRemDeterministic_of_unsignedDivRemExecutionFacts :=
  @Nightstream.Rv64IM.unsignedDivRemDeterministic_of_unsignedDivRemExecutionFacts
noncomputable abbrev unsignedDivRemExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.unsignedDivRemExecutionFacts_of_stepComposition

end UnsignedDivRemSemanticsInterface

end Nightstream.Rv64IM
