import Nightstream.Rv64IM.Execution.UnsignedDivRemOpcodeSemantics

namespace Nightstream.Rv64IM

namespace UnsignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.opcodeBound_of_unsignedDivRemOpcodeSemantics
abbrev divu_flags_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.divu_flags_of_unsignedDivRemOpcodeSemantics
abbrev remu_flags_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.remu_flags_of_unsignedDivRemOpcodeSemantics
abbrev divuw_flags_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.divuw_flags_of_unsignedDivRemOpcodeSemantics
abbrev remuw_flags_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.remuw_flags_of_unsignedDivRemOpcodeSemantics
abbrev spec_of_unsignedDivuOpcodeSemantics :=
  @Nightstream.Rv64IM.spec_of_unsignedDivuOpcodeSemantics
abbrev spec_of_unsignedRemuOpcodeSemantics :=
  @Nightstream.Rv64IM.spec_of_unsignedRemuOpcodeSemantics
abbrev deterministic_of_unsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.deterministic_of_unsignedDivRemOpcodeSemantics
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics
abbrev normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics
abbrev normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics
abbrev normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics
abbrev sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics
abbrev closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics
abbrev uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics
abbrev effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics

end UnsignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
