import Nightstream.Rv64IM.Execution.UnsignedDivRemLoweringSemantics

namespace Nightstream.Rv64IM

namespace UnsignedDivRemLoweringSemanticsInterface

abbrev fetchDecodeBound_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_unsignedDivRemLoweringSemantics
abbrev decodedRow_valid_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_unsignedDivRemLoweringSemantics
abbrev decodeHandoffBound_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_unsignedDivRemLoweringSemantics
abbrev x0WritePreserved_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_unsignedDivRemLoweringSemantics
abbrev nonFinalRdTarget_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_unsignedDivRemLoweringSemantics
abbrev frame_row_eq_at_index_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_unsignedDivRemLoweringSemantics
abbrev adjacentStates_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_unsignedDivRemLoweringSemantics
abbrev preparedStep_matches_row_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_unsignedDivRemLoweringSemantics
abbrev successor_matches_rows_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_unsignedDivRemLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_unsignedDivRemLoweringSemantics
abbrev mulUNoOverflowBound_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_unsignedDivRemLoweringSemantics
abbrev mulUNoOverflow_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.mulUNoOverflow_of_unsignedDivRemLoweringSemantics
abbrev unsignedDivRemSpec_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.unsignedDivRemSpec_of_unsignedDivRemLoweringSemantics
abbrev sequenceCorrect_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_unsignedDivRemLoweringSemantics
abbrev sequenceDeterministic_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_unsignedDivRemLoweringSemantics
abbrev unsignedDivRemDeterministic_of_unsignedDivRemLoweringSemantics :=
  @Nightstream.Rv64IM.unsignedDivRemDeterministic_of_unsignedDivRemLoweringSemantics

end UnsignedDivRemLoweringSemanticsInterface

end Nightstream.Rv64IM
