import Nightstream.Rv64IM.Execution.WordShiftWordArithmetic

namespace Nightstream.Rv64IM

namespace WordShiftWordArithmeticInterface

abbrev addw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.addw_wordArithmetic_of_wordShiftWordArithmetic
abbrev addw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.addw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev addiw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.addiw_wordArithmetic_of_wordShiftWordArithmetic
abbrev addiw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.addiw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev subw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.subw_wordArithmetic_of_wordShiftWordArithmetic
abbrev subw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.subw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev sllw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sllw_wordArithmetic_of_wordShiftWordArithmetic
abbrev sllw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sllw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev slliw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.slliw_wordArithmetic_of_wordShiftWordArithmetic
abbrev slliw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.slliw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev srlw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.srlw_wordArithmetic_of_wordShiftWordArithmetic
abbrev srlw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.srlw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev srliw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.srliw_wordArithmetic_of_wordShiftWordArithmetic
abbrev srliw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.srliw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev sraw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sraw_wordArithmetic_of_wordShiftWordArithmetic
abbrev sraw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sraw_authenticatedWordArithmetic_of_wordShiftWordArithmetic
abbrev sraiw_wordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sraiw_wordArithmetic_of_wordShiftWordArithmetic
abbrev sraiw_authenticatedWordArithmetic_of_wordShiftWordArithmetic :=
  @Nightstream.Rv64IM.sraiw_authenticatedWordArithmetic_of_wordShiftWordArithmetic

end WordShiftWordArithmeticInterface

end Nightstream.Rv64IM
