import Nightstream.Rv64IM.Execution.WordShiftOpcodeSemantics

namespace Nightstream.Rv64IM

namespace WordShiftOpcodeSemanticsInterface

abbrev opcodeBound_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.opcodeBound_of_wordShiftOpcodeSemantics
abbrev flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.flags_of_wordShiftOpcodeSemantics
abbrev addw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.addw_flags_of_wordShiftOpcodeSemantics
abbrev addiw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.addiw_flags_of_wordShiftOpcodeSemantics
abbrev subw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.subw_flags_of_wordShiftOpcodeSemantics
abbrev sllw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.sllw_flags_of_wordShiftOpcodeSemantics
abbrev slliw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.slliw_flags_of_wordShiftOpcodeSemantics
abbrev srlw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.srlw_flags_of_wordShiftOpcodeSemantics
abbrev srliw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.srliw_flags_of_wordShiftOpcodeSemantics
abbrev sraw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.sraw_flags_of_wordShiftOpcodeSemantics
abbrev sraiw_flags_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.sraiw_flags_of_wordShiftOpcodeSemantics
abbrev sequenceCorrect_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShiftOpcodeSemantics
abbrev sequenceDeterministic_of_wordShiftOpcodeSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_wordShiftOpcodeSemantics

end WordShiftOpcodeSemanticsInterface

end Nightstream.Rv64IM
