import Nightstream.Rv64IM.Execution.WordShiftSemantics

namespace Nightstream.Rv64IM

namespace WordShiftSemanticsInterface

abbrev WordShiftExecutionFacts := @Nightstream.Rv64IM.WordShiftExecutionFacts
abbrev wordShiftExecutionFacts_of_opcodeClassFacts :=
  @Nightstream.Rv64IM.wordShiftExecutionFacts_of_opcodeClassFacts
abbrev frame_row_eq_at_index_of_wordShiftExecutionFacts :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_wordShiftExecutionFacts
abbrev adjacentStates_of_wordShiftExecutionFacts :=
  @Nightstream.Rv64IM.adjacentStates_of_wordShiftExecutionFacts
abbrev preparedStep_matches_row_of_wordShiftExecutionFacts :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_wordShiftExecutionFacts
abbrev successor_matches_rows_of_wordShiftExecutionFacts :=
  @Nightstream.Rv64IM.successor_matches_rows_of_wordShiftExecutionFacts
abbrev row_has_opcodeClass_at_index_of_wordShiftExecutionFacts :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_wordShiftExecutionFacts
noncomputable abbrev wordShiftExecutionFacts_of_stepComposition :=
  @Nightstream.Rv64IM.wordShiftExecutionFacts_of_stepComposition

end WordShiftSemanticsInterface

end Nightstream.Rv64IM
