import Nightstream.Rv64IM.Execution.WordShiftLoweringSemantics

namespace Nightstream.Rv64IM

namespace WordShiftLoweringSemanticsInterface

abbrev fetchDecodeBound_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.fetchDecodeBound_of_wordShiftLoweringSemantics
abbrev decodedRow_valid_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.decodedRow_valid_of_wordShiftLoweringSemantics
abbrev decodeHandoffBound_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.decodeHandoffBound_of_wordShiftLoweringSemantics
abbrev x0WritePreserved_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.x0WritePreserved_of_wordShiftLoweringSemantics
abbrev nonFinalRdTarget_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.nonFinalRdTarget_of_wordShiftLoweringSemantics
abbrev frame_row_eq_at_index_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.frame_row_eq_at_index_of_wordShiftLoweringSemantics
abbrev adjacentStates_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.adjacentStates_of_wordShiftLoweringSemantics
abbrev preparedStep_matches_row_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.preparedStep_matches_row_of_wordShiftLoweringSemantics
abbrev successor_matches_rows_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.successor_matches_rows_of_wordShiftLoweringSemantics
abbrev row_has_opcodeClass_at_index_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.row_has_opcodeClass_at_index_of_wordShiftLoweringSemantics
abbrev sequenceCorrect_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShiftLoweringSemantics
abbrev sequenceDeterministic_of_wordShiftLoweringSemantics :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_wordShiftLoweringSemantics

end WordShiftLoweringSemanticsInterface

end Nightstream.Rv64IM
