import Nightstream.Chip8.Stage2.RegisterHistoryProjection

namespace Nightstream.Chip8

namespace RegisterHistoryProjectionInterface

abbrev registerHistoryFamily := Nightstream.Chip8.registerHistoryFamily
abbrev RegisterHistoryBundle := @Nightstream.Chip8.RegisterHistoryBundle
abbrev RegisterHistoryBundleBound := @Nightstream.Chip8.RegisterHistoryBundleBound
noncomputable abbrev registerHistoryBundle_of_exactTrace :=
  @Nightstream.Chip8.registerHistoryBundle_of_exactTrace
abbrev registerHistoryBundleBound_of_exactTrace :=
  @Nightstream.Chip8.registerHistoryBundleBound_of_exactTrace
abbrev registerHistoryBundle_initialRegisterValue :=
  @Nightstream.Chip8.registerHistoryBundle_initialRegisterValue
abbrev registerHistoryBundle_initialIValue :=
  @Nightstream.Chip8.registerHistoryBundle_initialIValue
abbrev registerHistoryReads_eq_roleValues_tracewise :=
  @Nightstream.Chip8.registerHistoryReads_eq_roleValues_tracewise
abbrev registerHistoryWrites_eq_roleValues_tracewise :=
  @Nightstream.Chip8.registerHistoryWrites_eq_roleValues_tracewise
abbrev registerHistoryProjection := @Nightstream.Chip8.registerHistoryProjection
abbrev registerHistoryProjection_is_projectionFamily :=
  @Nightstream.Chip8.registerHistoryProjection_is_projectionFamily
abbrev registerHistoryProjection_not_mainLane :=
  @Nightstream.Chip8.registerHistoryProjection_not_mainLane
abbrev registerHistoryProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Chip8.registerHistoryProjection_decide_eq_foldSeparate_of_supported
abbrev registerHistoryProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Chip8.registerHistoryProjection_decide_eq_exportFinal_of_unsupported

end RegisterHistoryProjectionInterface

end Nightstream.Chip8
