import Nightstream.Rv64IM.Kernel.AcceptedProofSoundness
import Nightstream.Rv64IM.Kernel.AcceptedProofExecutionResultInterface
import Nightstream.Rv64IM.Kernel.PublicProofBoundaryInterface
import Nightstream.Rv64IM.Kernel.PublicProofSchemaInterface

namespace Nightstream.Rv64IM.AcceptedProofSoundnessInterface

abbrev AcceptedProofSoundness := @Nightstream.Rv64IM.AcceptedProofSoundness
abbrev AcceptedProofConclusion := @Nightstream.Rv64IM.AcceptedProofConclusion
abbrev AcceptedProofExecutionResult := @Nightstream.Rv64IM.AcceptedProofExecutionResult
abbrev PublicProofBoundary := @Nightstream.Rv64IM.PublicProofBoundary
abbrev PublicProofBoundaryExecutionResult := @Nightstream.Rv64IM.PublicProofBoundaryExecutionResult
abbrev Rv64imPublicProofBoundary := @Nightstream.Rv64IM.Rv64imPublicProofBoundary
abbrev Rv64imPublicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofBoundaryExecutionResult
abbrev Rv64imPublicProofSchema := @Nightstream.Rv64IM.Rv64imPublicProofSchema
abbrev Rv64imPublicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofSchemaExecutionResult
abbrev acceptedProofSoundness_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofSoundness_of_exactKernelBoundaries
abbrev acceptedProofConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_acceptedProofSoundness
abbrev acceptedProofImpliesConclusion := @Nightstream.Rv64IM.acceptedProofImpliesConclusion
abbrev acceptedProofExecutionResult_of_acceptedProofConclusion :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_acceptedProofConclusion
abbrev acceptedProofExecutionResult_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_acceptedProofSoundness
abbrev acceptedProofImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionAndPublicResult
abbrev acceptedProofConclusion_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyAcceptedProofConclusion :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyAcceptedProofConclusion
abbrev acceptedProofExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyExecutionAndPublicResult
abbrev publicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundary_of_exactKernelBoundaries
abbrev publicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_boundary
abbrev publicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.publicProofBoundaryImpliesExecutionAndPublicResult
abbrev executionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundaryExecutionResult
abbrev preparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev executionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundary
abbrev preparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundary
abbrev fullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundary
abbrev publicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyPublicProofExecutionAndPublicResult
abbrev executionCorrect_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.executionCorrect_of_exactKernelBoundaries_via_publicProofBoundary
abbrev preparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary
abbrev fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPublicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundary_of_exactKernelBoundaries
abbrev rv64imPublicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_boundary
abbrev rv64imPublicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryImpliesExecutionAndPublicResult
abbrev rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundary
abbrev rv64imPreparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundary
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundary
abbrev rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult
abbrev rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPublicProofSchema_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchema_of_exactKernelBoundaries
abbrev rv64imPublicProofSchemaExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_boundary
abbrev rv64imPublicProofSchemaImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaImpliesExecutionAndPublicResult
abbrev rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imExecutionCorrect_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchemaExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchema
abbrev rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema
abbrev acceptedProofExecutionResult_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_publicProofSchemaExecutionResult
abbrev acceptedProofExecutionResult_of_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_publicProofSchema
abbrev acceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema
abbrev acceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_publicProofSchemaExecutionResult
abbrev rv64imAcceptedProofExecutionResult_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imAcceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult
abbrev rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries
abbrev rv64imAcceptedProofImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofImpliesExecutionAndPublicResult
abbrev exactKernelBoundariesImplyRv64imExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imExecutionAndPublicResult
abbrev exactKernelBoundaries_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.exactKernelBoundaries_of_acceptedProofSoundness
abbrev topLevelSoundness_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.topLevelSoundness_of_acceptedProofSoundness
abbrev kernelSoundnessConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSoundnessConclusion_of_acceptedProofSoundness
abbrev kernelSemanticClosure_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_acceptedProofSoundness
abbrev executionCorrect_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_acceptedProofSoundness
abbrev preparedStepExportBound_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_acceptedProofSoundness
abbrev fullHaltedExecutionClaim_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_acceptedProofSoundness
abbrev acceptedProofImpliesKernelSoundnessConclusion :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSoundnessConclusion
abbrev acceptedProofImpliesKernelSemanticClosure :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSemanticClosure
abbrev acceptedProofImpliesExecutionCorrect :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionCorrect
abbrev acceptedProofImpliesPreparedStepExportBound :=
  @Nightstream.Rv64IM.acceptedProofImpliesPreparedStepExportBound
abbrev acceptedProofImpliesFullHaltedExecutionClaim :=
  @Nightstream.Rv64IM.acceptedProofImpliesFullHaltedExecutionClaim

end Nightstream.Rv64IM.AcceptedProofSoundnessInterface
