import Nightstream.Rv64IM.Kernel.AcceptedPublicProofConsequences

namespace Nightstream.Rv64IM.AcceptedPublicProofInterface

abbrev acceptedPublicProofImpliesExecutionConsequences :=
  @Nightstream.Rv64IM.acceptedPublicProofImpliesExecutionConsequences
abbrev exactKernelBoundariesImplyAcceptedPublicProofExecutionConsequences :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyAcceptedPublicProofExecutionConsequences

abbrev rv64imAcceptedPublicProofImpliesExecutionConsequences :=
  @Nightstream.Rv64IM.rv64imAcceptedPublicProofImpliesExecutionConsequences
abbrev exactKernelBoundariesImplyRv64imAcceptedPublicProofExecutionConsequences :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imAcceptedPublicProofExecutionConsequences

end Nightstream.Rv64IM.AcceptedPublicProofInterface
