import Nightstream.Rv64IM.Kernel.AcceptedProofArtifactConsequences

namespace Nightstream.Rv64IM.AcceptedProofArtifactConsequencesInterface

abbrev acceptedProofArtifactBoundaryRecoversExactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofArtifactBoundaryRecoversExactKernelBoundaries
abbrev acceptedProofArtifactBoundaryRecoversAcceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofArtifactBoundaryRecoversAcceptedProofSoundness
abbrev acceptedProofArtifactHasExactPublicProofProjection :=
  @Nightstream.Rv64IM.acceptedProofArtifactHasExactPublicProofProjection
abbrev acceptedProofExecutionResult_of_acceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_acceptedProofArtifactBoundary
abbrev acceptedProofArtifactBoundaryImpliesExecutionConsequences :=
  @Nightstream.Rv64IM.acceptedProofArtifactBoundaryImpliesExecutionConsequences
abbrev acceptedProofArtifactBoundaryImpliesAcceptedPublicProofExecutionConsequences :=
  @Nightstream.Rv64IM.acceptedProofArtifactBoundaryImpliesAcceptedPublicProofExecutionConsequences

end Nightstream.Rv64IM.AcceptedProofArtifactConsequencesInterface
