import Nightstream.Rv64IM.Kernel.AcceptedProofArtifact

/-!
Interface for the theorem-facing RV64IM accepted-proof artifact boundary.
-/

namespace Nightstream.Rv64IM.AcceptedProofArtifactInterface

abbrev AcceptedProofArtifact := @Nightstream.Rv64IM.AcceptedProofArtifact
abbrev AcceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.AcceptedProofArtifactBoundary
abbrev exactKernelBoundaries_of_acceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.exactKernelBoundaries_of_acceptedProofArtifactBoundary
abbrev recomputedPublicProofSchema_of_acceptedProofArtifact :=
  @Nightstream.Rv64IM.recomputedPublicProofSchema_of_acceptedProofArtifact
abbrev publicProofBoundary_of_acceptedProofArtifact :=
  @Nightstream.Rv64IM.publicProofBoundary_of_acceptedProofArtifact
abbrev acceptedPublicProof_of_acceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.acceptedPublicProof_of_acceptedProofArtifactBoundary
abbrev publicProofSchemaExecutionResult_of_acceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.publicProofSchemaExecutionResult_of_acceptedProofArtifactBoundary
abbrev acceptedProofSoundness_of_acceptedProofArtifactBoundary :=
  @Nightstream.Rv64IM.acceptedProofSoundness_of_acceptedProofArtifactBoundary

end Nightstream.Rv64IM.AcceptedProofArtifactInterface
