import Nightstream.Rv64IM.Kernel.AlignedMemoryOpcodeSemantics

namespace Nightstream.Rv64IM

namespace AlignedMemoryOpcodeSemanticsInterface

noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_kernelSoundness
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_exactKernelBoundaries

end AlignedMemoryOpcodeSemanticsInterface

end Nightstream.Rv64IM
