import Nightstream.Rv64IM.Kernel.BridgeBinding

namespace Nightstream.Rv64IM

namespace BridgeBindingInterface

abbrev KernelBridgeBindingWitness := @Nightstream.Rv64IM.KernelBridgeBindingWitness
abbrev KernelBridgeTraceBound := @Nightstream.Rv64IM.KernelBridgeTraceBound
abbrev kernelBridgeBindingWitness_at_index_of_kernelBridgeTraceBound :=
  @Nightstream.Rv64IM.kernelBridgeBindingWitness_at_index_of_kernelBridgeTraceBound
abbrev exactBridgeBindingAtIndex_of_kernelBridgeTraceBound :=
  @Nightstream.Rv64IM.exactBridgeBindingAtIndex_of_kernelBridgeTraceBound
abbrev preparedStep_mem_rowBindings_of_kernelBridgeBindingWitness :=
  @Nightstream.Rv64IM.preparedStep_mem_rowBindings_of_kernelBridgeBindingWitness
abbrev preparedStep_exported_of_kernelBridgeBindingWitness :=
  @Nightstream.Rv64IM.preparedStep_exported_of_kernelBridgeBindingWitness
abbrev preparedStep_exported_at_index_of_kernelBridgeTraceBound :=
  @Nightstream.Rv64IM.preparedStep_exported_at_index_of_kernelBridgeTraceBound

end BridgeBindingInterface

end Nightstream.Rv64IM
