import Nightstream.Rv64IM.Kernel.ControlFlowOpcodeSemantics

namespace Nightstream.Rv64IM

namespace ControlFlowOpcodeSemanticsInterface

abbrev lane_isJal_of_kernelSoundness :=
  @Nightstream.Rv64IM.lane_isJal_of_kernelSoundness
abbrev lane_isJalr_of_kernelSoundness :=
  @Nightstream.Rv64IM.lane_isJalr_of_kernelSoundness
abbrev takenTargetAlignment_of_jal_of_kernelSoundness :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jal_of_kernelSoundness
abbrev takenTargetAlignment_of_jalr_of_kernelSoundness :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jalr_of_kernelSoundness
abbrev lane_isJal_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.lane_isJal_of_exactKernelBoundaries
abbrev takenTargetAlignment_of_jal_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jal_of_exactKernelBoundaries

end ControlFlowOpcodeSemanticsInterface

end Nightstream.Rv64IM
