import Nightstream.Rv64IM.Kernel.ExactKernelBoundaries
import Nightstream.Rv64IM.Kernel.AcceptedProofSoundnessInterface
import Nightstream.Rv64IM.Kernel.AcceptedProofExecutionResultInterface
import Nightstream.Rv64IM.Kernel.PublicProofBoundaryInterface
import Nightstream.Rv64IM.Kernel.PublicProofSchemaInterface
import Nightstream.Rv64IM.Kernel.SemanticClosureInterface
import Nightstream.Rv64IM.Kernel.TopLevelSoundnessInterface
import Nightstream.Rv64IM.Execution.ImportedSequenceSemanticsInterface
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedClosureInterface
import Nightstream.Rv64IM.Stage1.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedSemanticsInterface
import Nightstream.Rv64IM.Stage2.AuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedClosureInterface
import Nightstream.Rv64IM.Stage2.ImportedAuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedClosureInterface
import Nightstream.Rv64IM.Stage3.ImportedContinuitySemanticsInterface
import Nightstream.Rv64IM.Stage3.ExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Kernel.AlignedMemoryOpcodeSemantics
import Nightstream.Rv64IM.Kernel.NarrowMemoryHelperResultSemantics
import Nightstream.Rv64IM.Kernel.NarrowMemoryPayloadSemantics
import Nightstream.Rv64IM.Kernel.OpcodeFamilySemantics
import Nightstream.Rv64IM.Kernel.WordArithmeticSemantics

namespace Nightstream.Rv64IM

namespace ExactKernelBoundariesInterface

abbrev ExactKernelBoundaries := @Nightstream.Rv64IM.ExactKernelBoundaries
abbrev AcceptedProofSoundness := @Nightstream.Rv64IM.AcceptedProofSoundness
abbrev AcceptedProofConclusion := @Nightstream.Rv64IM.AcceptedProofConclusion
abbrev AcceptedProofExecutionResult := @Nightstream.Rv64IM.AcceptedProofExecutionResult
abbrev PublicProofBoundary := @Nightstream.Rv64IM.PublicProofBoundary
abbrev PublicProofBoundaryExecutionResult := @Nightstream.Rv64IM.PublicProofBoundaryExecutionResult
abbrev Rv64imPublicProofBoundary := @Nightstream.Rv64IM.Rv64imPublicProofBoundary
abbrev Rv64imPublicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofBoundaryExecutionResult
abbrev Rv64imPublicProofSchema := @Nightstream.Rv64IM.Rv64imPublicProofSchema
abbrev Rv64imPublicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofSchemaExecutionResult
abbrev KernelSemanticClosure := @Nightstream.Rv64IM.KernelSemanticClosure
abbrev TopLevelSoundness := @Nightstream.Rv64IM.TopLevelSoundness
abbrev kernelSoundnessAccepted_of_exactBoundaries :=
  @Nightstream.Rv64IM.kernelSoundnessAccepted_of_exactBoundaries
abbrev kernelSoundness_of_exactBoundaries :=
  @Nightstream.Rv64IM.kernelSoundness_of_exactBoundaries
abbrev kernelSemanticClosure_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_exactKernelBoundaries
abbrev topLevelSoundness_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.topLevelSoundness_of_exactKernelBoundaries
abbrev acceptedProofSoundness_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofSoundness_of_exactKernelBoundaries
abbrev acceptedProofConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_acceptedProofSoundness
abbrev acceptedProofImpliesConclusion := @Nightstream.Rv64IM.acceptedProofImpliesConclusion
abbrev acceptedProofExecutionResult_of_acceptedProofConclusion :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_acceptedProofConclusion
abbrev acceptedProofExecutionResult_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_acceptedProofSoundness
abbrev acceptedProofImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionAndPublicResult
abbrev acceptedProofConclusion_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyAcceptedProofConclusion :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyAcceptedProofConclusion
abbrev acceptedProofExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyExecutionAndPublicResult
abbrev publicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundary_of_exactKernelBoundaries
abbrev publicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_boundary
abbrev publicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.publicProofBoundaryImpliesExecutionAndPublicResult
abbrev executionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundaryExecutionResult
abbrev preparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev executionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundary
abbrev preparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundary
abbrev fullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundary
abbrev publicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyPublicProofExecutionAndPublicResult
abbrev executionCorrect_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.executionCorrect_of_exactKernelBoundaries_via_publicProofBoundary
abbrev preparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary
abbrev fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPublicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundary_of_exactKernelBoundaries
abbrev rv64imPublicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_boundary
abbrev rv64imPublicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryImpliesExecutionAndPublicResult
abbrev rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundary
abbrev rv64imPreparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundary
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundary
abbrev rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult
abbrev rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofBoundary
abbrev rv64imPublicProofSchema_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchema_of_exactKernelBoundaries
abbrev rv64imPublicProofSchemaExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_boundary
abbrev rv64imPublicProofSchemaImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaImpliesExecutionAndPublicResult
abbrev rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imExecutionCorrect_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchemaExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchema
abbrev rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema
abbrev acceptedProofExecutionResult_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_publicProofSchemaExecutionResult
abbrev acceptedProofExecutionResult_of_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_publicProofSchema
abbrev acceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema
abbrev acceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_publicProofSchemaExecutionResult
abbrev rv64imAcceptedProofExecutionResult_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imAcceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imAcceptedProofImpliesExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imAcceptedProofExecutionResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult
abbrev rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imAcceptedProofExecutionResult_of_exactKernelBoundaries
abbrev rv64imAcceptedProofImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imAcceptedProofImpliesExecutionAndPublicResult
abbrev exactKernelBoundariesImplyRv64imExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imExecutionAndPublicResult
abbrev topLevelSoundness_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.topLevelSoundness_of_acceptedProofSoundness
abbrev kernelSoundnessConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSoundnessConclusion_of_acceptedProofSoundness
abbrev kernelSemanticClosure_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_acceptedProofSoundness
abbrev executionCorrect_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_acceptedProofSoundness
abbrev preparedStepExportBound_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_acceptedProofSoundness
abbrev fullHaltedExecutionClaim_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_acceptedProofSoundness
abbrev acceptedProofImpliesKernelSoundnessConclusion :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSoundnessConclusion
abbrev acceptedProofImpliesKernelSemanticClosure :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSemanticClosure
abbrev acceptedProofImpliesExecutionCorrect :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionCorrect
abbrev acceptedProofImpliesPreparedStepExportBound :=
  @Nightstream.Rv64IM.acceptedProofImpliesPreparedStepExportBound
abbrev acceptedProofImpliesFullHaltedExecutionClaim :=
  @Nightstream.Rv64IM.acceptedProofImpliesFullHaltedExecutionClaim
abbrev kernelSemanticClosure_of_topLevelSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_topLevelSoundness
abbrev executionCorrect_of_topLevelSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_topLevelSoundness
abbrev preparedStepExportBound_of_topLevelSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_topLevelSoundness
abbrev stage2AuthenticatedHistorySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_topLevelSoundness
abbrev stage3ContinuitySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_topLevelSoundness
abbrev stage3ExportSemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_topLevelSoundness
abbrev pcAdjacentBridge_of_topLevelSoundness :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_topLevelSoundness
abbrev activePrefixContinuity_of_topLevelSoundness :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_topLevelSoundness
abbrev fullHaltedExecutionClaim_of_topLevelSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_topLevelSoundness
abbrev executionCorrect_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.executionCorrect_of_exactKernelBoundaries
abbrev ImportedExpandedRowSequenceSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedExpandedRowSequenceSemantics
abbrev importedExpandedRowSequenceSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedExpandedRowSequenceSemanticsCheck
abbrev stage1RowBindingOfExecutionRow_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1RowBindingOfExecutionRow
abbrev stage1SummaryOfExecutionRows_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1SummaryOfExecutionRows
abbrev ImportedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage1Closure
abbrev importedStage1ClosureCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage1ClosureCheck
abbrev stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure
abbrev stage1Rows_length_eq_executionRows_length_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1Rows_length_eq_executionRows_length_of_importedStage1Closure
abbrev ImportedStage1ProjectionSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage1ProjectionSemantics
abbrev importedStage1ProjectionSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage1ProjectionSemanticsCheck
abbrev ImportedStage1LocalSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage1LocalSemantics
abbrev importedStage1LocalSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemanticsCheck
abbrev stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure
abbrev importedStage1LocalSemantics_of_importedStage1Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemantics_of_importedStage1Closure_and_sequence
abbrev stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure
abbrev stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure
abbrev stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure
abbrev stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure
abbrev stage2SummaryOfExecutionRows_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2SummaryOfExecutionRows
abbrev ImportedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage2Closure
abbrev importedStage2ClosureCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2ClosureCheck
abbrev stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure
abbrev ImportedStage2LocalSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage2LocalSemantics
abbrev importedStage2LocalSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemanticsCheck
abbrev ImportedStage2HistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage2HistorySemantics
abbrev importedStage2HistorySemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemanticsCheck
abbrev ImportedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage2AuthenticatedHistorySemantics
abbrev Stage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.Stage2AuthenticatedHistorySemantics
abbrev importedStage2AuthenticatedHistorySemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemanticsCheck
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics
abbrev importedStage2LocalSemantics_of_importedStage2Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2HistorySemantics_of_importedStage2Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence
abbrev stage2AuthenticatedHistorySemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_exactBoundaries
abbrev registerTimelineBound_of_exactBoundaries :=
  @Nightstream.Rv64IM.registerTimelineBound_of_exactBoundaries
abbrev ramTimelineBound_of_exactBoundaries :=
  @Nightstream.Rv64IM.ramTimelineBound_of_exactBoundaries
abbrev stage3SummaryOfExecutionRows_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3SummaryOfExecutionRows
abbrev ImportedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage3Closure
abbrev importedStage3ClosureCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3ClosureCheck
abbrev stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure
abbrev stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure
abbrev ImportedStage3LocalSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage3LocalSemantics
abbrev importedStage3LocalSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemanticsCheck
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure
abbrev importedStage3LocalSemantics_of_importedStage3Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemantics_of_importedStage3Closure_and_sequence
abbrev continuityEventLocalSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics
abbrev continuityEventLocalSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemanticsCheck
abbrev ImportedStage3ContinuitySemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage3ContinuitySemantics
abbrev importedStage3ContinuitySemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemanticsCheck
abbrev ImportedStage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.ImportedStage3ExportSemantics
abbrev Stage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.Stage3ExportSemantics
abbrev importedStage3ExportSemanticsCheck_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemanticsCheck
abbrev continuityEventLocalSemantics_of_mem_of_importedStage3Closure_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics_of_mem_of_importedStage3Closure
abbrev importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics
abbrev stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics
abbrev importedStage3ExportSemantics_of_importedStage3Closure_and_sequence_exactKernelBoundarySurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemantics_of_importedStage3Closure_and_sequence
abbrev stage3ExportSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_exactBoundaries
abbrev stage3ContinuitySemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_exactBoundaries
abbrev activePrefixContinuity_of_exactBoundaries :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_exactBoundaries
abbrev exactPreparedStepBridgeAtIndex_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactPreparedStepBridgeAtIndex_of_exactKernelBoundaries
noncomputable abbrev canonicalOpcodeProofs_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.canonicalOpcodeProofs_of_exactKernelBoundaries
noncomputable abbrev exactOpcodeFamilySemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_exactKernelBoundaries
noncomputable abbrev exactWordArithmeticSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_exactKernelBoundaries
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_exactKernelBoundaries
noncomputable abbrev exactNarrowMemoryHelperResultSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_exactKernelBoundaries
noncomputable abbrev exactNarrowMemoryPayloadSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryPayloadSemantics_of_exactKernelBoundaries

end ExactKernelBoundariesInterface

end Nightstream.Rv64IM
