import Nightstream.Rv64IM.Kernel.KernelSoundness
import Nightstream.Rv64IM.Kernel.AcceptedProofSoundnessInterface
import Nightstream.Rv64IM.Kernel.SemanticClosureInterface
import Nightstream.Rv64IM.Kernel.TopLevelSoundnessInterface
import Nightstream.Rv64IM.Execution.ImportedSequenceSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedClosureInterface
import Nightstream.Rv64IM.Stage1.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedSemanticsInterface
import Nightstream.Rv64IM.Stage2.AuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedClosureInterface
import Nightstream.Rv64IM.Stage2.ImportedAuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedClosureInterface
import Nightstream.Rv64IM.Stage3.ImportedContinuitySemanticsInterface
import Nightstream.Rv64IM.Stage3.ExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Kernel.AlignedMemoryOpcodeSemantics
import Nightstream.Rv64IM.Kernel.NarrowMemoryHelperResultSemantics
import Nightstream.Rv64IM.Kernel.NarrowMemoryPayloadSemantics
import Nightstream.Rv64IM.Kernel.OpcodeFamilySemantics
import Nightstream.Rv64IM.Kernel.WordArithmeticSemantics

namespace Nightstream.Rv64IM

namespace KernelSoundnessInterface

abbrev KernelSoundnessAccepted := @Nightstream.Rv64IM.KernelSoundnessAccepted
abbrev KernelSoundnessConclusion := @Nightstream.Rv64IM.KernelSoundnessConclusion
abbrev AcceptedProofSoundness := @Nightstream.Rv64IM.AcceptedProofSoundness
abbrev AcceptedProofConclusion := @Nightstream.Rv64IM.AcceptedProofConclusion
abbrev KernelSemanticClosure := @Nightstream.Rv64IM.KernelSemanticClosure
abbrev TopLevelSoundness := @Nightstream.Rv64IM.TopLevelSoundness
abbrev kernelSoundness_of_acceptance := @Nightstream.Rv64IM.kernelSoundness_of_acceptance
abbrev kernelSoundness_of_authenticatedTrace :=
  @Nightstream.Rv64IM.kernelSoundness_of_authenticatedTrace
abbrev kernelSemanticClosure_of_kernelSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_kernelSoundness
abbrev topLevelSoundness_of_kernelSoundness :=
  @Nightstream.Rv64IM.topLevelSoundness_of_kernelSoundness
abbrev topLevelSoundness_of_acceptance :=
  @Nightstream.Rv64IM.topLevelSoundness_of_acceptance
abbrev acceptedProofSoundness_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofSoundness_of_exactKernelBoundaries
abbrev acceptedProofConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_acceptedProofSoundness
abbrev acceptedProofConclusion_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.acceptedProofConclusion_of_exactKernelBoundaries
abbrev topLevelSoundness_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.topLevelSoundness_of_acceptedProofSoundness
abbrev kernelSoundnessConclusion_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSoundnessConclusion_of_acceptedProofSoundness
abbrev kernelSemanticClosure_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_acceptedProofSoundness
abbrev executionCorrect_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_acceptedProofSoundness
abbrev preparedStepExportBound_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_acceptedProofSoundness
abbrev fullHaltedExecutionClaim_of_acceptedProofSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_acceptedProofSoundness
abbrev acceptedProofImpliesKernelSoundnessConclusion :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSoundnessConclusion
abbrev acceptedProofImpliesKernelSemanticClosure :=
  @Nightstream.Rv64IM.acceptedProofImpliesKernelSemanticClosure
abbrev acceptedProofImpliesExecutionCorrect :=
  @Nightstream.Rv64IM.acceptedProofImpliesExecutionCorrect
abbrev acceptedProofImpliesPreparedStepExportBound :=
  @Nightstream.Rv64IM.acceptedProofImpliesPreparedStepExportBound
abbrev acceptedProofImpliesFullHaltedExecutionClaim :=
  @Nightstream.Rv64IM.acceptedProofImpliesFullHaltedExecutionClaim
abbrev kernelSemanticClosure_of_topLevelSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_topLevelSoundness
abbrev executionCorrect_of_topLevelSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_topLevelSoundness
abbrev preparedStepExportBound_of_topLevelSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_topLevelSoundness
abbrev stage2AuthenticatedHistorySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_topLevelSoundness
abbrev stage3ContinuitySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_topLevelSoundness
abbrev stage3ExportSemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_topLevelSoundness
abbrev pcAdjacentBridge_of_topLevelSoundness :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_topLevelSoundness
abbrev activePrefixContinuity_of_topLevelSoundness :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_topLevelSoundness
abbrev fullHaltedExecutionClaim_of_topLevelSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_topLevelSoundness
abbrev programBinding_of_kernelSoundness := @Nightstream.Rv64IM.programBinding_of_kernelSoundness
abbrev authenticatedTrace_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedTrace_of_kernelSoundness
abbrev executionCorrect_of_kernelSoundness :=
  @Nightstream.Rv64IM.executionCorrect_of_kernelSoundness
abbrev ImportedExpandedRowSequenceSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedExpandedRowSequenceSemantics
abbrev importedExpandedRowSequenceSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedExpandedRowSequenceSemanticsCheck
abbrev executionCorrect_on_authenticatedPrefix_of_kernelSoundness :=
  @Nightstream.Rv64IM.executionCorrect_on_authenticatedPrefix_of_kernelSoundness
abbrev mainLaneTraceBoundary_of_kernelSoundness :=
  @Nightstream.Rv64IM.mainLaneTraceBoundary_of_kernelSoundness
abbrev traceLinkBoundary_of_kernelSoundness :=
  @Nightstream.Rv64IM.traceLinkBoundary_of_kernelSoundness
abbrev expandedBytecodeExecutionBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.expandedBytecodeExecutionBound_of_kernelSoundness
abbrev adjacentStateClosed_of_kernelSoundness :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_kernelSoundness
abbrev registerTimelineBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.registerTimelineBound_of_kernelSoundness
abbrev ramTimelineBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.ramTimelineBound_of_kernelSoundness
abbrev fullHaltedExecutionClaim_of_kernelSoundness :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_kernelSoundness
abbrev pcAdjacentBridgeProofPackage_of_kernelSoundness :=
  @Nightstream.Rv64IM.pcAdjacentBridgeProofPackage_of_kernelSoundness
abbrev pcAdjacentBridge_of_kernelSoundness :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_kernelSoundness
abbrev activePrefixContinuity_of_kernelSoundness :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_kernelSoundness
abbrev prePc_eq_stage2PreStatePc_of_kernelSoundness :=
  @Nightstream.Rv64IM.prePc_eq_stage2PreStatePc_of_kernelSoundness
abbrev postPc_eq_stage2PostStatePc_of_kernelSoundness :=
  @Nightstream.Rv64IM.postPc_eq_stage2PostStatePc_of_kernelSoundness
abbrev preparedStepExportBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_kernelSoundness
abbrev preparedStepExportBound_on_authenticatedPrefix_of_kernelSoundness :=
  @Nightstream.Rv64IM.preparedStepExportBound_on_authenticatedPrefix_of_kernelSoundness
abbrev twistConcreteBinding_of_kernelSoundness :=
  @Nightstream.Rv64IM.twistConcreteBinding_of_kernelSoundness
abbrev stage2LinkageBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.stage2LinkageBound_of_kernelSoundness
abbrev registerLinkageBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.registerLinkageBound_of_kernelSoundness
abbrev ramLinkageBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.ramLinkageBound_of_kernelSoundness
abbrev registerWriteValue_of_kernelSoundness :=
  @Nightstream.Rv64IM.registerWriteValue_of_kernelSoundness
abbrev ramLoadMemVal_of_kernelSoundness :=
  @Nightstream.Rv64IM.ramLoadMemVal_of_kernelSoundness
abbrev ramStorePayload_of_kernelSoundness :=
  @Nightstream.Rv64IM.ramStorePayload_of_kernelSoundness
abbrev ramInactiveMemValZero_of_kernelSoundness :=
  @Nightstream.Rv64IM.ramInactiveMemValZero_of_kernelSoundness
abbrev stage1LinkageBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.stage1LinkageBound_of_kernelSoundness
abbrev stage1RowBindingOfExecutionRow_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1RowBindingOfExecutionRow
abbrev stage1SummaryOfExecutionRows_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1SummaryOfExecutionRows
abbrev ImportedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage1Closure
abbrev importedStage1ClosureCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage1ClosureCheck
abbrev stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure
abbrev stage1Rows_length_eq_executionRows_length_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1Rows_length_eq_executionRows_length_of_importedStage1Closure
abbrev ImportedStage1ProjectionSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage1ProjectionSemantics
abbrev importedStage1ProjectionSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage1ProjectionSemanticsCheck
abbrev ImportedStage1LocalSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage1LocalSemantics
abbrev importedStage1LocalSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemanticsCheck
abbrev stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure
abbrev importedStage1LocalSemantics_of_importedStage1Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemantics_of_importedStage1Closure_and_sequence
abbrev stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure
abbrev stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure
abbrev stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure
abbrev stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure
abbrev stage2SummaryOfExecutionRows_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2SummaryOfExecutionRows
abbrev ImportedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage2Closure
abbrev importedStage2ClosureCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2ClosureCheck
abbrev stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure
abbrev ImportedStage2LocalSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage2LocalSemantics
abbrev importedStage2LocalSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemanticsCheck
abbrev ImportedStage2HistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage2HistorySemantics
abbrev importedStage2HistorySemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemanticsCheck
abbrev ImportedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage2AuthenticatedHistorySemantics
abbrev Stage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.Stage2AuthenticatedHistorySemantics
abbrev importedStage2AuthenticatedHistorySemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemanticsCheck
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics
abbrev importedStage2LocalSemantics_of_importedStage2Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2HistorySemantics_of_importedStage2Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence
abbrev stage2AuthenticatedHistorySemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_kernelSoundness
abbrev stage3SummaryOfExecutionRows_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3SummaryOfExecutionRows
abbrev ImportedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage3Closure
abbrev importedStage3ClosureCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3ClosureCheck
abbrev stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure
abbrev stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure
abbrev ImportedStage3LocalSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage3LocalSemantics
abbrev importedStage3LocalSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemanticsCheck
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure
abbrev importedStage3LocalSemantics_of_importedStage3Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemantics_of_importedStage3Closure_and_sequence
abbrev continuityEventLocalSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics
abbrev continuityEventLocalSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemanticsCheck
abbrev ImportedStage3ContinuitySemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage3ContinuitySemantics
abbrev importedStage3ContinuitySemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemanticsCheck
abbrev ImportedStage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.ImportedStage3ExportSemantics
abbrev Stage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.Stage3ExportSemantics
abbrev importedStage3ExportSemanticsCheck_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemanticsCheck
abbrev continuityEventLocalSemantics_of_mem_of_importedStage3Closure_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics_of_mem_of_importedStage3Closure
abbrev importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics
abbrev stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics
abbrev importedStage3ExportSemantics_of_importedStage3Closure_and_sequence_kernelSoundnessSurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemantics_of_importedStage3Closure_and_sequence
abbrev stage3ExportSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_kernelSoundness
abbrev stage3ContinuitySemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_kernelSoundness
abbrev takenTargetAlignmentBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.takenTargetAlignmentBound_of_kernelSoundness
abbrev mulUNoOverflowBound_of_kernelSoundness :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_kernelSoundness
abbrev temporaryRegisterHygiene_of_kernelSoundness :=
  @Nightstream.Rv64IM.temporaryRegisterHygiene_of_kernelSoundness
abbrev mulUNoOverflow_of_kernelSoundness :=
  @Nightstream.Rv64IM.mulUNoOverflow_of_kernelSoundness
abbrev unsignedDivRemSpec_of_kernelSoundness :=
  @Nightstream.Rv64IM.unsignedDivRemSpec_of_kernelSoundness
abbrev unsignedDivRemDeterministic_of_kernelSoundness :=
  @Nightstream.Rv64IM.unsignedDivRemDeterministic_of_kernelSoundness
abbrev changeDivisorCorrect_of_kernelSoundness :=
  @Nightstream.Rv64IM.changeDivisorCorrect_of_kernelSoundness
abbrev remainderFromDividendSign_of_kernelSoundness :=
  @Nightstream.Rv64IM.remainderFromDividendSign_of_kernelSoundness
abbrev signedDivRemSpec_of_kernelSoundness :=
  @Nightstream.Rv64IM.signedDivRemSpec_of_kernelSoundness
noncomputable abbrev canonicalOpcodeProofs_of_kernelSoundness :=
  @Nightstream.Rv64IM.canonicalOpcodeProofs_of_kernelSoundness
noncomputable abbrev exactOpcodeFamilySemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_kernelSoundness
noncomputable abbrev exactWordArithmeticSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_kernelSoundness
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_kernelSoundness
noncomputable abbrev exactNarrowMemoryHelperResultSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_kernelSoundness
noncomputable abbrev exactNarrowMemoryPayloadSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactNarrowMemoryPayloadSemantics_of_kernelSoundness
abbrev rowBindingCoverage_of_kernelSoundness :=
  @Nightstream.Rv64IM.rowBindingCoverage_of_kernelSoundness
abbrev bridgeBindings_length_of_kernelSoundness :=
  @Nightstream.Rv64IM.bridgeBindings_length_of_kernelSoundness
abbrev bridgeBindingWitness_at_index_of_kernelSoundness :=
  @Nightstream.Rv64IM.bridgeBindingWitness_at_index_of_kernelSoundness
abbrev exactPreparedStepBridgeAtIndex_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactPreparedStepBridgeAtIndex_of_kernelSoundness
abbrev transcriptSchedule_of_kernelSoundness :=
  @Nightstream.Rv64IM.transcriptSchedule_of_kernelSoundness
abbrev negligible_epsTotal_of_kernelSoundness :=
  @Nightstream.Rv64IM.negligible_epsTotal_of_kernelSoundness

end KernelSoundnessInterface

end Nightstream.Rv64IM
