import Nightstream.Rv64IM.Kernel.MultiplyOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace MultiplyOpcodeSemanticsInterface

abbrev opcodeBound_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.opcodeBound_of_kernelSoundness_multiply
abbrev flags_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.flags_of_kernelSoundness_multiply
abbrev x0WritePreserved_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.x0WritePreserved_of_kernelSoundness_multiply
abbrev registerOperands_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.registerOperands_of_kernelSoundness_multiply
abbrev activeWrite_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.activeWrite_of_kernelSoundness_multiply
abbrev authenticatedWriteback_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeMultiply_of_kernelSoundness
abbrev routedWriteback_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.routedWriteback_of_activeMultiply_of_kernelSoundness
abbrev authenticatedRoutedWriteback_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeMultiply_of_kernelSoundness
abbrev encodedAluOut_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeMultiply_of_kernelSoundness
abbrev encodedAluResult_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeMultiply_of_kernelSoundness
abbrev authenticatedEncodedAluOut_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeMultiply_of_kernelSoundness
abbrev authenticatedEncodedAluResult_of_activeMultiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeMultiply_of_kernelSoundness
abbrev sequenceCorrect_of_multiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceCorrect_of_multiply_of_kernelSoundness
abbrev sequenceDeterministic_of_multiply_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_multiply_of_kernelSoundness
abbrev flags_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.flags_of_exactKernelBoundaries_multiply
abbrev x0WritePreserved_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactKernelBoundaries_multiply
abbrev registerOperands_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.registerOperands_of_exactKernelBoundaries_multiply
abbrev activeWrite_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.activeWrite_of_exactKernelBoundaries_multiply
abbrev authenticatedWriteback_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeMultiply_of_exactKernelBoundaries
abbrev routedWriteback_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.routedWriteback_of_activeMultiply_of_exactKernelBoundaries
abbrev authenticatedRoutedWriteback_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeMultiply_of_exactKernelBoundaries
abbrev encodedAluOut_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeMultiply_of_exactKernelBoundaries
abbrev encodedAluResult_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeMultiply_of_exactKernelBoundaries
abbrev authenticatedEncodedAluOut_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeMultiply_of_exactKernelBoundaries
abbrev authenticatedEncodedAluResult_of_activeMultiply_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeMultiply_of_exactKernelBoundaries
abbrev normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end MultiplyOpcodeSemanticsInterface

end Nightstream.Rv64IM
