import Nightstream.Rv64IM.Kernel.MultiplyOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace MultiplyOpcodeResultSemanticsInterface

abbrev encodedAluResult_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.encodedAluResult_of_kernelSoundness_multiply
abbrev authenticatedEncodedAluResult_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_kernelSoundness_multiply
abbrev encodedAluResult_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.encodedAluResult_of_exactKernelBoundaries_multiply
abbrev authenticatedEncodedAluResult_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_exactKernelBoundaries_multiply

end MultiplyOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
