import Nightstream.Rv64IM.Kernel.MultiplyEncodedArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyEncodedArithmeticInterface

abbrev encodedArithmetic_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.encodedArithmetic_of_kernelSoundness_multiply
abbrev authenticatedEncodedArithmetic_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_kernelSoundness_multiply
abbrev encodedArithmetic_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.encodedArithmetic_of_exactKernelBoundaries_multiply
abbrev authenticatedEncodedArithmetic_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_exactKernelBoundaries_multiply

end MultiplyEncodedArithmeticInterface

end Nightstream.Rv64IM
