import Nightstream.Rv64IM.Kernel.MultiplyWordArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyWordArithmeticInterface

abbrev wordArithmetic_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.wordArithmetic_of_kernelSoundness_multiply
abbrev authenticatedWordArithmetic_of_kernelSoundness_multiply :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_kernelSoundness_multiply
abbrev wordArithmetic_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactKernelBoundaries_multiply
abbrev authenticatedWordArithmetic_of_exactKernelBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactKernelBoundaries_multiply

end MultiplyWordArithmeticInterface

end Nightstream.Rv64IM
