import Nightstream.Rv64IM.Kernel.NarrowMemoryHelperResultSemantics

namespace Nightstream.Rv64IM

namespace NarrowMemoryHelperResultSemanticsInterface

abbrev exactNarrowMemoryHelperResultSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_kernelSoundness
abbrev loadExtractHelperResult_of_kernelSoundness_narrowMemory :=
  @Nightstream.Rv64IM.loadExtractHelperResult_of_kernelSoundness_narrowMemory
abbrev storeBlendHelperResult_of_kernelSoundness_narrowMemory :=
  @Nightstream.Rv64IM.storeBlendHelperResult_of_kernelSoundness_narrowMemory
abbrev exactNarrowMemoryHelperResultSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_exactKernelBoundaries
abbrev loadExtractHelperResult_of_exactKernelBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.loadExtractHelperResult_of_exactKernelBoundaries_narrowMemory
abbrev storeBlendHelperResult_of_exactKernelBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.storeBlendHelperResult_of_exactKernelBoundaries_narrowMemory

end NarrowMemoryHelperResultSemanticsInterface

end Nightstream.Rv64IM
