import Nightstream.Rv64IM.Kernel.NarrowMemoryOpcodeSemantics

namespace NarrowMemoryOpcodeSemanticsInterface

abbrev flags_of_kernelSoundness_narrowMemory :=
  @Nightstream.Rv64IM.flags_of_kernelSoundness_narrowMemory
abbrev x0WritePreserved_of_kernelSoundness_narrowMemory :=
  @Nightstream.Rv64IM.x0WritePreserved_of_kernelSoundness_narrowMemory
abbrev sequenceCorrect_of_narrowMemory_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceCorrect_of_narrowMemory_of_kernelSoundness
abbrev flags_of_exactKernelBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.flags_of_exactKernelBoundaries_narrowMemory
abbrev x0WritePreserved_of_exactKernelBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactKernelBoundaries_narrowMemory

end NarrowMemoryOpcodeSemanticsInterface
