import Nightstream.Rv64IM.Kernel.NativeAluWordArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluWordArithmeticInterface

abbrev wordArithmetic_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.wordArithmetic_of_kernelSoundness_nativeAlu
abbrev authenticatedWordArithmetic_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_kernelSoundness_nativeAlu
abbrev wordArithmetic_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactKernelBoundaries_nativeAlu
abbrev authenticatedWordArithmetic_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactKernelBoundaries_nativeAlu

end NativeAluWordArithmeticInterface

end Nightstream.Rv64IM
