import Nightstream.Rv64IM.Kernel.NativeAluEncodedArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluEncodedArithmeticInterface

abbrev encodedArithmetic_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.encodedArithmetic_of_kernelSoundness_nativeAlu
abbrev authenticatedEncodedArithmetic_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_kernelSoundness_nativeAlu
abbrev encodedArithmetic_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.encodedArithmetic_of_exactKernelBoundaries_nativeAlu
abbrev authenticatedEncodedArithmetic_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_exactKernelBoundaries_nativeAlu

end NativeAluEncodedArithmeticInterface

end Nightstream.Rv64IM
