import Nightstream.Rv64IM.Kernel.NativeAluOpcodeSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeSemanticsInterface

abbrev opcodeBound_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.opcodeBound_of_kernelSoundness_nativeAlu
abbrev flags_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.flags_of_kernelSoundness_nativeAlu
abbrev x0WritePreserved_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.x0WritePreserved_of_kernelSoundness_nativeAlu
abbrev registerOperands_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.registerOperands_of_kernelSoundness_nativeAlu
abbrev nonX0WriteFacts_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_kernelSoundness_nativeAlu
abbrev activeWrite_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.activeWrite_of_kernelSoundness_nativeAlu
abbrev passiveWrite_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.passiveWrite_of_kernelSoundness_nativeAlu
abbrev authenticatedWriteback_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeNativeAlu_of_kernelSoundness
abbrev routedWriteback_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.routedWriteback_of_activeNativeAlu_of_kernelSoundness
abbrev authenticatedRoutedWriteback_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeNativeAlu_of_kernelSoundness
abbrev encodedAluOut_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeNativeAlu_of_kernelSoundness
abbrev encodedAluResult_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeNativeAlu_of_kernelSoundness
abbrev authenticatedEncodedAluOut_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeNativeAlu_of_kernelSoundness
abbrev authenticatedEncodedAluResult_of_activeNativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeNativeAlu_of_kernelSoundness
abbrev ecall_terminates_of_kernelSoundness :=
  @Nightstream.Rv64IM.ecall_terminates_of_kernelSoundness
abbrev sequenceCorrect_of_nativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceCorrect_of_nativeAlu_of_kernelSoundness
abbrev sequenceDeterministic_of_nativeAlu_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_nativeAlu_of_kernelSoundness
abbrev flags_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.flags_of_exactKernelBoundaries_nativeAlu
abbrev x0WritePreserved_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactKernelBoundaries_nativeAlu
abbrev registerOperands_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.registerOperands_of_exactKernelBoundaries_nativeAlu
abbrev nonX0WriteFacts_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_exactKernelBoundaries_nativeAlu
abbrev activeWrite_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.activeWrite_of_exactKernelBoundaries_nativeAlu
abbrev passiveWrite_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.passiveWrite_of_exactKernelBoundaries_nativeAlu
abbrev authenticatedWriteback_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeNativeAlu_of_exactKernelBoundaries
abbrev routedWriteback_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.routedWriteback_of_activeNativeAlu_of_exactKernelBoundaries
abbrev authenticatedRoutedWriteback_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeNativeAlu_of_exactKernelBoundaries
abbrev encodedAluOut_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeNativeAlu_of_exactKernelBoundaries
abbrev encodedAluResult_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeNativeAlu_of_exactKernelBoundaries
abbrev authenticatedEncodedAluOut_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeNativeAlu_of_exactKernelBoundaries
abbrev authenticatedEncodedAluResult_of_activeNativeAlu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeNativeAlu_of_exactKernelBoundaries
abbrev ecall_terminates_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.ecall_terminates_of_exactKernelBoundaries

end NativeAluOpcodeSemanticsInterface

end Nightstream.Rv64IM
