import Nightstream.Rv64IM.Kernel.NativeAluOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeResultSemanticsInterface

abbrev encodedAluResult_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.encodedAluResult_of_kernelSoundness_nativeAlu
abbrev authenticatedEncodedAluResult_of_kernelSoundness_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_kernelSoundness_nativeAlu
abbrev encodedAluResult_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.encodedAluResult_of_exactKernelBoundaries_nativeAlu
abbrev authenticatedEncodedAluResult_of_exactKernelBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_exactKernelBoundaries_nativeAlu

end NativeAluOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
