import Nightstream.Rv64IM.Kernel.OpcodeFamilySemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace OpcodeFamilySemanticsInterface

noncomputable abbrev exactOpcodeFamilySemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_kernelSoundness
noncomputable abbrev exactOpcodeFamilySemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_exactKernelBoundaries
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_opcodeFamilyKernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end OpcodeFamilySemanticsInterface

end Nightstream.Rv64IM
