import Nightstream.Rv64IM.Kernel.OpcodeClassSemantics

namespace Nightstream.Rv64IM

namespace OpcodeClassSemanticsInterface

noncomputable abbrev canonicalOpcodeClassSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_kernelSoundness
noncomputable abbrev nativeAluFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.nativeAluFacts_of_kernelSoundness
noncomputable abbrev wordShiftFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.wordShiftFacts_of_kernelSoundness
noncomputable abbrev controlFlowFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.controlFlowFacts_of_kernelSoundness
noncomputable abbrev narrowMemoryFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_kernelSoundness
noncomputable abbrev multiplyFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.multiplyFacts_of_kernelSoundness
noncomputable abbrev unsignedDivRemFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_kernelSoundness
noncomputable abbrev signedDivRemFacts_of_kernelSoundness :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_kernelSoundness
noncomputable abbrev canonicalOpcodeClassSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_exactKernelBoundaries
noncomputable abbrev nativeAluFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.nativeAluFacts_of_exactKernelBoundaries
noncomputable abbrev wordShiftFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.wordShiftFacts_of_exactKernelBoundaries
noncomputable abbrev controlFlowFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.controlFlowFacts_of_exactKernelBoundaries
noncomputable abbrev narrowMemoryFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_exactKernelBoundaries
noncomputable abbrev multiplyFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.multiplyFacts_of_exactKernelBoundaries
noncomputable abbrev unsignedDivRemFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_exactKernelBoundaries
noncomputable abbrev signedDivRemFacts_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_exactKernelBoundaries

end OpcodeClassSemanticsInterface

end Nightstream.Rv64IM
