import Nightstream.Rv64IM.Kernel.PublicProofBoundaryConsequences

namespace Nightstream.Rv64IM.PublicProofBoundaryInterface

abbrev PublicProofBoundary := @Nightstream.Rv64IM.PublicProofBoundary
abbrev PublicProofBoundaryExecutionResult := @Nightstream.Rv64IM.PublicProofBoundaryExecutionResult
abbrev publicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundary_of_exactKernelBoundaries
abbrev publicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_boundary
abbrev publicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.publicProofBoundaryImpliesExecutionAndPublicResult
abbrev executionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundaryExecutionResult
abbrev preparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev executionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofBoundary
abbrev preparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofBoundary
abbrev fullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofBoundary
abbrev publicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyPublicProofExecutionAndPublicResult

abbrev Rv64imPublicProofBoundary := @Nightstream.Rv64IM.Rv64imPublicProofBoundary
abbrev Rv64imPublicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofBoundaryExecutionResult
abbrev rv64imPublicProofBoundary_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundary_of_exactKernelBoundaries
abbrev rv64imPublicProofBoundaryExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_boundary
abbrev rv64imPublicProofBoundaryImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryImpliesExecutionAndPublicResult
abbrev rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundaryExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundaryExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundaryExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofBoundary
abbrev rv64imPreparedStepExportBound_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofBoundary
abbrev rv64imFullHaltedExecutionClaim_of_publicProofBoundary :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofBoundary
abbrev rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofBoundaryExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imPublicProofExecutionAndPublicResult

end Nightstream.Rv64IM.PublicProofBoundaryInterface
