import Nightstream.Rv64IM.Kernel.PublicProofSchemaConsequences

namespace Nightstream.Rv64IM.PublicProofSchemaInterface

abbrev PublicProofSchema := @Nightstream.Rv64IM.PublicProofSchema
abbrev PublicProofSchemaExecutionResult := @Nightstream.Rv64IM.PublicProofSchemaExecutionResult
abbrev Rv64imPublicProofSchema := @Nightstream.Rv64IM.Rv64imPublicProofSchema
abbrev Rv64imPublicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.Rv64imPublicProofSchemaExecutionResult
abbrev publicProofBoundary_of_schema := @Nightstream.Rv64IM.publicProofBoundary_of_schema
abbrev publicProofSchemaExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.publicProofSchemaExecutionResult_of_boundary
abbrev publicProofSchemaImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.publicProofSchemaImpliesExecutionAndPublicResult
abbrev publicProofSchema_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofSchema_of_exactKernelBoundaries
abbrev publicProofSchemaExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.publicProofSchemaExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyExecutionAndPublicResult_via_publicProofSchema
abbrev executionCorrect_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofSchemaExecutionResult
abbrev preparedStepExportBound_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofSchemaExecutionResult
abbrev fullHaltedExecutionClaim_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofSchemaExecutionResult
abbrev executionCorrect_of_publicProofSchema :=
  @Nightstream.Rv64IM.executionCorrect_of_publicProofSchema
abbrev preparedStepExportBound_of_publicProofSchema :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_publicProofSchema
abbrev fullHaltedExecutionClaim_of_publicProofSchema :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_publicProofSchema
abbrev executionCorrect_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.executionCorrect_of_exactKernelBoundaries_via_publicProofSchema
abbrev preparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema
abbrev fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imPublicProofSchema_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchema_of_exactKernelBoundaries
abbrev rv64imPublicProofSchemaExecutionResult_of_boundary :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_boundary
abbrev rv64imPublicProofSchemaImpliesExecutionAndPublicResult :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaImpliesExecutionAndPublicResult
abbrev rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.rv64imPublicProofSchemaExecutionResult_of_exactKernelBoundaries
abbrev exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema :=
  @Nightstream.Rv64IM.exactKernelBoundariesImplyRv64imExecutionAndPublicResult_via_publicProofSchema
abbrev rv64imExecutionCorrect_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchemaExecutionResult
abbrev rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchemaExecutionResult
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchemaExecutionResult
abbrev rv64imExecutionCorrect_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_publicProofSchema
abbrev rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imExecutionCorrect_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imPreparedStepExportBound_of_exactKernelBoundaries_via_publicProofSchema
abbrev rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema :=
  @Nightstream.Rv64IM.rv64imFullHaltedExecutionClaim_of_exactKernelBoundaries_via_publicProofSchema

end Nightstream.Rv64IM.PublicProofSchemaInterface
