import Nightstream.Rv64IM.Kernel.RequiredProofCompleteRustExportSurface

namespace Nightstream.Rv64IM

namespace RequiredProofCompleteRustExportSurfaceInterface

def implementationModule : String :=
  "Nightstream.Rv64IM.Kernel.RequiredProofCompleteRustExportSurface"

def exportedModuleNames : List String :=
  [ "Nightstream.Rv64IM.Generated.AcceptedProofArtifactCorpus"
  , "Nightstream.Rv64IM.Kernel.RequiredBackendPayloadSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredRootExecutionSemanticsSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredKernelDesignBridgeSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredProofCompleteRustExportSurface"
  ]

abbrev requiredProofCompleteRustExportChecks :=
  Nightstream.Rv64IM.requiredProofCompleteRustExportChecks
abbrev requiredProofCompleteBackendSurfacePresent :=
  Nightstream.Rv64IM.requiredProofCompleteBackendSurfacePresent
abbrev requiredProofCompleteRootExecutionSemanticsSurfacePresent :=
  Nightstream.Rv64IM.requiredProofCompleteRootExecutionSemanticsSurfacePresent
abbrev requiredProofCompleteKernelDesignBridgeSurfacePresent :=
  Nightstream.Rv64IM.requiredProofCompleteKernelDesignBridgeSurfacePresent
abbrev requiredProofCompleteRustExportSurfacePresent :=
  Nightstream.Rv64IM.requiredProofCompleteRustExportSurfacePresent
abbrev missingRequiredProofCompleteRustExportFields :=
  Nightstream.Rv64IM.missingRequiredProofCompleteRustExportFields
abbrev requiredProofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.requiredProofCompleteRustExportBlockers
abbrev requiredProofCompleteBackendRustExportBlockers :=
  Nightstream.Rv64IM.requiredProofCompleteBackendRustExportBlockers
abbrev requiredProofCompleteRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.requiredProofCompleteRootExecutionSemanticsRustExportBlockers
abbrev requiredProofCompleteKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.requiredProofCompleteKernelDesignBridgeRustExportBlockers
abbrev requiredProofCompleteBackendMissingFields :=
  Nightstream.Rv64IM.requiredProofCompleteBackendMissingFields
abbrev requiredProofCompleteRootExecutionSemanticsMissingFields :=
  Nightstream.Rv64IM.requiredProofCompleteRootExecutionSemanticsMissingFields
abbrev requiredProofCompleteKernelDesignBridgeMissingFields :=
  Nightstream.Rv64IM.requiredProofCompleteKernelDesignBridgeMissingFields
abbrev requiredProofCompleteRustExportReport :=
  Nightstream.Rv64IM.requiredProofCompleteRustExportReport
abbrev uniqueMissingRequiredProofCompleteRustExportFields :=
  Nightstream.Rv64IM.uniqueMissingRequiredProofCompleteRustExportFields
abbrev uniqueRequiredProofCompleteBackendMissingFields :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteBackendMissingFields
abbrev uniqueRequiredProofCompleteRootExecutionSemanticsMissingFields :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteRootExecutionSemanticsMissingFields
abbrev uniqueRequiredProofCompleteKernelDesignBridgeMissingFields :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteKernelDesignBridgeMissingFields
abbrev uniqueRequiredProofCompleteBackendRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteBackendRustExportBlockers
abbrev uniqueRequiredProofCompleteRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteRootExecutionSemanticsRustExportBlockers
abbrev uniqueRequiredProofCompleteKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteKernelDesignBridgeRustExportBlockers
abbrev uniqueRequiredProofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteRustExportBlockers
abbrev rv64imRequiredProofCompleteRustExportChecks :=
  Nightstream.Rv64IM.rv64imRequiredProofCompleteRustExportChecks
abbrev validGeneratedRv64imRequiredProofCompleteBackendSurfaceCases :=
  Nightstream.Rv64IM.validGeneratedRv64imRequiredProofCompleteBackendSurfaceCases
abbrev validGeneratedRv64imRequiredProofCompleteRootExecutionSemanticsSurfaceCases :=
  Nightstream.Rv64IM.validGeneratedRv64imRequiredProofCompleteRootExecutionSemanticsSurfaceCases
abbrev validGeneratedRv64imRequiredProofCompleteKernelDesignBridgeSurfaceCases :=
  Nightstream.Rv64IM.validGeneratedRv64imRequiredProofCompleteKernelDesignBridgeSurfaceCases
abbrev validGeneratedRv64imRequiredProofCompleteRustExportCases :=
  Nightstream.Rv64IM.validGeneratedRv64imRequiredProofCompleteRustExportCases
abbrev rv64imRequiredProofCompleteRustExportReports :=
  Nightstream.Rv64IM.rv64imRequiredProofCompleteRustExportReports

def entrypointContract : Prop := True

theorem entrypointContract_true : entrypointContract := by
  trivial

end RequiredProofCompleteRustExportSurfaceInterface

end Nightstream.Rv64IM
