import Nightstream.Rv64IM.Kernel.SemanticClosure

namespace Nightstream.Rv64IM.KernelSemanticClosureInterface

abbrev KernelSemanticClosure := @Nightstream.Rv64IM.KernelSemanticClosure
abbrev kernelSemanticClosure_of_kernelSoundness := @Nightstream.Rv64IM.kernelSemanticClosure_of_kernelSoundness
abbrev kernelSemanticClosure_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_exactKernelBoundaries

end Nightstream.Rv64IM.KernelSemanticClosureInterface
