import Nightstream.Rv64IM.Kernel.SignedDivRemOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace SignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_kernelSoundness_signedDivRem :=
  @Nightstream.Rv64IM.opcodeBound_of_kernelSoundness_signedDivRem
abbrev div_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.div_flags_of_kernelSoundness
abbrev rem_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.rem_flags_of_kernelSoundness
abbrev divw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.divw_flags_of_kernelSoundness
abbrev remw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.remw_flags_of_kernelSoundness
abbrev spec_of_signedDiv_of_kernelSoundness :=
  @Nightstream.Rv64IM.spec_of_signedDiv_of_kernelSoundness
abbrev spec_of_signedRem_of_kernelSoundness :=
  @Nightstream.Rv64IM.spec_of_signedRem_of_kernelSoundness
abbrev div_flags_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.div_flags_of_exactKernelBoundaries
abbrev spec_of_signedDiv_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.spec_of_signedDiv_of_exactKernelBoundaries
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end SignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
