import Nightstream.Rv64IM.Kernel.TopLevelSoundness

namespace Nightstream.Rv64IM.TopLevelSoundnessInterface

abbrev TopLevelSoundness := @Nightstream.Rv64IM.TopLevelSoundness
abbrev topLevelSoundness_of_kernelSoundness := @Nightstream.Rv64IM.topLevelSoundness_of_kernelSoundness
abbrev topLevelSoundness_of_acceptance := @Nightstream.Rv64IM.topLevelSoundness_of_acceptance
abbrev topLevelSoundness_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.topLevelSoundness_of_exactKernelBoundaries
abbrev kernelSemanticClosure_of_topLevelSoundness :=
  @Nightstream.Rv64IM.kernelSemanticClosure_of_topLevelSoundness
abbrev executionCorrect_of_topLevelSoundness := @Nightstream.Rv64IM.executionCorrect_of_topLevelSoundness
abbrev preparedStepExportBound_of_topLevelSoundness := @Nightstream.Rv64IM.preparedStepExportBound_of_topLevelSoundness
abbrev stage2AuthenticatedHistorySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_topLevelSoundness
abbrev stage3ContinuitySemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ContinuitySemantics_of_topLevelSoundness
abbrev stage3ExportSemantics_of_topLevelSoundness :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_topLevelSoundness
abbrev pcAdjacentBridge_of_topLevelSoundness :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_topLevelSoundness
abbrev activePrefixContinuity_of_topLevelSoundness :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_topLevelSoundness
abbrev fullHaltedExecutionClaim_of_topLevelSoundness := @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_topLevelSoundness

end Nightstream.Rv64IM.TopLevelSoundnessInterface
