import Nightstream.Rv64IM.Kernel.UnsignedDivRemOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace UnsignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_kernelSoundness_unsignedDivRem :=
  @Nightstream.Rv64IM.opcodeBound_of_kernelSoundness_unsignedDivRem
abbrev divu_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.divu_flags_of_kernelSoundness
abbrev remu_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.remu_flags_of_kernelSoundness
abbrev divuw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.divuw_flags_of_kernelSoundness
abbrev remuw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.remuw_flags_of_kernelSoundness
abbrev spec_of_unsignedDivu_of_kernelSoundness :=
  @Nightstream.Rv64IM.spec_of_unsignedDivu_of_kernelSoundness
abbrev spec_of_unsignedRemu_of_kernelSoundness :=
  @Nightstream.Rv64IM.spec_of_unsignedRemu_of_kernelSoundness
abbrev deterministic_of_unsignedDivRem_of_kernelSoundness :=
  @Nightstream.Rv64IM.deterministic_of_unsignedDivRem_of_kernelSoundness
abbrev divu_flags_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.divu_flags_of_exactKernelBoundaries
abbrev spec_of_unsignedDivu_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.spec_of_unsignedDivu_of_exactKernelBoundaries
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_kernelSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end UnsignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
