import Nightstream.Rv64IM.Kernel.WordArithmeticSemantics

namespace Nightstream.Rv64IM

namespace WordArithmeticSemanticsInterface

abbrev exactWordArithmeticSemantics_of_kernelSoundness :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_kernelSoundness
abbrev exactWordArithmeticSemantics_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_exactKernelBoundaries

end WordArithmeticSemanticsInterface

end Nightstream.Rv64IM
