import Nightstream.Rv64IM.Kernel.WordShiftWordArithmetic

namespace Nightstream.Rv64IM

namespace WordShiftWordArithmeticInterface

abbrev wordArithmetic_of_kernelSoundness_wordShift :=
  @Nightstream.Rv64IM.wordArithmetic_of_kernelSoundness_wordShift
abbrev authenticatedWordArithmetic_of_kernelSoundness_wordShift :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_kernelSoundness_wordShift
abbrev wordArithmetic_of_exactKernelBoundaries_wordShift :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactKernelBoundaries_wordShift
abbrev authenticatedWordArithmetic_of_exactKernelBoundaries_wordShift :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactKernelBoundaries_wordShift

end WordShiftWordArithmeticInterface

end Nightstream.Rv64IM
