import Nightstream.Rv64IM.Kernel.WordShiftOpcodeSemantics

namespace Nightstream.Rv64IM

namespace WordShiftOpcodeSemanticsInterface

abbrev opcodeBound_of_kernelSoundness_wordShift :=
  @Nightstream.Rv64IM.opcodeBound_of_kernelSoundness_wordShift
abbrev flags_of_kernelSoundness_wordShift :=
  @Nightstream.Rv64IM.flags_of_kernelSoundness_wordShift
abbrev sraw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.sraw_flags_of_kernelSoundness
abbrev sraiw_flags_of_kernelSoundness :=
  @Nightstream.Rv64IM.sraiw_flags_of_kernelSoundness
abbrev sequenceCorrect_of_wordShift_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShift_of_kernelSoundness
abbrev sequenceDeterministic_of_wordShift_of_kernelSoundness :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_wordShift_of_kernelSoundness
abbrev sraw_flags_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.sraw_flags_of_exactKernelBoundaries
abbrev sequenceCorrect_of_wordShift_of_exactKernelBoundaries :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShift_of_exactKernelBoundaries

end WordShiftOpcodeSemanticsInterface

end Nightstream.Rv64IM
