import Nightstream.Chip8.Kernel.ChallengeDerivation

namespace Nightstream.Chip8

namespace ChallengeDerivationInterface

abbrev ChallengePair := Nightstream.Chip8.ChallengeDerivation.ChallengePair
abbrev stage1LookupLabel := Nightstream.Chip8.ChallengeDerivation.stage1LookupLabel
abbrev stage1GammaLookupLinkLabel := Nightstream.Chip8.ChallengeDerivation.stage1GammaLookupLinkLabel
abbrev stage2TwistCycleLabel := Nightstream.Chip8.ChallengeDerivation.stage2TwistCycleLabel
abbrev stage2GammaRegLabel := Nightstream.Chip8.ChallengeDerivation.stage2GammaRegLabel
abbrev stage2GammaRamLabel := Nightstream.Chip8.ChallengeDerivation.stage2GammaRamLabel
abbrev stage2RegAddrLabel := Nightstream.Chip8.ChallengeDerivation.stage2RegAddrLabel
abbrev stage2RamAddrLabel := Nightstream.Chip8.ChallengeDerivation.stage2RamAddrLabel
abbrev stage2GammaTwistLinkLabel := Nightstream.Chip8.ChallengeDerivation.stage2GammaTwistLinkLabel
abbrev stage3Beta1Label := Nightstream.Chip8.ChallengeDerivation.stage3Beta1Label
abbrev stage3Beta2Label := Nightstream.Chip8.ChallengeDerivation.stage3Beta2Label
abbrev stage3ShiftLabel := Nightstream.Chip8.ChallengeDerivation.stage3ShiftLabel
abbrev stage3GammaShiftLabel := Nightstream.Chip8.ChallengeDerivation.stage3GammaShiftLabel
abbrev sampleFieldCursor := Nightstream.Chip8.ChallengeDerivation.sampleFieldCursor
abbrev sampleChallengePairCursor := Nightstream.Chip8.ChallengeDerivation.sampleChallengePairCursor
abbrev samplePointCursor := Nightstream.Chip8.ChallengeDerivation.samplePointCursor
abbrev root0TranscriptCursor := @Nightstream.Chip8.ChallengeDerivation.root0TranscriptCursor
abbrev sampleStage1LookupPointFromRoot0 := @Nightstream.Chip8.ChallengeDerivation.sampleStage1LookupPointFromRoot0
abbrev sampleStage1GammaLookupLink := Nightstream.Chip8.ChallengeDerivation.sampleStage1GammaLookupLink
abbrev sampleStage2TwistCyclePoint := Nightstream.Chip8.ChallengeDerivation.sampleStage2TwistCyclePoint
abbrev sampleStage2GammaReg := Nightstream.Chip8.ChallengeDerivation.sampleStage2GammaReg
abbrev sampleStage2GammaRam := Nightstream.Chip8.ChallengeDerivation.sampleStage2GammaRam
abbrev sampleStage2RegAddrPoint := Nightstream.Chip8.ChallengeDerivation.sampleStage2RegAddrPoint
abbrev sampleStage2RamAddrPoint := Nightstream.Chip8.ChallengeDerivation.sampleStage2RamAddrPoint
abbrev sampleStage2GammaTwistLink := Nightstream.Chip8.ChallengeDerivation.sampleStage2GammaTwistLink
abbrev sampleStage3Beta1 := Nightstream.Chip8.ChallengeDerivation.sampleStage3Beta1
abbrev sampleStage3Beta2 := Nightstream.Chip8.ChallengeDerivation.sampleStage3Beta2
abbrev sampleStage3ShiftPoint := Nightstream.Chip8.ChallengeDerivation.sampleStage3ShiftPoint
abbrev sampleStage3GammaShift := Nightstream.Chip8.ChallengeDerivation.sampleStage3GammaShift

abbrev sampleFieldCursor_absorbed := @Nightstream.Chip8.ChallengeDerivation.sampleFieldCursor_absorbed
abbrev sampleChallengePairCursor_absorbed := @Nightstream.Chip8.ChallengeDerivation.sampleChallengePairCursor_absorbed
abbrev samplePointCursor_length := @Nightstream.Chip8.ChallengeDerivation.samplePointCursor_length
abbrev samplePointCursor_succ_absorbed := @Nightstream.Chip8.ChallengeDerivation.samplePointCursor_succ_absorbed
abbrev sampleStage1LookupPointFromRoot0_length := @Nightstream.Chip8.ChallengeDerivation.sampleStage1LookupPointFromRoot0_length
abbrev sampleStage2TwistCyclePoint_length := @Nightstream.Chip8.ChallengeDerivation.sampleStage2TwistCyclePoint_length
abbrev sampleStage2RegAddrPoint_length := @Nightstream.Chip8.ChallengeDerivation.sampleStage2RegAddrPoint_length
abbrev sampleStage2RamAddrPoint_length := @Nightstream.Chip8.ChallengeDerivation.sampleStage2RamAddrPoint_length
abbrev sampleStage3ShiftPoint_length := @Nightstream.Chip8.ChallengeDerivation.sampleStage3ShiftPoint_length

end ChallengeDerivationInterface

end Nightstream.Chip8
