import Nightstream.Chip8.Kernel.ConcreteTranscriptParity

namespace Nightstream.Chip8

namespace ConcreteTranscriptParityInterface

abbrev concreteCore := Nightstream.Chip8.ConcreteTranscriptParity.concreteCore
abbrev Cursor := Nightstream.Chip8.ConcreteTranscriptParity.Cursor
abbrev ChallengePair := Nightstream.Chip8.ConcreteTranscriptParity.ChallengePair
abbrev root0DigestCursor := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestCursor
abbrev root0DigestWords := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestWords
abbrev root0DigestBytes := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestBytes
abbrev root0TranscriptCursor := @Nightstream.Chip8.ConcreteTranscriptParity.root0TranscriptCursor
abbrev sampleFieldCursor := Nightstream.Chip8.ConcreteTranscriptParity.sampleFieldCursor
abbrev sampleChallengePairCursor := Nightstream.Chip8.ConcreteTranscriptParity.sampleChallengePairCursor
abbrev samplePointCursor := Nightstream.Chip8.ConcreteTranscriptParity.samplePointCursor
abbrev sampleStage1LookupPointFromRoot0 := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage1LookupPointFromRoot0
abbrev sampleStage1GammaLookupLink := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage1GammaLookupLink
abbrev sampleStage2TwistCyclePoint := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2TwistCyclePoint
abbrev sampleStage2GammaReg := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2GammaReg
abbrev sampleStage2GammaRam := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2GammaRam
abbrev sampleStage2RegAddrPoint := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2RegAddrPoint
abbrev sampleStage2RamAddrPoint := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2RamAddrPoint
abbrev sampleStage2GammaTwistLink := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2GammaTwistLink
abbrev sampleStage3Beta1 := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage3Beta1
abbrev sampleStage3Beta2 := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage3Beta2
abbrev sampleStage3ShiftPoint := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage3ShiftPoint
abbrev sampleStage3GammaShift := Nightstream.Chip8.ConcreteTranscriptParity.sampleStage3GammaShift

abbrev root0DigestCursor_absorbed := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestCursor_absorbed
abbrev root0DigestWords_length := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestWords_length
abbrev root0DigestBytes_length := @Nightstream.Chip8.ConcreteTranscriptParity.root0DigestBytes_length
abbrev sampleFieldCursor_absorbed := @Nightstream.Chip8.ConcreteTranscriptParity.sampleFieldCursor_absorbed
abbrev sampleChallengePairCursor_absorbed := @Nightstream.Chip8.ConcreteTranscriptParity.sampleChallengePairCursor_absorbed
abbrev samplePointCursor_length := @Nightstream.Chip8.ConcreteTranscriptParity.samplePointCursor_length
abbrev sampleStage1LookupPointFromRoot0_length := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage1LookupPointFromRoot0_length
abbrev sampleStage2TwistCyclePoint_length := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2TwistCyclePoint_length
abbrev sampleStage2RegAddrPoint_length := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2RegAddrPoint_length
abbrev sampleStage2RamAddrPoint_length := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage2RamAddrPoint_length
abbrev sampleStage3ShiftPoint_length := @Nightstream.Chip8.ConcreteTranscriptParity.sampleStage3ShiftPoint_length

end ConcreteTranscriptParityInterface

end Nightstream.Chip8
