import Nightstream.Chip8.Kernel.ExternalReleaseArtifact

namespace Nightstream.Chip8

namespace ExternalReleaseArtifactInterface

abbrev ImportedArtifact := Nightstream.Chip8.ExternalReleaseArtifact.ImportedArtifact
abbrev ofVectorCase := Nightstream.Chip8.ExternalReleaseArtifact.ofVectorCase
abbrev semanticRows := Nightstream.Chip8.ExternalReleaseArtifact.semanticRows
abbrev rowProjections := Nightstream.Chip8.ExternalReleaseArtifact.rowProjections
abbrev bridgeClaims := Nightstream.Chip8.ExternalReleaseArtifact.bridgeClaims
abbrev expectedTraceSurface := Nightstream.Chip8.ExternalReleaseArtifact.expectedTraceSurface
abbrev expectedExportSurface := Nightstream.Chip8.ExternalReleaseArtifact.expectedExportSurface
abbrev expectedBundle := Nightstream.Chip8.ExternalReleaseArtifact.expectedBundle
abbrev expectedTranscriptSurface := Nightstream.Chip8.ExternalReleaseArtifact.expectedTranscriptSurface
abbrev expectedOpeningTranscriptSurface :=
  Nightstream.Chip8.ExternalReleaseArtifact.expectedOpeningTranscriptSurface
abbrev rowWord? := Nightstream.Chip8.ExternalReleaseArtifact.rowWord?
abbrev claimedShiftValuesMatch := Nightstream.Chip8.ExternalReleaseArtifact.claimedShiftValuesMatch
abbrev stage3ViewMatchesFrame := Nightstream.Chip8.ExternalReleaseArtifact.stage3ViewMatchesFrame
abbrev allStage3ViewsMatchFrames := Nightstream.Chip8.ExternalReleaseArtifact.allStage3ViewsMatchFrames
abbrev allKernelManifestClaimsAreKernel :=
  Nightstream.Chip8.ExternalReleaseArtifact.allKernelManifestClaimsAreKernel
abbrev manifestExpectedClaimCount := Nightstream.Chip8.ExternalReleaseArtifact.manifestExpectedClaimCount
abbrev auditPathsReuseRowBinding := Nightstream.Chip8.ExternalReleaseArtifact.auditPathsReuseRowBinding
abbrev auditPreparedStepsMatchStage3 := Nightstream.Chip8.ExternalReleaseArtifact.auditPreparedStepsMatchStage3
abbrev auditRowsMatchFrames := Nightstream.Chip8.ExternalReleaseArtifact.auditRowsMatchFrames
abbrev TraceSurfaceBound := Nightstream.Chip8.ExternalReleaseArtifact.TraceSurfaceBound
abbrev ExportSurfaceBound := Nightstream.Chip8.ExternalReleaseArtifact.ExportSurfaceBound
abbrev BundleSurfaceBound := Nightstream.Chip8.ExternalReleaseArtifact.BundleSurfaceBound
abbrev Stage3SourceLengthsAgree := Nightstream.Chip8.ExternalReleaseArtifact.Stage3SourceLengthsAgree
abbrev Stage3SourcesMatchFrames := Nightstream.Chip8.ExternalReleaseArtifact.Stage3SourcesMatchFrames
abbrev BundleLengthMatchesFrames := Nightstream.Chip8.ExternalReleaseArtifact.BundleLengthMatchesFrames
abbrev ExportMatchesBundleLength := Nightstream.Chip8.ExternalReleaseArtifact.ExportMatchesBundleLength
abbrev SemanticRowsMatchBundleLength :=
  Nightstream.Chip8.ExternalReleaseArtifact.SemanticRowsMatchBundleLength
abbrev TranscriptSurfaceBound := Nightstream.Chip8.ExternalReleaseArtifact.TranscriptSurfaceBound
abbrev openingTranscriptExactClaimsMatchManifest :=
  Nightstream.Chip8.ExternalReleaseArtifact.openingTranscriptExactClaimsMatchManifest
abbrev openingTranscriptRefinementCountMatchesExactOpenings :=
  Nightstream.Chip8.ExternalReleaseArtifact.openingTranscriptRefinementCountMatchesExactOpenings
abbrev OpeningTranscriptSurfaceBound :=
  Nightstream.Chip8.ExternalReleaseArtifact.OpeningTranscriptSurfaceBound
abbrev ErrorSurfaceListsConform := Nightstream.Chip8.ExternalReleaseArtifact.ErrorSurfaceListsConform
abbrev Root0IdsMatchBindings := Nightstream.Chip8.ExternalReleaseArtifact.Root0IdsMatchBindings
abbrev RootManifestEmpty := Nightstream.Chip8.ExternalReleaseArtifact.RootManifestEmpty
abbrev KernelManifestSources := Nightstream.Chip8.ExternalReleaseArtifact.KernelManifestSources
abbrev KernelManifestCount := Nightstream.Chip8.ExternalReleaseArtifact.KernelManifestCount
abbrev AuditLengthsConform := Nightstream.Chip8.ExternalReleaseArtifact.AuditLengthsConform
abbrev AuditRowsMatchFrames := Nightstream.Chip8.ExternalReleaseArtifact.AuditRowsMatchFrames
abbrev AuditReuseRowBinding := Nightstream.Chip8.ExternalReleaseArtifact.AuditReuseRowBinding
abbrev AuditPreparedStepsMatchStage3 :=
  Nightstream.Chip8.ExternalReleaseArtifact.AuditPreparedStepsMatchStage3
abbrev ImportedReleaseArtifactBound :=
  Nightstream.Chip8.ExternalReleaseArtifact.ImportedReleaseArtifactBound

end ExternalReleaseArtifactInterface

end Nightstream.Chip8
