import Nightstream.Chip8.Kernel.ExternalReleaseArtifactAudit

namespace Nightstream.Chip8

namespace ExternalReleaseArtifactAuditInterface

abbrev checkTraceSurface := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkTraceSurface
abbrev checkExportSurface := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkExportSurface
abbrev checkBundleSurface := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkBundleSurface
abbrev checkStage3SourceLengths := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkStage3SourceLengths
abbrev checkStage3SourcesMatchFrames :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkStage3SourcesMatchFrames
abbrev checkBundleLengthMatchesFrames :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkBundleLengthMatchesFrames
abbrev checkExportMatchesBundleLength :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkExportMatchesBundleLength
abbrev checkSemanticRowsMatchBundleLength :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkSemanticRowsMatchBundleLength
abbrev checkTranscriptSurface := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkTranscriptSurface
abbrev checkOpeningTranscriptSurface :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkOpeningTranscriptSurface
abbrev checkErrorSurfaceLists := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkErrorSurfaceLists
abbrev checkRoot0IdsMatchBindings := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkRoot0IdsMatchBindings
abbrev checkRootManifestEmpty := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkRootManifestEmpty
abbrev checkKernelManifestSources := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkKernelManifestSources
abbrev checkKernelManifestCount := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkKernelManifestCount
abbrev checkAuditLengths := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkAuditLengths
abbrev checkAuditRowsMatchFrames := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkAuditRowsMatchFrames
abbrev checkAuditReuseRowBinding := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkAuditReuseRowBinding
abbrev checkAuditPreparedSteps := Nightstream.Chip8.ExternalReleaseArtifactAudit.checkAuditPreparedSteps
abbrev checkImportedReleaseArtifact :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.checkImportedReleaseArtifact
abbrev ImportedReleaseArtifactAccepted :=
  Nightstream.Chip8.ExternalReleaseArtifactAudit.ImportedReleaseArtifactAccepted
abbrev importedReleaseArtifactAccepted_iff_bound :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAccepted_iff_bound
abbrev importedReleaseArtifactAccepted_of_bound :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAccepted_of_bound
abbrev importedReleaseArtifactAuditSound :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAuditSound
abbrev importedReleaseArtifactAuditImpliesBundleLength_eq_semanticRows :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAuditImpliesBundleLength_eq_semanticRows
abbrev importedReleaseArtifactAuditImpliesPreparedStepCount_eq_bundleLength :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAuditImpliesPreparedStepCount_eq_bundleLength
abbrev importedReleaseArtifactAuditImpliesAuditReuseRowBinding :=
  @Nightstream.Chip8.ExternalReleaseArtifactAudit.importedReleaseArtifactAuditImpliesAuditReuseRowBinding

end ExternalReleaseArtifactAuditInterface

end Nightstream.Chip8
