import Nightstream.Chip8.Kernel.KernelArtifactAudit

namespace Nightstream.Chip8

namespace KernelArtifactAuditInterface

abbrev F := Nightstream.Chip8.KernelArtifactAudit.F
abbrev Program := Nightstream.Chip8.KernelArtifactAudit.Program
abbrev MachineState := Nightstream.Chip8.KernelArtifactAudit.MachineState
abbrev InitialState := Nightstream.Chip8.KernelArtifactAudit.InitialState
abbrev ExternalSchedule := Nightstream.Chip8.KernelArtifactAudit.ExternalSchedule
abbrev ExecutionFrame := Nightstream.Chip8.KernelArtifactAudit.ExecutionFrame
abbrev ExecutionInputContext := Nightstream.Chip8.KernelArtifactAudit.ExecutionInputContext
abbrev RootEncode := @Nightstream.Chip8.KernelArtifactAudit.RootEncode
abbrev checkKernelTraceSurface :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelTraceSurface
abbrev checkKernelExportSurface :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelExportSurface
abbrev checkKernelAuditSurface :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelAuditSurface
abbrev checkKernelManifestSurface' :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelManifestSurface'
abbrev checkKernelTranscriptSurface :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelTranscriptSurface
abbrev checkKernelErrorSurface :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelErrorSurface
abbrev checkKernelExecutionDigest :=
  @Nightstream.Chip8.KernelArtifactAudit.checkKernelExecutionDigest
abbrev KernelArtifactAuditAccepted :=
  @Nightstream.Chip8.KernelArtifactAudit.KernelArtifactAuditAccepted
abbrev kernelArtifactAuditSound :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditSound
abbrev kernelArtifactAuditImpliesKernelSoundnessConclusion :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesKernelSoundnessConclusion
abbrev kernelArtifactAuditImpliesAuthenticatedChunkTrace :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesAuthenticatedChunkTrace
abbrev kernelArtifactAuditImpliesStage2TemporalSeeds :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesStage2TemporalSeeds
abbrev kernelArtifactAuditImpliesTemporalSupport :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesTemporalSupport
abbrev kernelArtifactAuditImpliesAuthenticatedExecutionTrace :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesAuthenticatedExecutionTrace
abbrev kernelArtifactAuditImpliesPreparedStepExport :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesPreparedStepExport
abbrev kernelArtifactAuditImpliesRowProjectionSummary :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesRowProjectionSummary
abbrev kernelArtifactAuditImpliesBridgeBindingSummary :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesBridgeBindingSummary
abbrev kernelArtifactAuditImpliesKernelClaimsFixedInRoot0 :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesKernelClaimsFixedInRoot0
abbrev kernelArtifactAuditImpliesKernelRootCommitmentsDisjoint :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesKernelRootCommitmentsDisjoint
abbrev kernelArtifactAuditImpliesChallengeAfterPhase0 :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesChallengeAfterPhase0
abbrev kernelArtifactAuditImpliesStage1TerminalAfterPhase0 :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesStage1TerminalAfterPhase0
abbrev kernelArtifactAuditImpliesStage2TerminalAfterPhase0 :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesStage2TerminalAfterPhase0
abbrev kernelArtifactAuditImpliesRowBindingCoverage :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesRowBindingCoverage
abbrev kernelArtifactAuditImpliesEmitKernelOpeningClaimsLast :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesEmitKernelOpeningClaimsLast
abbrev kernelArtifactAuditImpliesNegligibleTotal :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesNegligibleTotal
abbrev kernelArtifactAuditImpliesTraceLinkBound :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesTraceLinkBound
abbrev kernelArtifactAuditImpliesExecutionLinked :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesExecutionLinked
abbrev kernelArtifactAuditImpliesExecutionCorrect :=
  @Nightstream.Chip8.KernelArtifactAudit.kernelArtifactAuditImpliesExecutionCorrect

end KernelArtifactAuditInterface

end Nightstream.Chip8
