import Nightstream.FoldAdmissibility

namespace Nightstream

namespace FoldAdmissibilityInterface

abbrev mainLaneAdmissible_implies_homogeneous :=
  @Nightstream.mainLaneAdmissible_implies_homogeneous

abbrev separateFoldSupported_implies_homogeneous :=
  @Nightstream.separateFoldSupported_implies_homogeneous

abbrev classifyFamily_eq_mergeMain_of_mainLaneAdmissible :=
  @Nightstream.classifyFamily_eq_mergeMain_of_mainLaneAdmissible

abbrev classifyFamily_eq_foldSeparate_of_separateFoldSupported_not_main :=
  @Nightstream.classifyFamily_eq_foldSeparate_of_separateFoldSupported_not_main

abbrev classifyFamily_eq_exportFinal_of_not_homogeneous :=
  @Nightstream.classifyFamily_eq_exportFinal_of_not_homogeneous

abbrev mergeMain_members_have_main_shape :=
  @Nightstream.mergeMain_members_have_main_shape

abbrev classifyFamily_eq_exportFinal_of_not_main_no_support :=
  @Nightstream.classifyFamily_eq_exportFinal_of_not_main_no_support

end FoldAdmissibilityInterface

end Nightstream
