import Nightstream.ShardComposition

namespace Nightstream

namespace ShardCompositionInterface

abbrev FamilyPolicy := Nightstream.FamilyPolicy
noncomputable abbrev decideFamily := @Nightstream.decideFamily

abbrev decideFamily_eq_mergeMain_iff_mainLaneAdmissible :=
  @Nightstream.decideFamily_eq_mergeMain_iff_mainLaneAdmissible
abbrev projectionFamily_separateFoldSupported :=
  @Nightstream.projectionFamily_separateFoldSupported
abbrev projectionFamily_not_separateFoldSupported_of_not_support :=
  @Nightstream.projectionFamily_not_separateFoldSupported_of_not_support
abbrev ceProjection_decide_eq_mergeMain_iff :=
  @Nightstream.ceProjection_decide_eq_mergeMain_iff
abbrev ceProjectionSingleton_decide_eq_mergeMain_iff :=
  @Nightstream.ceProjectionSingleton_decide_eq_mergeMain_iff
abbrev ceProjectionSingleton_decide_eq_foldSeparate_of_supported_not_main :=
  @Nightstream.ceProjectionSingleton_decide_eq_foldSeparate_of_supported_not_main
abbrev ceProjectionSingleton_decide_eq_exportFinal_of_unsupported_not_main :=
  @Nightstream.ceProjectionSingleton_decide_eq_exportFinal_of_unsupported_not_main
abbrev projectionFamily_decide_eq_foldSeparate_of_supported_not_main :=
  @Nightstream.projectionFamily_decide_eq_foldSeparate_of_supported_not_main
abbrev projectionFamily_decide_eq_exportFinal_of_unsupported_not_main :=
  @Nightstream.projectionFamily_decide_eq_exportFinal_of_unsupported_not_main
abbrev shoutReadProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.shoutReadProjection_decide_eq_foldSeparate_of_supported
abbrev shoutReadProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.shoutReadProjection_decide_eq_exportFinal_of_unsupported
abbrev twistValProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.twistValProjection_decide_eq_foldSeparate_of_supported
abbrev twistValProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.twistValProjection_decide_eq_exportFinal_of_unsupported

end ShardCompositionInterface

end Nightstream
