import Nightstream.Rv64IM.Stage2.AuthenticatedHistorySemantics

namespace Nightstream.Rv64IM

namespace Stage2AuthenticatedHistorySemanticsInterface

abbrev Stage2AuthenticatedHistorySemantics := @Nightstream.Rv64IM.Stage2AuthenticatedHistorySemantics
abbrev adjacentStateClosed_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_stage2AuthenticatedHistorySemantics
abbrev registerTimelineBound_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.registerTimelineBound_of_stage2AuthenticatedHistorySemantics
abbrev ramTimelineBound_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.ramTimelineBound_of_stage2AuthenticatedHistorySemantics
abbrev stage2LinkageBound_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2LinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev registerLinkageBound_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.registerLinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev ramLinkageBound_of_stage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.ramLinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev stage2AuthenticatedHistorySemantics_of_temporalConsistency_and_twistConcreteBinding :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_temporalConsistency_and_twistConcreteBinding

end Stage2AuthenticatedHistorySemanticsInterface

end Nightstream.Rv64IM
