import Nightstream.Rv64IM.Stage2.ImportedAuthenticatedHistorySemantics

namespace Nightstream.Rv64IM

namespace ImportedAuthenticatedHistorySemanticsInterface

abbrev ImportedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.ImportedStage2AuthenticatedHistorySemantics
abbrev importedStage2AuthenticatedHistorySemanticsCheck :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemanticsCheck
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics
abbrev importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence

end ImportedAuthenticatedHistorySemanticsInterface

end Nightstream.Rv64IM
