import Nightstream.Rv64IM.Stage2.ImportedHistorySemantics

namespace Nightstream.Rv64IM

namespace ImportedHistorySemanticsInterface

abbrev ImportedStage2HistorySemantics := @Nightstream.Rv64IM.ImportedStage2HistorySemantics
abbrev importedStage2HistorySemanticsCheck := @Nightstream.Rv64IM.importedStage2HistorySemanticsCheck
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics
abbrev importedStage2HistorySemantics_of_importedStage2Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage2HistorySemantics_of_importedStage2Closure_and_sequence

end ImportedHistorySemanticsInterface

end Nightstream.Rv64IM
