import Nightstream.Rv64IM.Stage2.ImportedLocalSemantics

namespace Nightstream.Rv64IM

namespace ImportedLocalSemanticsInterface

abbrev stage2RegisterReadCount := Nightstream.Rv64IM.stage2RegisterReadCount
abbrev stage2RegisterWriteCount := Nightstream.Rv64IM.stage2RegisterWriteCount
abbrev stage2RamEventCount := Nightstream.Rv64IM.stage2RamEventCount
abbrev stage2TwistLinkCount := Nightstream.Rv64IM.stage2TwistLinkCount
abbrev executionRegisterReadCount := Nightstream.Rv64IM.executionRegisterReadCount
abbrev executionRegisterWriteCount := Nightstream.Rv64IM.executionRegisterWriteCount
abbrev executionRamEventCount := Nightstream.Rv64IM.executionRamEventCount
abbrev executionTwistLinkCount := Nightstream.Rv64IM.executionTwistLinkCount
abbrev ImportedStage2LocalSemantics := @Nightstream.Rv64IM.ImportedStage2LocalSemantics
abbrev importedStage2LocalSemanticsCheck := @Nightstream.Rv64IM.importedStage2LocalSemanticsCheck
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure
abbrev importedStage2LocalSemantics_of_importedStage2Closure_and_sequence :=
  @Nightstream.Rv64IM.importedStage2LocalSemantics_of_importedStage2Closure_and_sequence

end ImportedLocalSemanticsInterface

end Nightstream.Rv64IM
