import Nightstream.Rv64IM.Stage2.ImportedClosure

namespace Nightstream.Rv64IM

namespace ImportedClosureInterface

abbrev rowReadsRs1 := Nightstream.Rv64IM.rowReadsRs1
abbrev rowReadsRs2 := Nightstream.Rv64IM.rowReadsRs2
abbrev stage2SummaryOfExecutionRows := Nightstream.Rv64IM.stage2SummaryOfExecutionRows
abbrev ImportedStage2Closure := @Nightstream.Rv64IM.ImportedStage2Closure
abbrev importedStage2ClosureCheck := @Nightstream.Rv64IM.importedStage2ClosureCheck
abbrev stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure

end ImportedClosureInterface

end Nightstream.Rv64IM
