import Nightstream.Rv64IM.Stage2.RegisterHistoryProjection

namespace Nightstream.Rv64IM

namespace RegisterHistoryProjectionInterface

abbrev registerHistoryFamily := Nightstream.Rv64IM.registerHistoryFamily
abbrev RegisterHistoryRow := Nightstream.Rv64IM.RegisterHistoryRow
abbrev RegisterHistoryRowBound := @Nightstream.Rv64IM.RegisterHistoryRowBound
abbrev RegisterHistoryBundle := Nightstream.Rv64IM.RegisterHistoryBundle
abbrev registerHistoryRowBound_rs2Sink_of_not_usesRs2 :=
  @Nightstream.Rv64IM.registerHistoryRowBound_rs2Sink_of_not_usesRs2
abbrev registerHistoryRowBound_waSink_of_not_writesRd :=
  @Nightstream.Rv64IM.registerHistoryRowBound_waSink_of_not_writesRd
abbrev registerHistoryProjection := @Nightstream.Rv64IM.registerHistoryProjection
abbrev registerHistoryProjection_is_projectionFamily :=
  @Nightstream.Rv64IM.registerHistoryProjection_is_projectionFamily
abbrev registerHistoryProjection_not_mainLane :=
  @Nightstream.Rv64IM.registerHistoryProjection_not_mainLane
abbrev registerHistoryProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Rv64IM.registerHistoryProjection_decide_eq_foldSeparate_of_supported
abbrev registerHistoryProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Rv64IM.registerHistoryProjection_decide_eq_exportFinal_of_unsupported

end RegisterHistoryProjectionInterface

end Nightstream.Rv64IM
