import Nightstream.Rv64IM.Stage2.TwistTemporalInstantiation

namespace Nightstream.Rv64IM

namespace TwistTemporalInstantiationInterface

abbrev Stage2HistoryBundles := Nightstream.Rv64IM.Stage2HistoryBundles
abbrev stage2TemporalContextOfHistoryBundles :=
  @Nightstream.Rv64IM.stage2TemporalContextOfHistoryBundles
abbrev stage2TemporalClosureProofPackage_of_historyBundles :=
  @Nightstream.Rv64IM.stage2TemporalClosureProofPackage_of_historyBundles
abbrev adjacentStateClosed_of_stage2TemporalClosureProofPackage :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_stage2TemporalClosureProofPackage

end TwistTemporalInstantiationInterface

end Nightstream.Rv64IM
