import Nightstream.Chip8.Stage1.BytecodeFetchProjection

namespace Nightstream.Chip8

namespace BytecodeFetchProjectionInterface

abbrev bytecodeFetchFamily := Nightstream.Chip8.bytecodeFetchFamily
abbrev BytecodeFetchRecordBound := Nightstream.Chip8.BytecodeFetchRecordBound
abbrev bytecodeFetchProjection := @Nightstream.Chip8.bytecodeFetchProjection

abbrev bytecodeFetchRecordBound_of_fetchDecodeBound :=
  @Nightstream.Chip8.bytecodeFetchRecordBound_of_fetchDecodeBound
abbrev bytecodeFetchProjection_is_projectionFamily :=
  @Nightstream.Chip8.bytecodeFetchProjection_is_projectionFamily
abbrev bytecodeFetchProjection_not_mainLane :=
  @Nightstream.Chip8.bytecodeFetchProjection_not_mainLane
abbrev bytecodeFetchProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Chip8.bytecodeFetchProjection_decide_eq_foldSeparate_of_supported
abbrev bytecodeFetchProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Chip8.bytecodeFetchProjection_decide_eq_exportFinal_of_unsupported

end BytecodeFetchProjectionInterface

end Nightstream.Chip8
