import Nightstream.Chip8.Stage1.InstructionSemanticsLookupProjection

namespace Nightstream.Chip8

namespace InstructionSemanticsLookupProjectionInterface

abbrev instructionSemanticsLookupFamily := Nightstream.Chip8.instructionSemanticsLookupFamily
abbrev InstructionSemanticsLookupRecord := Nightstream.Chip8.InstructionSemanticsLookupRecord
abbrev InstructionSemanticsLookupRecordBound :=
  Nightstream.Chip8.InstructionSemanticsLookupRecordBound
abbrev instructionSemanticsLookupProjection :=
  @Nightstream.Chip8.instructionSemanticsLookupProjection

abbrev instructionSemanticsLookupRecord_existsUnique_of_fetchDecodeBound :=
  @Nightstream.Chip8.instructionSemanticsLookupRecord_existsUnique_of_fetchDecodeBound
abbrev instructionSemanticsLookupRecord_lookup_zero_of_noLookup :=
  @Nightstream.Chip8.instructionSemanticsLookupRecord_lookup_zero_of_noLookup
abbrev instructionSemanticsLookupRecord_burst_zero_of_nonMem :=
  @Nightstream.Chip8.instructionSemanticsLookupRecord_burst_zero_of_nonMem
abbrev instructionSemanticsLookupProjection_is_projectionFamily :=
  @Nightstream.Chip8.instructionSemanticsLookupProjection_is_projectionFamily
abbrev instructionSemanticsLookupProjection_not_mainLane :=
  @Nightstream.Chip8.instructionSemanticsLookupProjection_not_mainLane
abbrev instructionSemanticsLookupProjection_decide_eq_foldSeparate_of_supported :=
  @Nightstream.Chip8.instructionSemanticsLookupProjection_decide_eq_foldSeparate_of_supported
abbrev instructionSemanticsLookupProjection_decide_eq_exportFinal_of_unsupported :=
  @Nightstream.Chip8.instructionSemanticsLookupProjection_decide_eq_exportFinal_of_unsupported

end InstructionSemanticsLookupProjectionInterface

end Nightstream.Chip8
