import Nightstream.Chip8.Trace.RegisterTimeline

namespace Nightstream.Chip8

namespace RegisterTimelineInterface

abbrev F := Nightstream.Chip8.RegisterTimeline.F
abbrev MachineState := Nightstream.Chip8.RegisterTimeline.MachineState
abbrev ExecutionFrame := Nightstream.Chip8.RegisterTimeline.ExecutionFrame
abbrev RegisterValueTimeline := Nightstream.Chip8.RegisterTimeline.RegisterValueTimeline
abbrev RegisterIndexBound := Nightstream.Chip8.RegisterTimeline.RegisterIndexBound
abbrev RegisterAdjacentTraceBound :=
  @Nightstream.Chip8.RegisterTimeline.RegisterAdjacentTraceBound
abbrev registerTimelineOfTraceFrom :=
  @Nightstream.Chip8.RegisterTimeline.registerTimelineOfTraceFrom
abbrev registerTimelineOfTrace :=
  @Nightstream.Chip8.RegisterTimeline.registerTimelineOfTrace
abbrev RegisterAdjacentBound := @Nightstream.Chip8.RegisterTimeline.RegisterAdjacentBound
abbrev RegisterTemporalBoundFrom := @Nightstream.Chip8.RegisterTimeline.RegisterTemporalBoundFrom
abbrev RegisterTemporalBound := @Nightstream.Chip8.RegisterTimeline.RegisterTemporalBound
abbrev headRegisterPreBound_of_registerTemporalBoundFrom :=
  @Nightstream.Chip8.RegisterTimeline.headRegisterPreBound_of_registerTemporalBoundFrom
abbrev registerAdjacentBound_of_registerTemporalBoundFrom :=
  @Nightstream.Chip8.RegisterTimeline.registerAdjacentBound_of_registerTemporalBoundFrom
abbrev tailRegisterTemporalBoundFrom_of_registerTemporalBoundFrom :=
  @Nightstream.Chip8.RegisterTimeline.tailRegisterTemporalBoundFrom_of_registerTemporalBoundFrom
abbrev registerAdjacentBound_of_registerTemporalBound :=
  @Nightstream.Chip8.RegisterTimeline.registerAdjacentBound_of_registerTemporalBound
abbrev tailRegisterTemporalBound_of_registerTemporalBound :=
  @Nightstream.Chip8.RegisterTimeline.tailRegisterTemporalBound_of_registerTemporalBound
abbrev registerTemporalBoundFrom_of_adjacentTraceBound :=
  @Nightstream.Chip8.RegisterTimeline.registerTemporalBoundFrom_of_adjacentTraceBound
abbrev registerTemporalBound_of_adjacentTraceBound :=
  @Nightstream.Chip8.RegisterTimeline.registerTemporalBound_of_adjacentTraceBound
abbrev registerAdjacentTraceBound_of_registerTemporalBoundFrom :=
  @Nightstream.Chip8.RegisterTimeline.registerAdjacentTraceBound_of_registerTemporalBoundFrom
abbrev registerAdjacentTraceBound_of_registerTemporalBound :=
  @Nightstream.Chip8.RegisterTimeline.registerAdjacentTraceBound_of_registerTemporalBound

end RegisterTimelineInterface

end Nightstream.Chip8
