import Nightstream.Rv64IM.Trace.AlignedMemoryOpcodeSemantics

namespace Nightstream.Rv64IM

namespace AlignedMemoryOpcodeSemanticsInterface

noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_authenticatedChunkTrace
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_exactBoundaries

end AlignedMemoryOpcodeSemanticsInterface

end Nightstream.Rv64IM
