import Nightstream.Rv64IM.Trace.AuthenticatedTrace
import Nightstream.Rv64IM.Execution.ImportedSequenceSemanticsInterface
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedClosureInterface
import Nightstream.Rv64IM.Stage1.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage1.ImportedSemanticsInterface
import Nightstream.Rv64IM.Stage2.AuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedClosureInterface
import Nightstream.Rv64IM.Stage2.ImportedAuthenticatedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedHistorySemanticsInterface
import Nightstream.Rv64IM.Stage2.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedClosureInterface
import Nightstream.Rv64IM.Stage3.ImportedContinuitySemanticsInterface
import Nightstream.Rv64IM.Stage3.ExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedExportSemanticsInterface
import Nightstream.Rv64IM.Stage3.ImportedLocalSemanticsInterface
import Nightstream.Rv64IM.Trace.OpcodeFamilySemantics
import Nightstream.Rv64IM.Trace.WordArithmeticSemantics
import Nightstream.Rv64IM.Trace.AlignedMemoryOpcodeSemantics
import Nightstream.Rv64IM.Trace.NarrowMemoryHelperResultSemantics
import Nightstream.Rv64IM.Trace.NarrowMemoryPayloadSemantics

namespace Nightstream.Rv64IM

namespace AuthenticatedTraceInterface

abbrev AuthenticatedChunkTrace := @Nightstream.Rv64IM.AuthenticatedChunkTrace
abbrev authenticatedChunkTrace_executionCorrect :=
  @Nightstream.Rv64IM.authenticatedChunkTrace_executionCorrect
abbrev authenticatedChunkTrace_executionCorrect_on_chunkInput :=
  @Nightstream.Rv64IM.authenticatedChunkTrace_executionCorrect_on_chunkInput
abbrev mainLaneSemanticRows_eq_chunkInput_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.mainLaneSemanticRows_eq_chunkInput_of_authenticatedChunkTrace
abbrev traceLinkSemanticRows_eq_chunkInput_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.traceLinkSemanticRows_eq_chunkInput_of_authenticatedChunkTrace
abbrev mainLaneTraceBoundary_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.mainLaneTraceBoundary_of_authenticatedChunkTrace
abbrev traceLinkBoundary_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.traceLinkBoundary_of_authenticatedChunkTrace
abbrev ImportedExpandedRowSequenceSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedExpandedRowSequenceSemantics
abbrev importedExpandedRowSequenceSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedExpandedRowSequenceSemanticsCheck
abbrev preparedStepExportBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_authenticatedChunkTrace
abbrev expandedRowSequenceBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.expandedRowSequenceBound_of_authenticatedChunkTrace
abbrev expandedBytecodeExecutionBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.expandedBytecodeExecutionBound_of_authenticatedChunkTrace
abbrev fullHaltedExecutionClaim_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_authenticatedChunkTrace
abbrev authenticatedChunkTrace_adjacentStateClosed :=
  @Nightstream.Rv64IM.authenticatedChunkTrace_adjacentStateClosed
abbrev pcAdjacentBridge_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_authenticatedChunkTrace
abbrev prePc_eq_stage2PreStatePc_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.prePc_eq_stage2PreStatePc_of_authenticatedChunkTrace
abbrev postPc_eq_stage2PostStatePc_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.postPc_eq_stage2PostStatePc_of_authenticatedChunkTrace
abbrev registerTimelineBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.registerTimelineBound_of_authenticatedChunkTrace
abbrev ramTimelineBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ramTimelineBound_of_authenticatedChunkTrace
abbrev twistConcreteBinding_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.twistConcreteBinding_of_authenticatedChunkTrace
abbrev stage2LinkageBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.stage2LinkageBound_of_authenticatedChunkTrace
abbrev registerLinkageBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.registerLinkageBound_of_authenticatedChunkTrace
abbrev ramLinkageBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ramLinkageBound_of_authenticatedChunkTrace
abbrev Stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.Stage2AuthenticatedHistorySemantics
abbrev adjacentStateClosed_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_stage2AuthenticatedHistorySemantics
abbrev registerTimelineBound_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.registerTimelineBound_of_stage2AuthenticatedHistorySemantics
abbrev ramTimelineBound_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ramTimelineBound_of_stage2AuthenticatedHistorySemantics
abbrev stage2LinkageBound_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2LinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev registerLinkageBound_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.registerLinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev ramLinkageBound_of_stage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ramLinkageBound_of_stage2AuthenticatedHistorySemantics
abbrev stage2AuthenticatedHistorySemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.stage2AuthenticatedHistorySemantics_of_authenticatedChunkTrace
abbrev registerWriteValue_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.registerWriteValue_of_authenticatedChunkTrace
abbrev ramLoadMemVal_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ramLoadMemVal_of_authenticatedChunkTrace
abbrev ramStorePayload_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ramStorePayload_of_authenticatedChunkTrace
abbrev ramInactiveMemValZero_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ramInactiveMemValZero_of_authenticatedChunkTrace
abbrev stage1LinkageBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.stage1LinkageBound_of_authenticatedChunkTrace
abbrev stage1RowBindingOfExecutionRow_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1RowBindingOfExecutionRow
abbrev stage1SummaryOfExecutionRows_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1SummaryOfExecutionRows
abbrev ImportedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage1Closure
abbrev importedStage1ClosureCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage1ClosureCheck
abbrev stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1Summary_eq_stage1SummaryOfExecutionRows_of_importedStage1Closure
abbrev stage1Rows_length_eq_executionRows_length_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1Rows_length_eq_executionRows_length_of_importedStage1Closure
abbrev ImportedStage1ProjectionSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage1ProjectionSemantics
abbrev importedStage1ProjectionSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage1ProjectionSemanticsCheck
abbrev ImportedStage1LocalSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage1LocalSemantics
abbrev importedStage1LocalSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemanticsCheck
abbrev stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1FirstInSequenceCount_eq_executionFirstInSequenceCount_of_importedStage1Closure
abbrev importedStage1LocalSemantics_of_importedStage1Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage1LocalSemantics_of_importedStage1Closure_and_sequence
abbrev stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1EffectRowCount_eq_executionEffectRowCount_of_importedStage1Closure
abbrev stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1CommitRowCount_eq_executionCommitRowCount_of_importedStage1Closure
abbrev stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1RealRowCount_eq_executionRealRowCount_of_importedStage1Closure
abbrev stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage1PreservesX0Count_eq_executionPreservesX0Count_of_importedStage1Closure
abbrev stage2SummaryOfExecutionRows_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2SummaryOfExecutionRows
abbrev ImportedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage2Closure
abbrev importedStage2ClosureCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2ClosureCheck
abbrev stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2Summary_eq_stage2SummaryOfExecutionRows_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2Closure
abbrev ImportedStage2LocalSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage2LocalSemantics
abbrev importedStage2LocalSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemanticsCheck
abbrev ImportedStage2HistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage2HistorySemantics
abbrev importedStage2HistorySemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemanticsCheck
abbrev ImportedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage2AuthenticatedHistorySemantics
abbrev importedStage2AuthenticatedHistorySemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemanticsCheck
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2Closure
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2Closure
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2Closure
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2Closure
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2HistorySemantics
abbrev stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RegisterReadCount_eq_executionRegisterReadCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RegisterWriteCount_eq_executionRegisterWriteCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2RamEventCount_eq_executionRamEventCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2TwistLinkCount_eq_executionTwistLinkCount_of_importedStage2AuthenticatedHistorySemantics
abbrev stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage2TwistLinks_length_eq_executionRows_length_of_importedStage2AuthenticatedHistorySemantics
abbrev importedStage2LocalSemantics_of_importedStage2Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2LocalSemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2HistorySemantics_of_importedStage2Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2HistorySemantics_of_importedStage2Closure_and_sequence
abbrev importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage2AuthenticatedHistorySemantics_of_importedStage2Closure_and_sequence
abbrev stage3SummaryOfExecutionRows_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3SummaryOfExecutionRows
abbrev ImportedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage3Closure
abbrev importedStage3ClosureCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3ClosureCheck
abbrev stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3Summary_eq_stage3SummaryOfExecutionRows_of_importedStage3Closure
abbrev stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3Continuity_length_eq_realExecutionRows_length_of_importedStage3Closure
abbrev ImportedStage3LocalSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage3LocalSemantics
abbrev importedStage3LocalSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemanticsCheck
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3Closure
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3Closure
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3Closure
abbrev importedStage3LocalSemantics_of_importedStage3Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3LocalSemantics_of_importedStage3Closure_and_sequence
abbrev continuityEventLocalSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics
abbrev continuityEventLocalSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemanticsCheck
abbrev ImportedStage3ContinuitySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage3ContinuitySemantics
abbrev importedStage3ContinuitySemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemanticsCheck
abbrev ImportedStage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.ImportedStage3ExportSemantics
abbrev importedStage3ExportSemanticsCheck_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemanticsCheck
abbrev Stage3ContinuitySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.Stage3ContinuitySemantics
abbrev Stage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.Stage3ExportSemantics
abbrev pcAdjacentBridge_of_stage3ContinuitySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_stage3ContinuitySemantics
abbrev activePrefixContinuity_of_stage3ContinuitySemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.activePrefixContinuity_of_stage3ContinuitySemantics
abbrev fullHaltedExecutionClaim_of_stage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.fullHaltedExecutionClaim_of_stage3ExportSemantics
abbrev stage3ExportSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.stage3ExportSemantics_of_authenticatedChunkTrace
abbrev continuityEventLocalSemantics_of_mem_of_importedStage3Closure_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.continuityEventLocalSemantics_of_mem_of_importedStage3Closure
abbrev importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3ContinuitySemantics_of_importedStage3Closure_and_sequence
abbrev stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3ContinuityCount_eq_executionContinuityCount_of_importedStage3ExportSemantics
abbrev stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3FinalStepCount_eq_executionFinalStepCount_of_importedStage3ExportSemantics
abbrev stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3AllContinuityHold_eq_executionAllContinuityHold_of_importedStage3ExportSemantics
abbrev stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.stage3Halted_eq_executionHalted_of_importedStage3ExportSemantics
abbrev importedStage3ExportSemantics_of_importedStage3Closure_and_sequence_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.importedStage3ExportSemantics_of_importedStage3Closure_and_sequence
abbrev takenTargetAlignmentBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.takenTargetAlignmentBound_of_authenticatedChunkTrace
abbrev mulUNoOverflowBound_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.mulUNoOverflowBound_of_authenticatedChunkTrace
abbrev temporaryRegisterHygiene_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.temporaryRegisterHygiene_of_authenticatedChunkTrace
abbrev mulUNoOverflow_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.mulUNoOverflow_of_authenticatedChunkTrace
abbrev unsignedDivRemSpec_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.unsignedDivRemSpec_of_authenticatedChunkTrace
abbrev unsignedDivRemDeterministic_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.unsignedDivRemDeterministic_of_authenticatedChunkTrace
noncomputable abbrev canonicalOpcodeProofs_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.canonicalOpcodeProofs_of_authenticatedChunkTrace
noncomputable abbrev exactOpcodeFamilySemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_authenticatedChunkTrace
abbrev exactWordArithmeticSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_authenticatedChunkTrace
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_authenticatedChunkTrace
noncomputable abbrev exactNarrowMemoryHelperResultSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_authenticatedChunkTrace
noncomputable abbrev exactNarrowMemoryPayloadSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactNarrowMemoryPayloadSemantics_of_authenticatedChunkTrace
abbrev changeDivisorCorrect_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.changeDivisorCorrect_of_authenticatedChunkTrace
abbrev remainderFromDividendSign_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.remainderFromDividendSign_of_authenticatedChunkTrace
abbrev signedDivRemSpec_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.signedDivRemSpec_of_authenticatedChunkTrace
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_authenticatedTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end AuthenticatedTraceInterface

end Nightstream.Rv64IM
