import Nightstream.Rv64IM.Trace.ControlFlowOpcodeSemantics

namespace Nightstream.Rv64IM

namespace ControlFlowOpcodeSemanticsInterface

abbrev lane_isJal_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.lane_isJal_of_authenticatedChunkTrace
abbrev lane_isJalr_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.lane_isJalr_of_authenticatedChunkTrace
abbrev lane_isBranch_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.lane_isBranch_of_authenticatedChunkTrace
abbrev branchOp_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.branchOp_of_authenticatedChunkTrace
abbrev takenTargetAlignment_of_jal_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jal_authenticatedChunkTrace
abbrev takenTargetAlignment_of_jalr_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jalr_authenticatedChunkTrace
abbrev takenBranchMux_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.takenBranchMux_of_authenticatedChunkTrace
abbrev takenTargetAlignment_of_takenBranch_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_takenBranch_authenticatedChunkTrace
abbrev lane_isJal_of_exactBoundaries :=
  @Nightstream.Rv64IM.lane_isJal_of_exactBoundaries
abbrev takenTargetAlignment_of_jal_of_exactBoundaries :=
  @Nightstream.Rv64IM.takenTargetAlignment_of_jal_of_exactBoundaries

end ControlFlowOpcodeSemanticsInterface

end Nightstream.Rv64IM
