import Nightstream.Rv64IM.Trace.ExactTraceBoundaries
import Nightstream.Rv64IM.Trace.OpcodeFamilySemantics
import Nightstream.Rv64IM.Trace.WordArithmeticSemantics
import Nightstream.Rv64IM.Trace.AlignedMemoryOpcodeSemantics
import Nightstream.Rv64IM.Trace.NarrowMemoryHelperResultSemantics
import Nightstream.Rv64IM.Trace.NarrowMemoryPayloadSemantics

namespace Nightstream.Rv64IM

namespace ExactTraceBoundariesInterface

abbrev ExactTraceBoundaries := @Nightstream.Rv64IM.ExactTraceBoundaries
abbrev authenticatedChunkTrace_of_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedChunkTrace_of_exactBoundaries
abbrev executionCorrect_of_exactBoundaries :=
  @Nightstream.Rv64IM.executionCorrect_of_exactBoundaries
abbrev executionCorrect_on_exactPrefix_of_exactBoundaries :=
  @Nightstream.Rv64IM.executionCorrect_on_exactPrefix_of_exactBoundaries
abbrev traceLinkBoundary_of_exactBoundaries :=
  @Nightstream.Rv64IM.traceLinkBoundary_of_exactBoundaries
abbrev preparedStepExportBound_of_exactBoundaries :=
  @Nightstream.Rv64IM.preparedStepExportBound_of_exactBoundaries
abbrev adjacentStateClosed_of_exactBoundaries :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_exactBoundaries
abbrev pcAdjacentBridge_of_exactBoundaries :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_exactBoundaries
noncomputable abbrev canonicalOpcodeProofs_of_exactBoundaries :=
  @Nightstream.Rv64IM.canonicalOpcodeProofs_of_exactBoundaries
noncomputable abbrev exactOpcodeFamilySemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_exactBoundaries
abbrev exactWordArithmeticSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_exactBoundaries
noncomputable abbrev exactAlignedMemoryOpcodeSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactAlignedMemoryOpcodeSemantics_of_exactBoundaries
noncomputable abbrev exactNarrowMemoryHelperResultSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_exactBoundaries
noncomputable abbrev exactNarrowMemoryPayloadSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryPayloadSemantics_of_exactBoundaries

end ExactTraceBoundariesInterface

end Nightstream.Rv64IM
