import Nightstream.Rv64IM.Trace.MultiplyEncodedArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyEncodedArithmeticInterface

abbrev encodedArithmetic_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.encodedArithmetic_of_authenticatedChunkTrace_multiply
abbrev authenticatedEncodedArithmetic_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_authenticatedChunkTrace_multiply
abbrev encodedArithmetic_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.encodedArithmetic_of_exactBoundaries_multiply
abbrev authenticatedEncodedArithmetic_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_exactBoundaries_multiply

end MultiplyEncodedArithmeticInterface

end Nightstream.Rv64IM
