import Nightstream.Rv64IM.Trace.MultiplyOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace MultiplyOpcodeResultSemanticsInterface

abbrev encodedAluResult_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.encodedAluResult_of_authenticatedChunkTrace_multiply
abbrev authenticatedEncodedAluResult_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_authenticatedChunkTrace_multiply
abbrev encodedAluResult_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.encodedAluResult_of_exactBoundaries_multiply
abbrev authenticatedEncodedAluResult_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_exactBoundaries_multiply

end MultiplyOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
