import Nightstream.Rv64IM.Trace.MultiplyOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace MultiplyOpcodeSemanticsInterface

abbrev opcodeBound_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.opcodeBound_of_authenticatedChunkTrace_multiply
abbrev flags_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.flags_of_authenticatedChunkTrace_multiply
abbrev x0WritePreserved_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.x0WritePreserved_of_authenticatedChunkTrace_multiply
abbrev registerOperands_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.registerOperands_of_authenticatedChunkTrace_multiply
abbrev activeWrite_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.activeWrite_of_authenticatedChunkTrace_multiply
abbrev authenticatedWriteback_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeMultiply_authenticatedChunkTrace
abbrev routedWriteback_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.routedWriteback_of_activeMultiply_authenticatedChunkTrace
abbrev authenticatedRoutedWriteback_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeMultiply_authenticatedChunkTrace
abbrev encodedAluOut_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeMultiply_authenticatedChunkTrace
abbrev encodedAluResult_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeMultiply_authenticatedChunkTrace
abbrev authenticatedEncodedAluOut_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeMultiply_authenticatedChunkTrace
abbrev authenticatedEncodedAluResult_of_activeMultiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeMultiply_authenticatedChunkTrace
abbrev sequenceCorrect_of_multiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceCorrect_of_multiply_authenticatedChunkTrace
abbrev sequenceDeterministic_of_multiply_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_multiply_authenticatedChunkTrace
abbrev flags_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.flags_of_exactBoundaries_multiply
abbrev x0WritePreserved_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactBoundaries_multiply
abbrev registerOperands_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.registerOperands_of_exactBoundaries_multiply
abbrev activeWrite_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.activeWrite_of_exactBoundaries_multiply
abbrev authenticatedWriteback_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeMultiply_exactBoundaries
abbrev routedWriteback_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.routedWriteback_of_activeMultiply_exactBoundaries
abbrev authenticatedRoutedWriteback_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeMultiply_exactBoundaries
abbrev encodedAluOut_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeMultiply_exactBoundaries
abbrev encodedAluResult_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeMultiply_exactBoundaries
abbrev authenticatedEncodedAluOut_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeMultiply_exactBoundaries
abbrev authenticatedEncodedAluResult_of_activeMultiply_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeMultiply_exactBoundaries
abbrev normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulwRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_mulhsuRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end MultiplyOpcodeSemanticsInterface

end Nightstream.Rv64IM
