import Nightstream.Rv64IM.Trace.MultiplyWordArithmetic

namespace Nightstream.Rv64IM

namespace MultiplyWordArithmeticInterface

abbrev wordArithmetic_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.wordArithmetic_of_authenticatedChunkTrace_multiply
abbrev authenticatedWordArithmetic_of_authenticatedChunkTrace_multiply :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_authenticatedChunkTrace_multiply
abbrev wordArithmetic_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactBoundaries_multiply
abbrev authenticatedWordArithmetic_of_exactBoundaries_multiply :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactBoundaries_multiply

end MultiplyWordArithmeticInterface

end Nightstream.Rv64IM
