import Nightstream.Rv64IM.Trace.NarrowMemoryHelperResultSemantics

namespace Nightstream.Rv64IM

namespace NarrowMemoryHelperResultSemanticsInterface

abbrev exactNarrowMemoryHelperResultSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_authenticatedChunkTrace
abbrev loadExtractHelperResult_of_authenticatedChunkTrace_narrowMemory :=
  @Nightstream.Rv64IM.loadExtractHelperResult_of_authenticatedChunkTrace_narrowMemory
abbrev storeBlendHelperResult_of_authenticatedChunkTrace_narrowMemory :=
  @Nightstream.Rv64IM.storeBlendHelperResult_of_authenticatedChunkTrace_narrowMemory
abbrev exactNarrowMemoryHelperResultSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactNarrowMemoryHelperResultSemantics_of_exactBoundaries
abbrev loadExtractHelperResult_of_exactBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.loadExtractHelperResult_of_exactBoundaries_narrowMemory
abbrev storeBlendHelperResult_of_exactBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.storeBlendHelperResult_of_exactBoundaries_narrowMemory

end NarrowMemoryHelperResultSemanticsInterface

end Nightstream.Rv64IM
