import Nightstream.Rv64IM.Trace.NarrowMemoryOpcodeSemantics

namespace NarrowMemoryOpcodeSemanticsInterface

abbrev flags_of_authenticatedChunkTrace_narrowMemory :=
  @Nightstream.Rv64IM.flags_of_authenticatedChunkTrace_narrowMemory
abbrev x0WritePreserved_of_authenticatedChunkTrace_narrowMemory :=
  @Nightstream.Rv64IM.x0WritePreserved_of_authenticatedChunkTrace_narrowMemory
abbrev sequenceCorrect_of_narrowMemory_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceCorrect_of_narrowMemory_authenticatedChunkTrace
abbrev flags_of_exactBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.flags_of_exactBoundaries_narrowMemory
abbrev x0WritePreserved_of_exactBoundaries_narrowMemory :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactBoundaries_narrowMemory

end NarrowMemoryOpcodeSemanticsInterface
