import Nightstream.Rv64IM.Trace.NativeAluWordArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluWordArithmeticInterface

abbrev wordArithmetic_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.wordArithmetic_of_authenticatedChunkTrace_nativeAlu
abbrev authenticatedWordArithmetic_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_authenticatedChunkTrace_nativeAlu
abbrev wordArithmetic_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactBoundaries_nativeAlu
abbrev authenticatedWordArithmetic_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactBoundaries_nativeAlu

end NativeAluWordArithmeticInterface

end Nightstream.Rv64IM
