import Nightstream.Rv64IM.Trace.NativeAluEncodedArithmetic

namespace Nightstream.Rv64IM

namespace NativeAluEncodedArithmeticInterface

abbrev encodedArithmetic_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.encodedArithmetic_of_authenticatedChunkTrace_nativeAlu
abbrev authenticatedEncodedArithmetic_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_authenticatedChunkTrace_nativeAlu
abbrev encodedArithmetic_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.encodedArithmetic_of_exactBoundaries_nativeAlu
abbrev authenticatedEncodedArithmetic_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedArithmetic_of_exactBoundaries_nativeAlu

end NativeAluEncodedArithmeticInterface

end Nightstream.Rv64IM
