import Nightstream.Rv64IM.Trace.NativeAluOpcodeSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeSemanticsInterface

abbrev opcodeBound_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.opcodeBound_of_authenticatedChunkTrace_nativeAlu
abbrev flags_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.flags_of_authenticatedChunkTrace_nativeAlu
abbrev x0WritePreserved_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.x0WritePreserved_of_authenticatedChunkTrace_nativeAlu
abbrev registerOperands_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.registerOperands_of_authenticatedChunkTrace_nativeAlu
abbrev nonX0WriteFacts_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_authenticatedChunkTrace_nativeAlu
abbrev activeWrite_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.activeWrite_of_authenticatedChunkTrace_nativeAlu
abbrev passiveWrite_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.passiveWrite_of_authenticatedChunkTrace_nativeAlu
abbrev authenticatedWriteback_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeNativeAlu_authenticatedChunkTrace
abbrev routedWriteback_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.routedWriteback_of_activeNativeAlu_authenticatedChunkTrace
abbrev authenticatedRoutedWriteback_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeNativeAlu_authenticatedChunkTrace
abbrev encodedAluOut_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeNativeAlu_authenticatedChunkTrace
abbrev encodedAluResult_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeNativeAlu_authenticatedChunkTrace
abbrev authenticatedEncodedAluOut_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeNativeAlu_authenticatedChunkTrace
abbrev authenticatedEncodedAluResult_of_activeNativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeNativeAlu_authenticatedChunkTrace
abbrev ecall_terminates_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.ecall_terminates_of_authenticatedChunkTrace
abbrev sequenceCorrect_of_nativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceCorrect_of_nativeAlu_authenticatedChunkTrace
abbrev sequenceDeterministic_of_nativeAlu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_nativeAlu_authenticatedChunkTrace
abbrev flags_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.flags_of_exactBoundaries_nativeAlu
abbrev x0WritePreserved_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.x0WritePreserved_of_exactBoundaries_nativeAlu
abbrev registerOperands_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.registerOperands_of_exactBoundaries_nativeAlu
abbrev nonX0WriteFacts_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.nonX0WriteFacts_of_exactBoundaries_nativeAlu
abbrev activeWrite_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.activeWrite_of_exactBoundaries_nativeAlu
abbrev passiveWrite_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.passiveWrite_of_exactBoundaries_nativeAlu
abbrev authenticatedWriteback_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedWriteback_of_activeNativeAlu_exactBoundaries
abbrev routedWriteback_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.routedWriteback_of_activeNativeAlu_exactBoundaries
abbrev authenticatedRoutedWriteback_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedRoutedWriteback_of_activeNativeAlu_exactBoundaries
abbrev encodedAluOut_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.encodedAluOut_of_activeNativeAlu_exactBoundaries
abbrev encodedAluResult_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.encodedAluResult_of_activeNativeAlu_exactBoundaries
abbrev authenticatedEncodedAluOut_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluOut_of_activeNativeAlu_exactBoundaries
abbrev authenticatedEncodedAluResult_of_activeNativeAlu_exactBoundaries :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_activeNativeAlu_exactBoundaries
abbrev ecall_terminates_of_exactBoundaries :=
  @Nightstream.Rv64IM.ecall_terminates_of_exactBoundaries

end NativeAluOpcodeSemanticsInterface

end Nightstream.Rv64IM
