import Nightstream.Rv64IM.Trace.NativeAluOpcodeResultSemantics

namespace Nightstream.Rv64IM

namespace NativeAluOpcodeResultSemanticsInterface

abbrev encodedAluResult_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.encodedAluResult_of_authenticatedChunkTrace_nativeAlu
abbrev authenticatedEncodedAluResult_of_authenticatedChunkTrace_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_authenticatedChunkTrace_nativeAlu
abbrev encodedAluResult_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.encodedAluResult_of_exactBoundaries_nativeAlu
abbrev authenticatedEncodedAluResult_of_exactBoundaries_nativeAlu :=
  @Nightstream.Rv64IM.authenticatedEncodedAluResult_of_exactBoundaries_nativeAlu

end NativeAluOpcodeResultSemanticsInterface

end Nightstream.Rv64IM
