import Nightstream.Rv64IM.Trace.OpcodeClassSemantics

namespace Nightstream.Rv64IM

namespace OpcodeClassSemanticsInterface

noncomputable abbrev canonicalOpcodeClassSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_authenticatedChunkTrace
noncomputable abbrev nativeAluFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.nativeAluFacts_of_authenticatedChunkTrace
noncomputable abbrev wordShiftFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.wordShiftFacts_of_authenticatedChunkTrace
noncomputable abbrev controlFlowFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.controlFlowFacts_of_authenticatedChunkTrace
noncomputable abbrev narrowMemoryFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_authenticatedChunkTrace
noncomputable abbrev multiplyFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.multiplyFacts_of_authenticatedChunkTrace
noncomputable abbrev unsignedDivRemFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_authenticatedChunkTrace
noncomputable abbrev signedDivRemFacts_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_authenticatedChunkTrace
noncomputable abbrev canonicalOpcodeClassSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.canonicalOpcodeClassSemantics_of_exactBoundaries
noncomputable abbrev nativeAluFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.nativeAluFacts_of_exactBoundaries
noncomputable abbrev wordShiftFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.wordShiftFacts_of_exactBoundaries
noncomputable abbrev controlFlowFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.controlFlowFacts_of_exactBoundaries
noncomputable abbrev narrowMemoryFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.narrowMemoryFacts_of_exactBoundaries
noncomputable abbrev multiplyFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.multiplyFacts_of_exactBoundaries
noncomputable abbrev unsignedDivRemFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.unsignedDivRemFacts_of_exactBoundaries
noncomputable abbrev signedDivRemFacts_of_exactBoundaries :=
  @Nightstream.Rv64IM.signedDivRemFacts_of_exactBoundaries

end OpcodeClassSemanticsInterface

end Nightstream.Rv64IM
