import Nightstream.Rv64IM.Trace.OpcodeFamilySemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace OpcodeFamilySemanticsInterface

noncomputable abbrev exactOpcodeFamilySemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_authenticatedChunkTrace
noncomputable abbrev exactOpcodeFamilySemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactOpcodeFamilySemantics_of_exactBoundaries
abbrev normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_mulhRefinedMultiplyOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_opcodeFamilyTraceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end OpcodeFamilySemanticsInterface

end Nightstream.Rv64IM
