import Nightstream.Rv64IM.Trace.SignedDivRemOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace SignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_authenticatedChunkTrace_signedDivRem :=
  @Nightstream.Rv64IM.opcodeBound_of_authenticatedChunkTrace_signedDivRem
abbrev div_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.div_flags_of_authenticatedChunkTrace
abbrev rem_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.rem_flags_of_authenticatedChunkTrace
abbrev divw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.divw_flags_of_authenticatedChunkTrace
abbrev remw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.remw_flags_of_authenticatedChunkTrace
abbrev spec_of_signedDiv_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.spec_of_signedDiv_authenticatedChunkTrace
abbrev spec_of_signedRem_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.spec_of_signedRem_authenticatedChunkTrace
abbrev div_flags_of_exactBoundaries :=
  @Nightstream.Rv64IM.div_flags_of_exactBoundaries
abbrev spec_of_signedDiv_of_exactBoundaries :=
  @Nightstream.Rv64IM.spec_of_signedDiv_of_exactBoundaries
abbrev normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remwRefinedSignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end SignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
