import Nightstream.Rv64IM.Trace.TemporalConsistency

namespace Nightstream.Rv64IM

namespace TemporalConsistencyInterface

abbrev TemporalConsistency := @Nightstream.Rv64IM.TemporalConsistency
abbrev TemporalConsistencyProofPackage := @Nightstream.Rv64IM.TemporalConsistencyProofPackage
abbrev adjacentStateClosed_of_temporalConsistency :=
  @Nightstream.Rv64IM.adjacentStateClosed_of_temporalConsistency
abbrev pcAdjacentBridge_of_temporalConsistency :=
  @Nightstream.Rv64IM.pcAdjacentBridge_of_temporalConsistency
abbrev registerTimelineBound_of_temporalConsistency :=
  @Nightstream.Rv64IM.registerTimelineBound_of_temporalConsistency
abbrev ramTimelineBound_of_temporalConsistency :=
  @Nightstream.Rv64IM.ramTimelineBound_of_temporalConsistency
abbrev registerSemanticRows_eq_stage2_of_temporalConsistency :=
  @Nightstream.Rv64IM.registerSemanticRows_eq_stage2_of_temporalConsistency
abbrev ramSemanticRows_eq_stage2_of_temporalConsistency :=
  @Nightstream.Rv64IM.ramSemanticRows_eq_stage2_of_temporalConsistency
abbrev pcSemanticRows_eq_stage2_of_temporalConsistency :=
  @Nightstream.Rv64IM.pcSemanticRows_eq_stage2_of_temporalConsistency
abbrev prePc_eq_stage2PreStatePc_of_temporalConsistency :=
  @Nightstream.Rv64IM.prePc_eq_stage2PreStatePc_of_temporalConsistency
abbrev postPc_eq_stage2PostStatePc_of_temporalConsistency :=
  @Nightstream.Rv64IM.postPc_eq_stage2PostStatePc_of_temporalConsistency

end TemporalConsistencyInterface

end Nightstream.Rv64IM
