import Nightstream.Rv64IM.Trace.UnsignedDivRemOpcodeSemantics
import Nightstream.Rv64IM.Execution.HardOpLoweringRefinementSemanticsInterface

namespace Nightstream.Rv64IM

namespace UnsignedDivRemOpcodeSemanticsInterface

abbrev opcodeBound_of_authenticatedChunkTrace_unsignedDivRem :=
  @Nightstream.Rv64IM.opcodeBound_of_authenticatedChunkTrace_unsignedDivRem
abbrev divu_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.divu_flags_of_authenticatedChunkTrace
abbrev remu_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.remu_flags_of_authenticatedChunkTrace
abbrev divuw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.divuw_flags_of_authenticatedChunkTrace
abbrev remuw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.remuw_flags_of_authenticatedChunkTrace
abbrev spec_of_unsignedDivu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.spec_of_unsignedDivu_authenticatedChunkTrace
abbrev spec_of_unsignedRemu_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.spec_of_unsignedRemu_authenticatedChunkTrace
abbrev deterministic_of_unsignedDivRem_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.deterministic_of_unsignedDivRem_authenticatedChunkTrace
abbrev divu_flags_of_exactBoundaries :=
  @Nightstream.Rv64IM.divu_flags_of_exactBoundaries
abbrev spec_of_unsignedDivu_of_exactBoundaries :=
  @Nightstream.Rv64IM.spec_of_unsignedDivu_of_exactBoundaries
abbrev normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_divuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.normalizedReference_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.sequenceMetadataBound_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.closureSuffixScratchOnly_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.uniqueCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics
abbrev effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_traceSurface :=
  @Nightstream.Rv64IM.effectRowPrecedesCommitRow_of_remuwRefinedUnsignedDivRemOpcodeSemantics_of_hardOpLoweringRefinementSemantics

end UnsignedDivRemOpcodeSemanticsInterface

end Nightstream.Rv64IM
