import Nightstream.Rv64IM.Trace.WordShiftOpcodeSemantics

namespace Nightstream.Rv64IM

namespace WordShiftOpcodeSemanticsInterface

abbrev opcodeBound_of_authenticatedChunkTrace_wordShift :=
  @Nightstream.Rv64IM.opcodeBound_of_authenticatedChunkTrace_wordShift
abbrev flags_of_authenticatedChunkTrace_wordShift :=
  @Nightstream.Rv64IM.flags_of_authenticatedChunkTrace_wordShift
abbrev sraw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sraw_flags_of_authenticatedChunkTrace
abbrev sraiw_flags_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sraiw_flags_of_authenticatedChunkTrace
abbrev sequenceCorrect_of_wordShift_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShift_authenticatedChunkTrace
abbrev sequenceDeterministic_of_wordShift_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.sequenceDeterministic_of_wordShift_authenticatedChunkTrace
abbrev sraw_flags_of_exactBoundaries :=
  @Nightstream.Rv64IM.sraw_flags_of_exactBoundaries
abbrev sequenceCorrect_of_wordShift_of_exactBoundaries :=
  @Nightstream.Rv64IM.sequenceCorrect_of_wordShift_of_exactBoundaries

end WordShiftOpcodeSemanticsInterface

end Nightstream.Rv64IM
