import Nightstream.Rv64IM.Trace.WordShiftWordArithmetic

namespace Nightstream.Rv64IM

namespace WordShiftWordArithmeticInterface

abbrev wordArithmetic_of_authenticatedChunkTrace_wordShift :=
  @Nightstream.Rv64IM.wordArithmetic_of_authenticatedChunkTrace_wordShift
abbrev authenticatedWordArithmetic_of_authenticatedChunkTrace_wordShift :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_authenticatedChunkTrace_wordShift
abbrev wordArithmetic_of_exactBoundaries_wordShift :=
  @Nightstream.Rv64IM.wordArithmetic_of_exactBoundaries_wordShift
abbrev authenticatedWordArithmetic_of_exactBoundaries_wordShift :=
  @Nightstream.Rv64IM.authenticatedWordArithmetic_of_exactBoundaries_wordShift

end WordShiftWordArithmeticInterface

end Nightstream.Rv64IM
