import Nightstream.Rv64IM.Trace.WordArithmeticSemantics

namespace Nightstream.Rv64IM

namespace WordArithmeticSemanticsInterface

abbrev exactWordArithmeticSemantics_of_authenticatedChunkTrace :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_authenticatedChunkTrace
abbrev exactWordArithmeticSemantics_of_exactBoundaries :=
  @Nightstream.Rv64IM.exactWordArithmeticSemantics_of_exactBoundaries

end WordArithmeticSemanticsInterface

end Nightstream.Rv64IM
